### ISSUE TITLE
不能刮削，提示连接错误

### ISSUE THREAD

**Issue by zpakof** [yoshiko2/Movie_Data_Capture#1007]
用这个软件陆陆续续一年了，没有一次bug，环境是软路由，节点默认日本，换了新加坡，台湾、香港，美国的都试了和关闭使用clash翻。均错误，梯子一直都是这个梯子，咋解决

!] [NTRD-008] As Number Processing for 'E:\Download\刮削文件夹\1\NTRD-008-C.mp4'
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]Invalid URL '': No scheme supplied. Perhaps you meant https://?
[-]Connect Failed! Please check your Proxy or Network!
[-]Image Download :Error Connect Failed
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]Invalid URL '': No scheme supplied. Perhaps you meant https://?
[-]Connect Failed! Please check your Proxy or Network!
[-]Image Download :Error Connect Failed
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]Invalid URL '': No scheme supplied. Perhaps you meant https://?
[-]Connect Failed! Please check your Proxy or Network!
[-]Image Download :Error Connect Failed
[-]Connect Failed! Please check your Proxy or Network!
[!]Image Download Failed! Trying again. [{}/3] 1
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]Invalid URL '': No scheme supplied. Perhaps you meant https://?
[-]Connect Failed! Please check your Proxy or Network!
[-]Image Download :Error Connect Failed
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]Invalid URL '': No scheme supplied. Perhaps you meant https://?
[-]Connect Failed! Please check your Proxy or Network!
[-]Image Download :Error Connect Failed
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]Invalid URL '': No scheme supplied. Perhaps you meant https://?
[-]Connect Failed! Please check your Proxy or Network!
[-]Image Download :Error Connect Failed
[-]Connect Failed! Please check your Proxy or Network!
[!]Image Download Failed! Trying again. [{}/3] 2
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]Invalid URL '': No scheme supplied. Perhaps you meant https://?
[-]Connect Failed! Please check your Proxy or Network!
[-]Image Download :Error Connect Failed
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]Invalid URL '': No scheme supplied. Perhaps you meant https://?
[-]Connect Failed! Please check your Proxy or Network!
[-]Image Download :Error Connect Failed
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]Invalid URL '': No scheme supplied. Perhaps you meant https://?
[-]Connect Failed! Please check your Proxy or Network!
[-]Image Download :Error Connect Failed
[-]Connect Failed! Please check your Proxy or Network!
[!]Image Download Failed! Trying again. [{}/3] 3
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]Invalid URL '': No scheme supplied. Perhaps you meant https://?
[-]Connect Failed! Please check your Proxy or Network!
[-]Image Download :Error Connect Failed
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]Invalid URL '': No scheme supplied. Perhaps you meant https://?
[-]Connect Failed! Please check your Proxy or Network!
[-]Image Download :Error Connect Failed
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]Invalid URL '': No scheme supplied. Perhaps you meant https://?
[-]Connect Failed! Please check your Proxy or Network!
[-]Image Download :Error Connect Failed
[-]Connect Failed! Please check your Proxy or Network!
[Errno 2] No such file or directory: 'JAV_output\\柳田弥生\\NTRD-008\\thumb'

**Comment by zpakof** [comment]
软件也是最新的 也重新下载过了。也是错误

**Comment by auroracamus** [comment]
是不是查询的频率太高，梯子的IP被封了？你用web页面能正常访问并查询那些网站么？

**Comment by Blackhihop** [comment]
更新后就这样了哦
[*]================= Movie Data Capture =================
[*]                        6.6.1                         
[*]======================================================
[*] - Windows-10-10.0.19045-SP0 
[*] - AMD64 - Python-3.10.11
[*]======================================================
[*] - 严禁在墙内宣传本项目 - 
[*]======================================================
[+]Start at 2023-05-04 23:01:57
[+]Load Config file 'F:\已完成\config.ini'.
[+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30
[-]Update check failed! 'tag_name'
[+]Find 4 movies.
[*]======================================================
[!]                - 25.0% [1/4] -             23:01:57
[!] [CEMD-318] As Number Processing for 'F:\已完成\CEMD-318.mp4'
[!] 出错啦
No module named 'scrapinglib.madou'
[!] 出错啦
No module named 'scrapinglib.javbus'
[!] 出错啦
No module named 'scrapinglib.airav'
[!] 出错啦
No module named 'scrapinglib.jav321'
[!] 出错啦
No module named 'scrapinglib.fanza'
[!] 出错啦
No module named 'scrapinglib.xcity'
[!] 出错啦
No module named 'scrapinglib.mgstage'
[!] 出错啦
No module named 'scrapinglib.fc2'
[!] 出错啦
No module named 'scrapinglib.avsox'
[!] 出错啦
No module named 'scrapinglib.dlsite'
[!] 出错啦
No module named 'scrapinglib.carib'
[!] 出错啦
No module named 'scrapinglib.getchu'
[!] 出错啦
No module named 'scrapinglib.javdb'
[!] 出错啦
No module named 'scrapinglib.gcolle'
[!] 出错啦
No module named 'scrapinglib.javday'
[!] 出错啦
No module named 'scrapinglib.javmenu'
[-]Movie Number [CEMD-318] not found!
[-]Movie Number not found!
[*]======================================================

**Comment by lljyy227** [comment]
6.6.2会出错，我也会出现连接错误，但是6.5.2就没有问题，ini配置文件用默认的，无任何修改，其它网络环境也是一样的

**Comment by adaelves** [comment]
6.5.2用起来没问题，挂梯子的话速度还挺快。今天更新的6.6.2总提示连接错误

**Comment by BellChole** [comment]
我的更新以后，用起来就是这个样子，但是单独上那些网站又可以上去
[*]================= Movie Data Capture =================
[*]                        6.6.2
[*]======================================================
[*] - Windows-10-10.0.22621-SP0
[*] - AMD64 - Python-3.10.11
[*]======================================================
[*] - 严禁在墙内宣传本项目 -
[*]======================================================
[+]Start at 2023-05-07 12:26:17
[+]Load Config file 'M:\重新下\新建文件夹\config.ini'.
[+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[-]Connect Failed! Please check your Proxy or Network!
[-]Connect retry 1/3
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[-]Connect Failed! Please check your Proxy or Network!
[-]Connect retry 3/3
[-]('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
[-]Connect Failed! Please check your Proxy or Network!
[!] ==================== ERROR ====================
[!]          Mapping Table Download FAILED
[!]                    无法连接github
[!]                     请过几小时再试试
[!] Connect Failed
[-]      ------ AUTO EXIT AFTER 30s !!! ------
