### ISSUE TITLE
一直循环报 [list index out of range]

### ISSUE THREAD

**Issue by Sprite-zlc** [yoshiko2/Movie_Data_Capture#1012]
**Describe the bug 错误描述**
一直循环报  [list index out of range]

**To Reproduce 如何重现BUG**
重现行为的步骤：
貌似刮削 FC2的片子就会这样

**Expected behavior 预期结果 **
如果搜索不到可以直接跳过

**Screenshots BUG发生截图**
![EBMT}_N8Z_M(6HR}F$PW@BM](https://user-images.githubusercontent.com/50043423/236678180-00e1c2fa-7f3a-4310-9f16-0684d9a5e73e.png)

**Running Env 运行环境**
 - OS :win11 22H2
 - Python Version : 不清楚

**Comment by cyclc77** [comment]
同样的问题

**Comment by aisildur** [comment]
> > 目前[FC2-1052770]这个番号我这里必现以下问题，已在Javdb找到data的情况下，还会在之后循环找其他站点，不停止刮削
> > log如下
> 
> 顺路问你个问题 要怎么设置才能在javdb刮削fc2的信息啊 谢谢

你需要Javdb的付费会员....

**Comment by yoshiko2** [comment]
Fixed in 6.6.4
