### ISSUE TITLE
遇到一些识别不了番号

### ISSUE THREAD

**Issue by yinhanghang** [yoshiko2/Movie_Data_Capture#1015]
1.一个番号有多个文件
FCDSS-013-A.mp4，FCDSS-013-B.mp4 ，都识别不到
2.legsjapan开头的番号
legsjapan-1063.mp4  这个是在javdb008.com下载的识别不到，有个十几部
3.uralesbian开头的番号
uralesbian-366.mp4 这个忘记在哪下载的了，有个十几部

**Comment by ZhanggaoYuan16** [comment]
对于1问题， 建议把A与B根据wiki的建议改成cd1，cd2.
对于2，3，有修改好config中javdb的网站地址吗，有配置好cookies吗。怎么配置看这里https://github.com/yoshiko2/db_cookies

**Comment by yinhanghang** [comment]
感谢帮助
第一个问题解决了
第二个问题
获取cookies那个软件打开就闪退了，没有生成配置文件
下载了谷歌浏览器，访问了javdb38.com生成了cookie，还是闪退，我去查看代码，
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "E:\av\db_cookies.py", line 33, in <module>
去找了路径发现没有Cookie
%LOCALAPPDATA%\Google\Chrome\User Data\Default\ 路径下面没有Cookie

**Comment by andyubird** [comment]
有顯示什麼錯誤嗎，如果是卡住不動的話，現在這個版本有個問題，當影片只在JavDB查得到會嘗試在其他站找封面，進入死循環，我已經有修改程式並提出一個Pull Request了

**Comment by ZhanggaoYuan16** [comment]
可以提供一下mdc运行时的log吗 记得打开debug模式

或者你也可以试试手动指定网站  https://github.com/yoshiko2/Movie_Data_Capture/wiki/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6#%E6%97%A0%E7%A0%81%E5%90%8E%E7%BC%80:~:text=xxx.xxx/xxxx%22-,%E6%89%8B%E5%8A%A8%E6%8C%87%E5%AE%9A%E7%95%AA%E5%8F%B7,-%2Dn%E6%88%96%2D%2Dnumber

**Comment by andyubird** [comment]
我有測試這幾個番號：
`legsjapan-1063.mp4
CCDV-79.mpg
heydouga4030-2240.wmv`
這幾個在我修正Javdb迴圈以後都找得到

uralesbian-366.mp4 在javdb38里面查不到，其他網站也沒有，就會失敗，但程式正常運行、結束。
可以等更新版本以後再試試，應該就沒問題了。

**Comment by yinhanghang** [comment]
是卡死的状态，没有错误提示，我试试新的版本
