### ISSUE TITLE
好像不能刮削115挂载盘的文件吗，管理员运行也没效果，tmm管理员运行就可以刮削115挂载的电影电视剧耶

### ISSUE THREAD

**Issue by Adsryen** [yoshiko2/Movie_Data_Capture#1021]
**Describe the bug 错误描述**
Describe clearly and concisely what the error is
不能刮削115挂载盘的文件吗，管理员运行也没效果

**To Reproduce 如何重现BUG**
重现行为的步骤：
1. 115挂载本地硬盘
2. tmm刮削成功
3. 因为需要把Movie_Data_Capture程序放置到和电影的同一目录下
4. 所以上传115后
5. 再本地运行肯定就不太可行
6. See error

**Expected behavior 预期结果 **
期望以后可以跨路径刮削，而不是一定要在同一目录

**Screenshots BUG发生截图**
 
**Logs 日志**
Copy all or key content of the file to this
复制文件的全部或关键内容到此
Logs location:
Windows : 
Linux/MacOS/BSD: 

**Running Env 运行环境**
 - OS : win11
 - Python Version : 3.10

**Comment by yoshiko2** [comment]
https://github.com/yoshiko2/Movie_Data_Capture/wiki/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6#%E5%88%AE%E5%89%8A%E5%85%B6%E4%BB%96%E7%9B%AE%E5%BD%95%E7%9A%84%E5%BD%B1%E7%89%87
