### ISSUE TITLE
中文无码流出的影片番号识别时不正确

### ISSUE THREAD

**Issue by Rebuilding127** [yoshiko2/Movie_Data_Capture#1026]
**Describe the bug 错误描述**
如影片 `FSDSS-070` 是无码流出的，我将其命名为以下几种格式，识别到的影片名都是 `FSDSS-070-` 导致解析错误。
`FSDSS-070-C-流出`
`FSDSS-070-C-无码流出`
`FSDSS-070-无码流出-C`

版本：v6.6.3

**Comment by yinhanghang** [comment]
我后缀改成了 FSDSS-070-C-hack

**Comment by Rebuilding127** [comment]
> 改成FSDSS-070-C-hack试试

试过了，可以识别。
但是与预期结果不一致，hack表示破解，和流出性质毕竟不一样。
我记得之前5.x某个版本还是可以用的，建议修复下这个问题。

**Comment by EuropeanWithSSR** [comment]
最近看到有一部分以 -U 结尾的后缀，也属于无码破解，希望能增加相关识别规则。

**Comment by hejianjun** [comment]
建议使用重命名工具重命名，之前支持是因为代码判断有-的话只读取`字母-数字`的番号后面发现有些番号比较特别,比如`200GANA-2082`所以现在番号会读取全部的非中文

**Comment by zolady** [comment]
目前我找到的解决方法是不要番号和无码流出之间的横杠，然后在无码流出后加上“-C”，即“SSIS-001无码流出-C”

**Comment by Rebuilding127** [comment]
> 建议使用重命名工具重命名，之前支持是因为代码判断有-的话只读取`字母-数字`的番号后面发现有些番号比较特别,比如`` 200GANA-2082``XXX-AV-19968 ``所以现在番号会读取全部的非中文

如果规则有调整，改成不识别中文的话，建议将无码流出也使用字母进行命名规范，就好像之前的`hack`以及最近常出现的`-U`，也使用特定大写字母或者单词简写，这方面我觉得完全可以由工具进行定义，只需在Wiki文档中说明即可。

**Comment by Rebuilding127** [comment]
> 目前我找到的解决方法是不要番号和无码流出之间的横杠，然后在无码流出后加上“-C”，即“SSIS-001无码流出-C”

试了下确实可以，感谢
