### ISSUE TITLE
大量影片的extrafanart图片只有几KB

### ISSUE THREAD

**Issue by jianshunjiang** [yoshiko2/Movie_Data_Capture#1027]
发现无论最新版还是6.6.4版本，都存在一个问题，很多影片的extrafanart 图片只有5KB，非常模糊。

发现只有6.2.2版本下载的extrafanart是没有问题的，但是这个版本会存在一个retry的问题，非常浪费时间。

提供如下号码以供测试ABP340，abp341
![image](https://github.com/yoshiko2/Movie_Data_Capture/assets/31506869/5bcd0368-0c3f-4f89-85d7-9b8f0684edc3)

**Comment by andyubird** [comment]
看起來應該是xcity的問題，把xcity從config移除或者放到列表後面應該可以暫時解決
