### ISSUE TITLE
6.6.4版本大量影片佚名

### ISSUE THREAD

**Issue by jianshunjiang** [yoshiko2/Movie_Data_Capture#1028]
6.6.4版本大量影片佚名

提供一些示例影片
ssni-484  mide-636

**Comment by ramondsq** [comment]
debug打开看看从哪个网站爬的

**Comment by jianshunjiang** [comment]
> debug打开看看从哪个网站爬的

找到了，是jav321

`[!] [ABP417] As Number Processing for '\\Ds920\片\老片\ABP417AVI情趣\ABP417.avi'
[+]select madou
[+]select xcity
list index out of range
[+]select javbus
[+]select airav
list indices must be integers or slices, not str
[+]select jav321
[+]Find movie [ABP417] metadata on website 'jav321'
[+] ------- DEBUG INFO -------
[+]  - actor               : 佚名`

**Comment by ramondsq** [comment]
可以把javbus排前面，我试了一下不会匿名

> > debug打开看看从哪个网站爬的
> 
> 找到了，是jav321
> 
> `[!] [ABP417] As Number Processing for '\\Ds920\片\老片\ABP417AVI情趣\ABP417.avi' [+]select madou [+]select xcity list index out of range [+]select javbus [+]select airav list indices must be integers or slices, not str [+]select jav321 [+]Find movie [ABP417] metadata on website 'jav321' [+] ------- DEBUG INFO ------- [+] - actor : 佚名`
