### ISSUE TITLE
刮削结果以名字做目录出现各种结果

### ISSUE THREAD

**Issue by yaoshengyi** [yoshiko2/Movie_Data_Capture#1035]
刮削一批文件，同一个演员，刮削出来3种目录，该怎么办？

/JAV_output/番号/
/JAV_output/日文演员名/番号/
/JAV_output/中文演员名/番号/

**Running Env 运行环境**
 - OS :MACOS 
 - Python Version : 3.10.11

**Comment by yaoshengyi** [comment]
![image](https://github.com/yoshiko2/Movie_Data_Capture/assets/35094285/40dfb8c5-70a6-4b7b-98fc-effddded8191)

**Comment by Rebuilding127** [comment]
根据我目前的观察来看，应该是刮削结果来自不同网站导致的，不同网站的刮削结果出入很大，建议作者能在刮削结果的基础上统一处理下

**Comment by yaoshengyi** [comment]
下次我试试只写一个或者两个网站的看看。。。

**Comment by Rebuilding127** [comment]
我试过了，比如正常就是默认的配置运行一次，对不满意的结果就使用只保留`javdb`的配置再试一下，一般就可以了

**Comment by NinetyFour95** [comment]
这种情况现在我都是跑两次来解决

**Comment by CleverMod** [comment]
> 这种情况现在我都是跑两次来解决

请问第二遍应该怎么配置

**Comment by CleverMod** [comment]
> 我试过了，比如正常就是默认的配置运行一次，对不满意的结果就使用只保留`javdb`的配置再试一下，一般就可以了

请问只保留javdb是怎么配置

**Comment by Rebuilding127** [comment]
> > 我试过了，比如正常就是默认的配置运行一次，对不满意的结果就使用只保留`javdb`的配置再试一下，一般就可以了
> 
> 请问只保留javdb是怎么配置

配置文件中有一项`website`，后面是一连串的web网站的简称或者别名，都是作为刮削资源网站用的。可以尝试把`javbus`放到最前面，或者全删了只保留`javbus`，修改的时候记得不同网站名用逗号分开

**Comment by NinetyFour95** [comment]
> 

![image](https://github.com/yoshiko2/Movie_Data_Capture/assets/65636228/3126d398-8320-4c30-9467-c86f39825e1c)

**Comment by CleverMod** [comment]
> > > 我试过了，比如正常就是默认的配置运行一次，对不满意的结果就使用只保留`javdb`的配置再试一下，一般就可以了
> > 
> > 
> > 请问只保留javdb是怎么配置
> 
> 配置文件中有一项`website`，后面是一连串的web网站的简称或者别名，都是作为刮削资源网站用的。可以尝试把`javbus`放到最前面，或者全删了只保留`javbus`，修改的时候记得不同网站名用逗号分开

谢谢

**Comment by CleverMod** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/65636228/250011245-3126d398-8320-4c30-9467-c86f39825e1c.png)

谢谢
