### ISSUE TITLE
macOS运行时报错SyntaxError: Non-UTF-8 code starting with '\xcf' in file

### ISSUE THREAD

**Issue by weixuanls** [yoshiko2/Movie_Data_Capture#1036]
**Running Env 运行环境**
 - OS :macOS
 - Python Version : 3.9

**Comment by yaoshengyi** [comment]
看上去是文件名或者目录里有特殊符号？

**Comment by weixuanls** [comment]
路径：/Volumes/weixuan_HDD1/H/Movie_Data_Capture，第一行声明编码好像也不行

**Comment by yoshiko2** [comment]
请在当前目录下运行

**Comment by 1013461195** [comment]
使用chmod +x 文件，将文件变成可执行文件，再右键文件选择打开即可，第一次打卡需要通过右键打开
