### ISSUE TITLE
6.6.6 版本无法使用javdb刮削

### ISSUE THREAD

**Issue by Rebuilding127** [yoshiko2/Movie_Data_Capture#1051]
刮削源仅保留 `javdb` 的情况下，刮削结果全都是 `Movie Number not Found!` ，调试模型输出 `list index out of range` 。
其它源如 `javbus` 则可以正常使用。
可以确保代理软件正常使用，javdb的网站也能正常访问的。

**Comment by gogofishman** [comment]
相同情况

**Comment by Rebuilding127** [comment]
最近观察也有一部分是输出是 `page not fond in javdb`
