### ISSUE TITLE
[BUG]配置文件中指定使用javdb不生效

### ISSUE THREAD

**Issue by zhang3woshi** [yoshiko2/Movie_Data_Capture#1060]
配置文件中指定仅使用javdb进行抓取，但是遇到FC2PPV资源没有使用javdb，自动选择了fc2，avsox，msin进行搜索导致无法搜索到结果，但是对于其它的资源又可以使用javdb，如图：

![image](https://github.com/yoshiko2/Movie_Data_Capture/assets/103362702/2b04ac4d-aac3-49bf-bc95-772fbaf5cef6)
![image](https://github.com/yoshiko2/Movie_Data_Capture/assets/103362702/db30fb99-4af2-42c8-b4de-3caa0845d60a)
![image](https://github.com/yoshiko2/Movie_Data_Capture/assets/103362702/ff30716b-ae90-430e-ab56-2894bf2c121e)

**Comment by NinetyFour95** [comment]
建议配置文件拉到最下面，有一个“javdb”配置选项。

**Comment by zhang3woshi** [comment]
> 建议配置文件拉到最下面，有一个“javdb”配置选项。改成最新的JAVDB网址后面的数字。再试一试。 ![image](https://user-images.githubusercontent.com/65636228/261815443-c1de2e2e-6412-4528-986e-d648e2dd700c.png) 如图。
配置文件已经改为521，其他视频资源可以正常使用javdb，只有fc2资源无法使用javdb
