### ISSUE TITLE
[建议]建议增加对“-UC”以及“-U”的识别

### ISSUE THREAD

**Issue by MengFanwei0317** [yoshiko2/Movie_Data_Capture#1078]
_For the new functions you need, you can contact me through the contact information below for a paid solution. I will respond as soon as possible and deliver it in the next version.

对于需要的新功能，可通过下方联系方式联系我有偿解决（支持众筹），我会尽快响应，会在下一个版本交付

# 联系方式 Contact：
* Email    : yoshiko2.dev@gmail.com
* Telegram : https://t.me/yoshiko2_

建议增加对“-UC”和“-U”后缀的识别，目前在jav的一系列论坛里，“-UC”代指ai破解的带字幕的资源，“-U”代指ai破解的资源，这种情况已经变得普遍化。希望能在下一个版本中内置对以上两种后缀的支持，这样就不用对着failed_list进行查找以及重命名。

**Comment by todoXu** [comment]
https://github.com/todoXu/Movie_Data_Capture
fork了一个，随手改了下，刚好我也想支持 -U -UC

**Comment by zhengweiqing** [comment]
我现在的解决办法是，自己写了个sh脚本，在刮削之前先将-U修改为 -hack

**Comment by aomengmeng** [comment]
> https://github.com/todoXu/Movie_Data_Capture fork了一个，随手改了下，正好我也想支持-U -UC

怎么用啊

**Comment by todoXu** [comment]
> > https://github.com/todoXu/Movie_Data_Capture fork了一个，随手改了下，正好我也想支持-U -UC
> 
> 怎么用啊

clone下来，然后跑一下py_to_exe.ps1，mdc的exe就会打包出来了

**Comment by biaji** [comment]
> https://github.com/todoXu/Movie_Data_Capture fork了一个，随手改了下，刚好我也想支持 -U -UC

不提个pr么。期待早点合入

**Comment by todoXu** [comment]
> > https://github.com/todoXu/Movie_Data_Capture fork了一个，随手改了下，刚好我也想支持 -U -UC
> 
> 不提个pr么。期待早点合入

https://github.com/yoshiko2/Movie_Data_Capture/pull/1076
