### ISSUE TITLE
javbus 不可用，出现 list index out of range 错误

### ISSUE THREAD

**Issue by tyur18** [yoshiko2/Movie_Data_Capture#1090]
javbus不可用，出现 list index out of range 错误

**Comment by igotcha** [comment]
看起来是因为javbus必须要登录才能查看内容了

**Comment by tyur18** [comment]
> 看起来是因为javbus必须要登录才能查看内容了

用浏览器看网页不用登录啊

**Comment by surfinghome** [comment]
javbus 昨天開始需要登陸才讓開網頁了.

**Comment by tyur18** [comment]
> javbus 昨天開始需要登陸才讓開網頁了.

刚才又用浏览器看了下，不用登录直接就可以打开

**Comment by surfinghome** [comment]
很可能是地區限制, 我這裡座標台灣, ctrl F5之後仍然強制要登入才讓開, 我沒買vpn , 來個有vpn 的兄弟試下就知道

**Comment by insomniacdoll** [comment]
代理是需要登录才能浏览了。这里应该需要类似javdb的处理。

**Comment by zzzshanghai** [comment]
我这里遇到和楼主同样的问题。

**Comment by t1000lalala** [comment]
一般瀏覽器可以不用登入是正常顯示
差別在header 加入 'Accept-Language': 'zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,ja;q=0.6,zh-CN;q=0.5'
requests就會返回正確的內容

**Comment by q767939287** [comment]
> 一般瀏覽器可以不用登入是正常顯示 差別在header 加入 'Accept-Language': 'zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,ja;q=0.6,zh-CN;q=0.5' requests就會返回正確的內容
> 
> 在.\scrapinglib\javbus.py 加上
> 
> ```
>     def extraInit(self):
>         self.extraheader = { 'Accept-Language': 'zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,ja;q=0.6,zh-CN;q=0.5'}
> ```
> 
> 應該就會出來了

按照语法文件应该这样吧？

    def extraInit(self, htmltree):
       **return** self.extraheader = { 'Accept-Language': 'zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,ja;q=0.6,zh-CN;q=0.5'}    

如果按照lao你的写法加上去在识别后会报错：
[+] ------- DEBUG INFO -------
[+]Image Downloaded! ***-***-thumb.jpg
[+]Image Cutted!     ***-***-poster.jpg
[-]Write Failed!
[-] No section: 'direct'
[-]Add to Failed List file, see '/mnt/Jellyfin/failed_av/failed_list.txt'

**Comment by t1000lalala** [comment]
> > 一般瀏覽器可以不用登入是正常顯示 差別在header 加入 'Accept-Language': 'zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,ja;q=0.6,zh-CN;q=0.5' requests就會返回正確的內容
> > 在.\scrapinglib\javbus.py 加上
> > ```
> >     def extraInit(self):
> >         self.extraheader = { 'Accept-Language': 'zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,ja;q=0.6,zh-CN;q=0.5'}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 應該就會出來了
> 
> 按照语法文件应该这样吧？
> 
> ```
> def extraInit(self, htmltree):
>    return self.extraheader = { 'Accept-Language': 'zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,ja;q=0.6,zh-CN;q=0.5'}    
> ```
> 
> 如果按照lao你的写法加上去在识别后会报错： [+] ------- DEBUG INFO ------- [+]Image Downloaded! _**-**_-thumb.jpg [+]Image Cutted! _**-**_-poster.jpg [-]Write Failed! [-] No section: 'direct' [-]Add to Failed List file, see '/mnt/Jellyfin/failed_av/failed_list.txt'

他是繼承parser.py的
所以def extraInit(self):
應該是沒傳入htmltree，也無回傳值

可以參照其他的類別 例如: ./scrapinglib/getchu.py
```
    def extraInit(self):
        self.imagecut = 0
        self.allow_number_change = True

        self.cookies = {'getchu_adalt_flag': 'getchu.com', "adult_check_flag": "1"}
        self.GETCHU_WWW_SEARCH_URL = 'http://www.getchu.com/php/search.phtml?genre=anime_dvd&search_keyword=_WORD_&check_key_dtl=1&submit='
```
加入 self.extraheader = { 'Accept-Language': 'zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,ja;q=0.6,zh-CN;q=0.5'}
並移除函數裡其他的

**Comment by q767939287** [comment]
> > > 一般瀏覽器可以不用登入是正常顯示 差別在header 加入 'Accept-Language': 'zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,ja;q=0.6,zh-CN;q=0.5' requests就會返回正確的內容
> > > 在.\scrapinglib\javbus.py 加上
> > > ```
> > >     def extraInit(self):
> > >         self.extraheader = { 'Accept-Language': 'zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,ja;q=0.6,zh-CN;q=0.5'}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 應該就會出來了
> > 
> > 
> > 按照语法文件应该这样吧？
> > ```
> > def extraInit(self, htmltree):
> >    return self.extraheader = { 'Accept-Language': 'zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,ja;q=0.6,zh-CN;q=0.5'}    
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 如果按照lao你的写法加上去在识别后会报错： [+] ------- DEBUG INFO ------- [+]Image Downloaded! _**-**_-thumb.jpg [+]Image Cutted! _**-**_-poster.jpg [-]Write Failed! [-] No section: 'direct' [-]Add to Failed List file, see '/mnt/Jellyfin/failed_av/failed_list.txt'
> 
> 他是繼承parser.py的 所以def extraInit(self): 應該是沒傳入htmltree，也無回傳值
> 
> 可以參照其他的類別 例如: ./scrapinglib/getchu.py
> 
> ```
>     def extraInit(self):
>         self.imagecut = 0
>         self.allow_number_change = True
> 
>         self.cookies = {'getchu_adalt_flag': 'getchu.com', "adult_check_flag": "1"}
>         self.GETCHU_WWW_SEARCH_URL = 'http://www.getchu.com/php/search.phtml?genre=anime_dvd&search_keyword=_WORD_&check_key_dtl=1&submit='
> ```
> 
> 加入 self.extraheader = { 'Accept-Language': 'zh-TW,zh;q=0.9,en-US;q=0.8,en;q=0.7,ja;q=0.6,zh-CN;q=0.5'} 並移除函數裡其他的

按照佬提供思路，再次编译已经没问题了，谢谢！
