### ISSUE TITLE
MDC 6.6.7 貎似削刮不出女優名字

### ISSUE THREAD

**Issue by clad1984** [yoshiko2/Movie_Data_Capture#1100]
先上圖
![螢幕擷取畫面 2023-10-11 124521a](https://github.com/yoshiko2/Movie_Data_Capture/assets/147581000/aec9ef38-a621-4c91-935f-fbdfd75777ef)

環境：Windows 11, 香港 ip , config.ini 更動為 translate to sc =1/ cc convert mode = 2 / jellyfin multi part fanart =1 , 其餘沒動
其實沒動也一樣

小弟不材，log file 看似正常，但女優名應該削刮不出所以變成伕名
而事實上，如 midv-118，於 javbus 網頁版中，是有資料的

求解，感謝

English simple version here :
Actress name can't be scrapped even by default options and settings.
This screen cap shows a released title midv-118 which is already filed in Javbus, however the scrapping result is "unknown" actress name.

Thanks for your help.

EDIT 1 , neos-003 本身沒有女優名，請無視

**Comment by grock304** [comment]
俺也一样，全是佚名。

**Comment by beacon007** [comment]
javbus国庆期间做了某些反爬虫策略，现在应该是访问不了javbus了，我开了debug信息 发现现在都是从jav321中取的，都是佚名

**Comment by clad1984** [comment]
> javbus国庆期间做了某些反爬虫策略，现在应该是访问不了javbus了，我开了debug信息 发现现在都是从jav321中取的，都是佚名

你對，我忘了有 debug mode，原來佚名是 jav321來的
我以為我chrome能連 javbus 就等如 MDC 也行
所以我只能等更新(解封)了？

**Comment by beacon007** [comment]
> > javbus国庆期间做了某些反爬虫策略，现在应该是访问不了javbus了，我开了debug信息 发现现在都是从jav321中取的，都是佚名
> 
> 你對，我忘了有 debug mode，原來佚名是 jav321來的 我以為我chrome能連 javbus 就等如 MDC 也行 所以我只能等更新(解封)了？

https://github.com/yoshiko2/Movie_Data_Capture/issues/1090 这个issue里有提到应该怎么修改，javbus的反爬虫机制不是很复杂，目前应该还不涉及cloudflare 有时间可以试试，同样jav321没拿到演员也可以在对应地方修改

**Comment by yushiro** [comment]
> > > javbus国庆期间做了某些反爬虫策略，现在应该是访问不了javbus了，我开了debug信息 发现现在都是从jav321中取的，都是佚名
> 
> > 
> 
> > 你對，我忘了有 debug mode，原來佚名是 jav321來的 我以為我chrome能連 javbus 就等如 MDC 也行 所以我只能等更新(解封)了？
> 
> 
> 
> https://github.com/yoshiko2/Movie_Data_Capture/issues/1090 这个issue里有提到应该怎么修改，javbus的反爬虫机制不是很复杂，目前应该还不涉及cloudflare 有时间可以试试，同样jav321没拿到演员也可以在对应地方修改

1090这个修改并没有用，我调试下来，javbus是做了ip限制，用日本或者台湾的ip就可以正常访问。

**Comment by beacon007** [comment]
> > > > javbus国庆期间做了某些反爬虫策略，现在应该是访问不了javbus了，我开了debug信息 发现现在都是从jav321中取的，都是佚名
> > 
> > 
> > > 
> > 
> > 
> > > 你對，我忘了有 debug mode，原來佚名是 jav321來的 我以為我chrome能連 javbus 就等如 MDC 也行 所以我只能等更新(解封)了？
> > 
> > 
> > https://github.com/yoshiko2/Movie_Data_Capture/issues/1090 这个issue里有提到应该怎么修改，javbus的反爬虫机制不是很复杂，目前应该还不涉及cloudflare 有时间可以试试，同样jav321没拿到演员也可以在对应地方修改
> 
> 1090这个修改并没有用，我调试下来，javbus是做了ip限制，用日本或者台湾的ip就可以正常访问。

好吧抱歉我没有仔细研究，不过换个思路解决 因为jav321抓不到演员，当我把这部分配置改成如下后，发现可以抓到了
```
[priority]                                  
website =javdb,gcolle,javday,javmenu,pcolle,caribpr,msin
```
即去掉了一部分网站

**Comment by clad1984** [comment]
> > > > > javbus国庆期间做了某些反爬虫策略，现在应该是访问不了javbus了，我开了debug信息 发现现在都是从jav321中取的，都是佚名
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 你對，我忘了有 debug mode，原來佚名是 jav321來的 我以為我chrome能連 javbus 就等如 MDC 也行 所以我只能等更新(解封)了？
> > > 
> > > 
> > > https://github.com/yoshiko2/Movie_Data_Capture/issues/1090 这个issue里有提到应该怎么修改，javbus的反爬虫机制不是很复杂，目前应该还不涉及cloudflare 有时间可以试试，同样jav321没拿到演员也可以在对应地方修改
> > 
> > 
> > 1090这个修改并没有用，我调试下来，javbus是做了ip限制，用日本或者台湾的ip就可以正常访问。
> 
> 好吧抱歉我没有仔细研究，不过换个思路解决 因为jav321抓不到演员，当我把这部分配置改成如下后，发现可以抓到了
> 
> ```
> [priority]                                  
> website =javdb,gcolle,javday,javmenu,pcolle,caribpr,msin
> ```
> 
> 即去掉了一部分网站

謝謝指點
事實我也沒有細看每個repo/issue，但我不明白為何原生 config.ini 的 javdb 的排名在最後？

**Comment by tony1016** [comment]
> > > > > javbus国庆期间做了某些反爬虫策略，现在应该是访问不了javbus了，我开了debug信息 发现现在都是从jav321中取的，都是佚名
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > 你對，我忘了有 debug mode，原來佚名是 jav321來的 我以為我chrome能連 javbus 就等如 MDC 也行 所以我只能等更新(解封)了？
> > > 
> > > 
> > > https://github.com/yoshiko2/Movie_Data_Capture/issues/1090 这个issue里有提到应该怎么修改，javbus的反爬虫机制不是很复杂，目前应该还不涉及cloudflare 有时间可以试试，同样jav321没拿到演员也可以在对应地方修改
> > 
> > 
> > 1090这个修改并没有用，我调试下来，javbus是做了ip限制，用日本或者台湾的ip就可以正常访问。
> 
> 好吧抱歉我没有仔细研究，不过换个思路解决 因为jav321抓不到演员，当我把这部分配置改成如下后，发现可以抓到了
> 
> ```
> [priority]                                  
> website =javdb,gcolle,javday,javmenu,pcolle,caribpr,msin
> ```
> 
> 即去掉了一部分网站

可行
