### ISSUE TITLE
欧美影片突然刮削不了了

### ISSUE THREAD

**Issue by lc190tt** [yoshiko2/Movie_Data_Capture#452]
用的4.4.2，这几天突然识别不了欧美的
刮削时显示
list index out of range 
Movie Data not found!
比如这些番号
blacked.18.03.06
blacked.18.06.24
blacked.18.09.02
blacked.19.10.22
blacked.20.01.10

**Comment by EnnawYang** [comment]
似乎有好几个站刮削不了了

**Comment by kglife** [comment]
最好用的javdb不能用了，jav321刮削的都是小写，还要自己整理，比较麻烦，希望作者大大能修复javdb的刮削

**Comment by lc190tt** [comment]
今天又看了一下，确实是javdb刮削引起的，javdb的欧美番号比较全
