### ISSUE TITLE
发出了奇怪的错误

### ISSUE THREAD

**Issue by sherlockHlb** [yoshiko2/Movie_Data_Capture#453]
urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

[proxy]
;proxytype: http or socks5 or socks5h switch: 0 1
switch=1
type=http
proxy=127.0.0.1:1090
timeout=5
retry=3
cacert_file=

为啥是HTTPS的请求

**Comment by sherlockHlb** [comment]
偶尔又有成功的。就很离谱

**Comment by fbigun** [comment]
是的，都无法调整
