### ISSUE TITLE
一开代理就报错是怎么回事

### ISSUE THREAD

**Issue by foxylol** [yoshiko2/Movie_Data_Capture#454]
不管是全局还是规则 配置文件怎么调都这样
![QQ截图20210410153341](https://user-images.githubusercontent.com/9382303/114262669-d0055a80-9a13-11eb-9ab5-65a971fd65ea.jpg)

**Comment by fbigun** [comment]
我也遇到这种鬼，全都报这中错误

**Comment by ianho7** [comment]
我也是，请问有解决方法吗？
