### ISSUE TITLE
javdb无法刮削

### ISSUE THREAD

**Issue by wsj920602** [yoshiko2/Movie_Data_Capture#456]
javdb无法刮削了，所有片子都提示not in the list

**Comment by ifunboy** [comment]
javdb.com已经启用cloudflare五秒盾，建议添加cookie选项。
临时解决，建议将JAVDB.PY 源码内 javdb4.com改为javdb8.com。javdb8.com暂时没有 防爬虫。

**Comment by kglife** [comment]
> javdb.com已经启用cloudflare五秒盾，建议添加cookie选项。
> 临时解决，建议将JAVDB.PY 源码内 javdb4.com改为javdb8.com。javdb8.com暂时没有 防爬虫。

测试将 javdb4.com改为javdb8.com，仍提示not in list，可能是其他原因？

**Comment by rxia24** [comment]
以KATU-080为例子，演员名字无法刮削
