### ISSUE TITLE
文件名混淆 同一个番号  - _

### ISSUE THREAD

**Issue by lbbboy** [yoshiko2/Movie_Data_Capture#461]
无法区分分隔符 - _

**Comment by lbbboy** [comment]
> 无法区分分隔符 - _

刚刚测试了下还是不能正确区分！

050121_001
050121-001

**Comment by lbbboy** [comment]
type nul > 042921-001.mp4

042921-001.mp4
050121-001.mp4
050221-001.mp4
050421-001.mp4

AV_Data_Capture-CLI-4.6.2-Windows-amd64
用最新版测试过，这几个都识别成  _001

**Comment by lededev** [comment]
你要改config.ini，加上carib这个搜刮引擎，功能才能生效。PR里我写了改哪里。

**Comment by lededev** [comment]
此外文件的命名要求有变动，不要删得只剩数字，保持原样就好。
carib-123456-123.mp4
1pon-123456_123.mp4
23434-3xplanent-123456-123-carib-1080p.mp4
这样的都可以，不需要改名成123456-123.mp4

**Comment by lbbboy** [comment]
> 你要改config.ini，加上carib这个搜刮引擎，功能才能生效。PR里我写了改哪里。

好谢谢，我在看看。

**Comment by lbbboy** [comment]
> 此外文件的命名要求有变动，不用删得只剩数字，保持原样就好。
> carib-123456-123.mp4
> 1pon-123456_123.mp4
> 23434-3xplanent-123456-123-carib-1080p.mp4
> 这样的都可以，不需要改名成123456-123.mp4
> 当然，你删得只剩数字了也没关系，只要加勒比用-做数字分隔，一本道用下划线做数字分隔，并且启用了carib削刮引擎，也能正确识别。

[!]Making Data for [Z:\carib-042921-001.mp4], the number is [carib-042921]
'CARIB-042921' is not in list
[-]Connect retry 1/3
list index out of range

搜不到啊，是我代理的问题？

**Comment by lededev** [comment]
我这里能找到你这个番号啊。
```
Z:\J>AV_Data_Capture.exe
[*]================== AV Data Capture ===================
[*]                        4.6.2
[*]======================================================
[+]Enable debug
[!]Enable soft link
[+]Find 1 movies
[!] - 100.% [1/1] -
[!]Making Data for [Z:\J\carib-042921-001.mp4], the number is [042921-001]
[+]select carib
[+] ---Debug info---
[+]  - actor       : 塩見エリカ
[+]  - cover       : https://www.caribbeancom.com/moviepages/042921-001/images/l_l.jpg
[+]  - director    :
[+]  - extrafanart :
[+]  - imagecut    : 0
[+]  - label       :
[+]  - number      : 042921-001
[+]  - outline     : 0 characters
[+]  - release     : 2021-04-29
[+]  - runtime     : 01:01:02
[+]  - series      :
[+]  - source      : carib.py
[+]  - studio      : 加勒比
[+]  - tag         : ['中出', '菠萝', '69', '破处', '美脚', '美尻']
[+]  - title       : Debut Vol.67 〜清楚な顔してイキまくり中出し３回戦！〜
[+]  - website     : https://www.caribbeancom.com/moviepages/042921-001/index.html
[+]  - cover_small :
[+]  - location_rule : #塩見エリカ/[2021] Debut Vol.67 〜清楚な顔してイキまくり中出し３回戦！〜 [042921-001]
[+]  - actor_list  : ['塩見エリカ']
[+]  - trailer     :
[+]  - naming_rule : Debut Vol.67 〜清楚な顔してイキまくり中出し３回戦！〜
[+] ---Debug info---
[+]Image Downloaded! \#JAV_output/#塩見エリカ/[2021] Debut Vol.67 〜清楚な顔してイキまくり中出し３回戦！〜 [042921-001]/042921-001-fanart.jpg
[+]Image Copyed!     \#JAV_output/#塩見エリカ/[2021] Debut Vol.67 〜清楚な顔してイキまくり中出し３回戦！〜 [042921-001]/042921-001-poster.jpg
[+]Wrote!            \#JAV_output/#塩見エリカ/[2021] Debut Vol.67 〜清楚な顔してイキまくり中出し３回戦！〜 [042921-001]/042921-001.nfo
[+]Thumb Add Mark:   无码
[+]Poster Add Mark:  无码
[*]======================================================
[+]Used 7.28s
[+]All finished!!!
Press enter key exit, you can check the error message before you exit...

Z:\J>
```

**Comment by lededev** [comment]
有可能是代理问题，因为我没用代理，日语网站的转码半天没搞好，用socket直接连接抓的字节数据然后转的码。
由于我是路由器自动翻墙，国外IP通过路由器默认走代理了，没感觉出区别来。
你试试在C:\windows\system32\drivers\etc\hosts文件里面加一行域名
www.caribbeancom.com        140.174.0.171
看看能不能联上吧。

> 搜不到啊，是我代理的问题？

**Comment by lbbboy** [comment]
`[*]================== AV Data Capture ===================
[*]                        4.6.2
[*]======================================================
[+]Enable debug
[+]Find 5 movies
[!] - 20.0% [1/5] -
[!]Making Data for [Z:\1\carib-042921-001.mp4], the number is [carib-042921]
[+]select javbus
[+]select javdb
'CARIB-042921' is not in list
[+]select airav
[+]select fanza
[+]select xcity
[+]select mgstage
[+]select fc2
list index out of range
[+]select avsox
[+]select jav321
[+]select dlsite
[+]select carib
[-]Movie Data not found!`

我也是路由翻的

**Comment by lbbboy** [comment]
```
[*]================== AV Data Capture ===================
[*]                        4.6.2
[*]======================================================
[+]Enable debug
[+]Find 5 movies
[!] - 20.0% [1/5] -
[!]Making Data for [Z:\1\carib-042921-001.mp4], the number is [carib-042921]
[+]select javbus
[+]select javdb
'CARIB-042921' is not in list
[+]select airav
[+]select fanza
[+]select xcity
[+]select mgstage
[+]select fc2
list index out of range
[+]select avsox
[+]select jav321
[+]select dlsite
[+]select carib
[-]Movie Data not found!
[*]======================================================
```
我也是路由直接翻的，caribbeancom直接访问没问题。

**Comment by lededev** [comment]
问题在这里
```
[!]Making Data for [Z:\1\carib-042921-001.mp4], the number is [carib-042921]
[+]select javbus
```
首先得到的number不正确，可能你用的是旧版本。其次如果得到正确number之后，紧跟select carib，才进我的代码。
所以我建议你checkout一份031ada6来编译运行试试，你目前运行的这份程序，看起来还是旧版本。

**Comment by lbbboy** [comment]
> 问题在这里
> 
> ```
> [!]Making Data for [Z:\1\carib-042921-001.mp4], the number is [carib-042921]
> [+]select javbus
> ```
> 
> 首先得到的number不正确，可能你用的是旧版本。其次如果得到正确number之后，紧跟select carib，才进我的代码。
> 所以我建议你checkout一份031ada6来编译运行试试，你目前运行的这份程序，看起来还是旧版本。

直接下载的4.6.2 Releases 没合并你的代码？自己编译不会啊。。

**Comment by lededev** [comment]
我的代码是4.6.2之后的，你得等4.6.3

> 直接下载的4.6.2 Releases 没合并你的代码？自己编译不会啊。。

**Comment by lededev** [comment]
@lbbboy  你可以来我这里下载一份编译好的windows 64位执行程序。免责声明：开源免费软件，风险自担，如果程序造成文件破坏概不负责。
https://github.com/lededev/AV_Data_Capture/releases/tag/pre-4.6.3
