### ISSUE TITLE
FC2_1 FC2_2 多个视频同一个番号会直接覆盖

### ISSUE THREAD

**Issue by Mosney** [yoshiko2/Movie_Data_Capture#462]
e.g.
FC2-PPV-1694498_1.mp4
FC2-PPV-1694498_2.mp4

```

[!] - 86.9% [20/23] -
[!]Making Data for [/XXX/FC2PPV/FC2-PPV-1694498_2.mp4], the number is [FC2-1694498]
[+]Image Downloaded! JAV_output/FC2-1694498/FC2-1694498-fanart.jpg
[+]Image Copyed!     JAV_output/FC2-1694498/FC2-1694498-poster.jpg
[+]Wrote!            JAV_output/FC2-1694498/FC2-1694498.nfo
[*]======================================================
[!] - 95.6% [22/23] -
[!]Making Data for [/XXX/FC2PPV/FC2-PPV-1694498_1.mp4], the number is [FC2-1694498]
[+]Image Downloaded! JAV_output/FC2-1694498/FC2-1694498-fanart.jpg
[+]Image Copyed!     JAV_output/FC2-1694498/FC2-1694498-poster.jpg
[+]Wrote!            JAV_output/FC2-1694498/FC2-1694498.nfo
[*]======================================================
[!] - 100.% [23/23] -

```

**Comment by SharpX2016** [comment]
多集影片处理
建议使用视频合并合并为一个视频文件 可以把多集电影按照集数后缀命名为类似ssni-xxx-cd1.mp4m,ssni-xxx-cd2.mp4，abp-xxx-CD1.mp4的规则，只要含有-CDn./-cdn.类似命名规则，即可使用分集功能

FC2-PPV-1694498-CD1.mp4
FC2-PPV-1694498-CD2.mp4

**Comment by Mosney** [comment]
> 
> 
> 多集影片处理
> 建议使用视频合并合并为一个视频文件 可以把多集电影按照集数后缀命名为类似ssni-xxx-cd1.mp4m,ssni-xxx-cd2.mp4，abp-xxx-CD1.mp4的规则，只要含有-CDn./-cdn.类似命名规则，即可使用分集功能
> 
> FC2-PPV-1694498-CD1.mp4
> FC2-PPV-1694498-CD2.mp4

这个我倒是知道，只是之前碰到这种情况都是会成功移动其中一个分集，然后其它的分集都做失败处理，而不是直接覆盖掉文件，我记得很清楚之前的版本重命名后发现已经存在同名文件就会放弃移动

**Comment by lededev** [comment]
我刚用这个软件时，在测试目录，拖动文件到执行程序强制削刮，曾经出现过一次目标目录所有文件被全部覆盖的情况，当时吓了我一跳。
后来我都是用软连接1方式了，削刮完查一遍没有错误的识别番号后，用自己写的脚本将目标目录全部软链接转成硬链接，然后再将目标目录的内容移动到最终目录(是的，硬链接可以随意移动目录，指向目标不会丢失，但跨盘会变复制)。回到源目录（下载目录）再查一遍这些硬链接指向没啥问题后，再用我写的脚本把源目录的硬链接批量删除。
要是还有对硬链接感兴趣的玩家，在这里我推荐一个极其小众的软件，windows文件管理器扩展插件，能给硬链接的文件图标加上红色角标，也能右键创建硬链接或者软链接。开源免费，用chocolatey也能装。
https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html
