### ISSUE TITLE
你好，能不能新增一个刮削完后，删除原目录的功能

### ISSUE THREAD

**Issue by jiliang6666** [yoshiko2/Movie_Data_Capture#488]
比如某部影片放在了一个叫new的文件下，这部影片成功刮削后，把new也一起给删除

**Comment by lededev** [comment]
用Everything，指定下载目录树，搜索菜单选择类型：视频，如果搜索结果中没有任何视频，就可以放心清空整个目录树。
否则选中搜到的视频，按CTRL+ENTER打开视频目录逐一进行处理。
