### ISSUE TITLE
FC2易誤刮問題

### ISSUE THREAD

**Issue by sonhsien** [yoshiko2/Movie_Data_Capture#498]
首先感謝作者的努力. 持續更新維護真的辛苦.
仍有一個問題想請作者幫忙.
我的想法是, 誤刮不如不刮.

在使用了javdb9.json的情況下. 測試FC2刮削
發現誤刮機率頗高.
例如
以下的FC2原始檔案(左欄), 被誤括成右欄
FC2PPV-938140.mp4 --->  FC2-983140.mp4
fc2-470194.mp4     FC2-420194.mp4
fc2_658989.mp4    FC2-658909.mp4
fc2-920833.mp4    FC2-720833.mp4 
FC2PPV-973503.mp4       FC2-773503.mp4
FC2-996318.mp4    FC2-996311.mp4
FC2PPV-1071194.mp4  FC2-1031194.mp4
FC2PPV-1071418.mp4  FC2-1051418.mp4
FC2PPV-1121040.mp4  FC2-1112040.mp4
FC2PPV-1197857.mp4      FC2-1117857.mp4
FC2-1197916.mp4    FC2-1127916.mp4
FC2-1168534.mp4    FC2-1128534.mp4
FC2-1218982.mp4    FC2-1128982.mp4
FC2-1174942.mp4    FC2-1147942.mp4
FC2PPV-1512313.mp4  FC2-1152313.mp4
FC2PPV-1513745.mp4  FC2-1153745.mp4
FC2PPV-1204745.mp4  FC2-1201745.mp4
FC2PPV-1218169.mp4  FC2-1208169.mp4
FC2PPV-1218103.mp4  FC2-1210103.mp4
FC2PPV-1311004.mp4  FC2-1211004.mp4
FC2PPV-1511532.mp4  FC2-1211532.mp4
FC2PPV-1511542.mp4  FC2-1211542.mp4
FC2PPV-1218981.mp4  FC2-1211981.mp4
FC2PPV-1218979.mp4  FC2-1212979.mp4
FC2PPV-1218980.mp4  FC2-1212980.mp4
FC2PPV-1218983.mp4  FC2-1212983.mp4
FC2PPV-1234771.mp4  FC2-1214771.mp4
FC2PPV-1234772.mp4  FC2-1214772.mp4
FC2PPV-1234773.mp4  FC2-1214773.mp4
FC2PPV-1632767.mp4  FC2-1612767.mp4
FC2-785172.mp4    FC2-1785172.mp4

秉持著誤刮不如不刮的原則, 希望作者可以讓數字不是 exactly match的, 就當作找不到了 (Movie data not found).

再次感謝您的付出!

**Comment by 9E307** [comment]
我跟你一样的情况，我惨的是一大堆FC2刮完之后才发现错了，问题是文件太多也不知道哪些刮错了。
