### ISSUE TITLE
FC2 刮削BUG：番号查询不到就直接刮削成错误番号

### ISSUE THREAD

**Issue by 9E307** [yoshiko2/Movie_Data_Capture#500]
[https://i.loli.net/2021/06/01/wSepaD83JOY45Cy.png](url)

如图，红色部分是原本的真正名字，黄色部分是AVDC识别的名字。
按正常逻辑应该是严格匹配番号，匹配不了直接不刮削。

这个明显的BUG，让我很多FC2片子全部报废，也找不到更名记录，如果有log日志存档就好了！

**Comment by lededev** [comment]
https://github.com/yoshiko2/AV_Data_Capture/wiki#%E8%BD%AF%E9%93%BE%E6%8E%A5
两种软连接方式都可以追溯改名前的视频源文件。
每次使用，我都先用软连接1方式，确定无错误后，用自己编写的powershell脚本，将软连接转为硬链接，然后将结果文件树从output目录移动到同盘的最终视频目录。
启动KODI扫描一遍，软连接只支持网络访问，不支持KODI扫描，所以上一步先转成硬链接。
KODI都能识别之后，再将源视频文件树的源视频文件（已经变成硬链接），用自己编写的opwershell脚本搜索目录树硬链接全部删除。
