### ISSUE TITLE
4.6.5无法正常使用

### ISSUE THREAD

**Issue by gntangled** [yoshiko2/Movie_Data_Capture#501]
[-]Image Download :  Connect retry 1/3
[-]Image Download :  Connect retry 2/3
[-]Image Download :  Connect retry 3/3
[-]Connect Failed! Please check your Proxy or Network!
[-] [E:\2\BMW-231.mp4] ERROR:
[-] [WinError 2] 系统找不到指定的文件。: 'JAV_output/多人作品/BMW-231/BMW-231-fanart.jpg'
麻烦看看是那里设置出问题了

**Comment by lededev** [comment]
cookie文件格式错误也会导致http请求失败，例如字段最后一行末尾也加了一个逗号。先移走json文件看看能不能恢复。
