### ISSUE TITLE
[Feature request]除创建软连接的功能外，再增加一个创建硬链接的功能如何？

### ISSUE THREAD

**Issue by lededev** [yoshiko2/Movie_Data_Capture#510]
软链接可以跨卷，比硬链接更灵活，但是KODI扫描视频文件时不认软链接，这点非常不爽。
硬链接无法跨卷（windows盘符），但在各种操作系统中，都被直接视为常规文件，KODI能支持扫描硬链接视频文件。
硬链接还有一个优点是可以移动位置，改变路径后依然有效。
而目前的软连接是相对路径，一旦移动时改变路径层次，就不能指向正确的视频文件了。

硬链接在Windows文件管理器里和普通文件无法区分，导致管理比较困难，推荐一个windows文件管理器扩展插件，能给硬链接的文件图标加上红色角标，也能右键创建硬链接或者软链接。开源免费，用chocolatey也能装。
https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html

**Comment by inertia42** [comment]
在刮削前为目标文件/文件夹创建硬链接，然后对这些硬链接进行刮削（把movie_lists里的is_link()注释掉）也能达到你要的效果吧。

**Comment by lededev** [comment]
is_link()就是我提交的PR。硬链接我也早就自己搞定了，软链接模式1削刮之后，用自己写的一个脚本就把软链接转成硬链接了。
我发个ISSUE就是问一下有没有人也有我这种需求，如果还有需要，我可以花点时间直接把功能做进去，但这个还得在几个平台下调试，比较麻烦，所以没人需要就算了。

**Comment by sjtuross** [comment]
这个功能对于继续做种还是有用的，Sonarr或Radarr整理影片的默认选项就是hardlink，开源代码应该可以借鉴一下的，希望大佬支持

![image](https://user-images.githubusercontent.com/940110/157002263-3d8bb4ad-1180-4812-955c-7548c8f8c722.png)

**Comment by VergilGao** [comment]
因为我一直都在linux上跑，其实我现在就是手动硬链接一份文件到刮削目录，刮削完成后再mv到jellyfin目录的。
如果能原生支持硬链接当然是好事啊。

**Comment by ylongwang2782** [comment]
> 因为我一直都在linux上跑，其实我现在就是手动硬链接一份文件到刮削目录，刮削完成后再mv到jellyfin目录的。 如果能原生支持硬链接当然是好事啊。

我也是这样的，因为PT保种的缘故，更改地址后就会红种
故此单独建立一个下载目录，再另建一个video目录

目前是使用的hlink创建硬链接
