### ISSUE TITLE
config fild no found

### ISSUE THREAD

**Issue by Sprite-zlc** [yoshiko2/Movie_Data_Capture#513]
Last login: Sun Jun  6 11:59:24 on ttys000

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
/Volumes/189XXXX9151/视频合辑/用所选项目新建的文件夹/AV_Data_Capture-CLI-4.6.6-macOS-amd64/AV_Data_Capture ; exit;
SpritedeMBP:~ sprite$ /Volumes/189XXXX9151/视频合辑/用所选项目新建的文件夹/AV_Data_Capture-CLI-4.6.6-macOS-amd64/AV_Data_Capture ; exit;
[*]================== AV Data Capture ===================
[*]                        4.6.6                         
[*]======================================================
[-]Config file not found!
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[进程已完成]

压缩包解压后，直接打开的，提示如此，config文件是与执行文件在同一文件夹下，请问该如何解决？

**Comment by ilss** [comment]
同样的问题

**Comment by townxue** [comment]
解决了吗？

**Comment by eureka098** [comment]
still the same in 4.7.1
