### ISSUE TITLE
fc2刮削成功视频移到failed和另一个问题

### ISSUE THREAD

**Issue by yfang86** [yoshiko2/Movie_Data_Capture#570]
刮削成功，不过视频移到failed去了

[+] ---Debug info---
[+]  - actor       : 园田美樱
[+]  - cover       : https://fc2club.net/uploadfile/2019/0218/20190218013402624.jpg
[+]  - director    :
[+]  - extrafanart : https://fc2club.net/uploadfile/2019/0218/20190218013402624.jpg
[+]  - imagecut    : 0
[+]  - label       :
[+]  - number      : FC2-1035997
[+]  - outline     : 0 characters
[+]  - release     :
[+]  - runtime     :
[+]  - series      :
[+]  - source      : https://fc2club.net/html/FC2-1035997.html/
[+]  - studio      :
[+]  - tag         : ['网袜', '流出', '']
[+]  - title       : FC2-1035997 蚊香社专属女优园田美樱无码流出
[+]  - trailer     :
[+]  - website     : https://fc2club.net/html/FC2-1035997.html/
[+]  - cover_small :
[+]  - actor_list  : ['园田美樱']
[+]  - naming_rule : FC2-1035997-FC2-1035997 蚊香社专属女优园田美樱无码流出
[+] ---Debug info---
[+]Image Downloaded! JAV_output/园田美樱/FC2-1035997/FC2-1035997-fanart.jpg
[-]Image Download :  Connect retry 1/3
[-]Image Download :  Connect retry 2/3
[-]Image Download :  Connect retry 3/3
[-]Connect Failed! Please check your Proxy or Network!
[-]Move to Failed output folder
[+]Image Copyed!     JAV_output/园田美樱/FC2-1035997/FC2-1035997-poster.jpg
[+]Wrote!            JAV_output/园田美樱/FC2-1035997/FC2-1035997.nfo
Traceback (most recent call last):
  File "core.py", line 380, in paste_file_to_folder
FileNotFoundError: [WinError 2] 系统找不到指定的文件。: 'X:\\新建文件夹\\ok2\\FC2PPV-1035997.mp4' -> 'JAV_output/园田美 樱/FC2-1035997/FC2-1035997.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "AV_Data_Capture.py", line 196, in <module>
  File "AV_Data_Capture.py", line 96, in create_data_and_move
  File "core.py", line 568, in core_main
  File "core.py", line 410, in paste_file_to_folder
TypeError: can only concatenate str (not "int") to str
[32300] Failed to execute script 'AV_Data_Capture' due to unhandled exception!

还有个问题就是打开闪退
[*]================== AV Data Capture ===================
[*]                        4.7.1
[*]======================================================
[*]严禁在墙内宣传本项目
[+]Enable debug
[+]Find 144 movies
[!] - 0.69% [1/144] -
Traceback (most recent call last):
  File "AV_Data_Capture.py", line 196, in <module>
  File "AV_Data_Capture.py", line 90, in create_data_and_move
  File "number_parser.py", line 77, in get_number
AttributeError: 'NoneType' object has no attribute 'group'
[21408] Failed to execute script 'AV_Data_Capture' due to unhandled exception!

**Comment by lededev** [comment]
后一个闪退只会发生在DEBUG=1的情况下，原因是得到空番号。
普通运行模式能够忽略跳过，不会退出。

**Comment by yfang86** [comment]
> 后一个闪退只会发生在DEBUG=1的情况下，原因是得到空番号。
> 普通运行模式能够忽略跳过，不会退出。

感谢！
