### ISSUE TITLE
抓取回來的系列名稱帶 * 號，又設定為目錄名稱時會報錯

### ISSUE THREAD

**Issue by josesun** [yoshiko2/Movie_Data_Capture#579]
最近發現抓回來的 series 名稱中帶有 * 號又設定為目錄名稱時會報錯～猜想是和 Windows 目錄名稱不能含有 * 號有關，
能否修正呢？

感謝
下面是 debug info~

[+] ---Debug info---
[+]  - actor       : 天音ゆい,渚みつき
[+]  - cover       : https://www.javbus.com/pics/cover/8ed5_b.jpg
[+]  - director    : 赤井彗星
[+]  - extrafanart : ['https://pics.dmm.co.jp/digital/video/cawd00261/cawd00261jp-1.jpg', 'https://pics.dmm.co.jp/digital/video/cawd00261/cawd00261jp-2.jpg', 'https://pics.dmm.co.jp/digital/video/cawd00261/cawd00261jp-3.jpg', 'https://pics.dmm.co.jp/digital/video/cawd00261/cawd00261jp-4.jpg', 'https://pics.dmm.co.jp/digital/video/cawd00261/cawd00261jp-5.jpg', 'https://pics.dmm.co.jp/digital/video/cawd00261/cawd00261jp-6.jpg', 'https://pics.dmm.co.jp/digital/video/cawd00261/cawd00261jp-7.jpg', 'https://pics.dmm.co.jp/digital/video/cawd00261/cawd00261jp-8.jpg', 'https://pics.dmm.co.jp/digital/video/cawd00261/cawd00261jp-9.jpg', 'https://pics.dmm.co.jp/digital/video/cawd00261/cawd00261jp-10.jpg']
[+]  - imagecut    : 1
[+]  - label       : kawaii*共演
[+]  - number      : CAWD-261
[+]  - outline     : 0 characters
[+]  - release     : 2021-08-20
[+]  - runtime     : 150
[+]  - series      : kawaii*共演
[+]  - source      : javbus.py
[+]  - studio      : kawaii
[+]  - tag         : ['中出', '美少女', 'キス・接吻', '潮吹', '高畫質', 'DMM獨家', 'ハーレム']
[+]  - title       : 「ねぇどっちが好き？」僕を取り合う親友の妹2人と狂ったようにセックスに没頭し中出ししてしまった31日間…-天音ゆい-渚みつき
[+]  - website     : https://www.javbus.com/CAWD-261
[+]  - cover_small :
[+]  - actor_list  : ['天音ゆい', '渚みつき']
[+]  - trailer     :
[+]  - naming_rule : 「ねぇどっちが好き？」僕を取り合う親友の妹2人と狂ったようにセックスに没頭し中出ししてしまった31日間…-天音ゆい-渚みつき [CAWD-261]
[+] ---Debug info---
Traceback (most recent call last):
  File "core.py", line 79, in create_folder
  File "os.py", line 213, in makedirs
  File "os.py", line 223, in makedirs
OSError: [WinError 123] 檔案名稱、目錄名稱或磁碟區標籤語法錯誤。: '#JAV_Output/kawaii*共演'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "AV_Data_Capture.py", line 202, in <module>
  File "AV_Data_Capture.py", line 102, in create_data_and_move
  File "core.py", line 536, in core_main
  File "core.py", line 84, in create_folder
  File "os.py", line 213, in makedirs
  File "os.py", line 223, in makedirs
OSError: [WinError 123] 檔案名稱、目錄名稱或磁碟區標籤語法錯誤。: '#JAV_Output/kawaii*共演'
[20212] Failed to execute script 'AV_Data_Capture' due to unhandled exception!

**Comment by icedrain0611** [comment]
这个是弱智日本人想出来的，只能说别用Windows就能解决
