### ISSUE TITLE
搜刮不到片名時, 把全部片名改成 本橋実来 ADZ335 

### ISSUE THREAD

**Issue by ronaldo224** [yoshiko2/Movie_Data_Capture#587]
搜刮不到片名時, 把全部片名改成 本橋実来 ADZ335

例
the number is [MYWIFE-1064]
[+]Image Downloaded! JAV_output/本橋実来/[] [ADZ335]

**Comment by rhct924** [comment]
[priority]
website=fc2club,javbus,airav,fanza,xcity,javdb,mgstage,fc2,avsox,dlsite,carib
移除xcity就可以避免這問題了

**Comment by ronaldo224** [comment]
成功了謝謝
