### ISSUE TITLE
docker下刮削失败

### ISSUE THREAD

**Issue by lzylipu** [yoshiko2/Movie_Data_Capture#592]
AV Data Capture ===================[*]                        4.7.1                         [*]======================================================[*]严禁在墙内宣传本项目[+]Find 1 movies[!] - 100.% [1/1] -[!]Making Data for [/app/data/abw144.mp4], the number is [abw144][-]Connect retry 1/3[-]Connect retry 1/3[-]Connect retry 2/3[-]Connect retry 2/3[-]Connect retry 3/3[-]Connect Failed! Please check your Proxy or Network![-]HTTPSConnectionPool(host='www.jav321.com', port=443): Max retries exceeded with url: /search (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2c2c095040>, 'Connection to www.jav321.com timed out. (connect timeout=5)'))[-]Connect retry 3/3[-]Connect Failed! Please check your Proxy or Network![-]HTTPSConnectionPool(host='fc2club.net', port=443): Read timed out. (read timeout=5)[-]Connect retry 1/3[-]Connect retry 2/3[-]Connect retry 3/3[-]Connect Failed! Please check your Proxy or Network![-]HTTPSConnectionPool(host='www.jav321.com', port=443): Max retries exceeded with url: /search (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7f2c245a1670>, 'Connection to www.jav321.com timed out. (connect timeout=5)'))[-]Connect retry 1/3[-]Connect retry 2/3[-]Connect retry 3/3[-]Connect Failed! Please check your Proxy or Network![-]HTTPSConnectionPool(host='fc2club.net', port=443): Read timed out. (read timeout=5)[-]Connect retry 1/3[-]Movie Data not found![-]Move to Failed output folder[*]======================================================[+]Used 74.24s[+]All finished!!!
--

**Comment by lededev** [comment]
你的docker没配通网络吧。
