### ISSUE TITLE
有一些番号会被识别成  [] ADZ335

### ISSUE THREAD

**Issue by trtrm** [yoshiko2/Movie_Data_Capture#614]
![ESEC%`U51C_99H5LY%N0D@E](https://user-images.githubusercontent.com/92213076/136656864-11fd5d26-d9ac-4a81-b340-c5ad30050b67.png)

所有不被识别的都会被重名成这个，导致丢失名称，有些视频也丢了

**Comment by lededev** [comment]
用5.0.1或者[PR](https://github.com/yoshiko2/AV_Data_Capture/pull/607)里最新的代码：https://github.com/yoshiko2/AV_Data_Capture/actions/runs/1323431625
