### ISSUE TITLE
想請作者增加FC2刮削時如無演員則以發佈者進行資料夾分類

### ISSUE THREAD

**Issue by gn01791992** [yoshiko2/Movie_Data_Capture#617]
因為目前刮削FC2皆會以標題進行資料夾創建，久之整理起來較為麻煩，想煩請作者增加以發佈者為演員選項

**Comment by lededev** [comment]
以卖家为演员显然不正确，我已经提交的PR里，用javdb数据源时，将卖家归类到工作室了，你的一级目录如果是演员，二级目录设置为工作室的话，文件夹建立时演员不存在，就会以工作室为一级目录。
https://github.com/yoshiko2/AV_Data_Capture/blob/189f4db6161f6393cbd5d3c1c204153a3f0f7b26/WebCrawler/javdb.py#L63
你可以试用，下载Action里的版本或者按https://github.com/yoshiko2/AV_Data_Capture/issues/616里的方法直接python脚本运行。
