### ISSUE TITLE
mac打不开？

### ISSUE THREAD

**Issue by nfeuism** [yoshiko2/Movie_Data_Capture#627]
请问mca用什么软件打开，解压后只有AV_Data_Capture和config.ini文件

**Comment by lededev** [comment]
在终端里用命令行执行，终端的英文叫terminal，不过我没MAC没试过。

**Comment by uyx6345** [comment]
你是不是用的M1芯片？

**Comment by Sprite-zlc** [comment]
> 在终端里用命令行执行，终端的英文叫terminal，不过我没MAC没试过。

请问具体使用说明命令执行？方便给个操作指引吗？

**Comment by Sprite-zlc** [comment]
试了一下，我是从mac 挂载了NAS中的硬盘，然后把 文件放在了 NAS的目录下，但是读取了本地的视频，不是文件所在目录的视频，请问这个什么原因啊？

**Comment by confeitocyan** [comment]
所以意思是M1的MAC現在暫時不能使用是嗎?

**Comment by yoshiko2** [comment]
笑死，根本买不起macbook

**Comment by confeitocyan** [comment]
了解，謝謝大大

**Comment by lededev** [comment]
> 笑死，根本买不起macbook

同样买不起MAC，今年电脑预算被我买了i9 12900K, 128GB DDR5 RAM, NV 3080TI 12GB, SSD 980PRO 2TB x 3 组RAID0，六块SATA 18TB硬盘组RAID10每天备份，已经把钱用完了，没钱买MAC。
