### ISSUE TITLE
无法连接到源网站

### ISSUE THREAD

**Issue by TianYaDY** [yoshiko2/Movie_Data_Capture#628]
全局代理模式和socks5都提示连不上，包括路由器的全局模式和PC端netch的全局模式。。。

**Comment by lededev** [comment]
用香港或者美国的IP试试，别用日本或者大陆的IP。

**Comment by TianYaDY** [comment]
新加坡的，香港的，棒子的，都试过了> 用香港或者美国的IP试试，别用日本或者大陆的IP。

**Comment by lededev** [comment]
我这里一直能连上啊，你把配置文件改名，让它自动生成一份新的再试试，如果能用，再把你旧配置文件上你的改动搬到新配置文件里。
每个版本的程序有对应的配置文件，不能直接用旧的。

**Comment by TianYaDY** [comment]
刚下的，不过你说的我也去试试看> 我这里一直能连上啊，你把配置文件改名，让它自动生成一份新的再试试，如果能用，再把你旧配置文件上你的改动搬到新配置文件里。
> 
> 每个版本的程序有对应的配置文件，不能直接用旧的。
> 
>

**Comment by TianYaDY** [comment]
放弃了，就是连不上。。。> 我这里一直能连上啊，你把配置文件改名，让它自动生成一份新的再试试，如果能用，再把你旧配置文件上你的改动搬到新配置文件里。
> 
> 每个版本的程序有对应的配置文件，不能直接用旧的。
> 
>

**Comment by 5536086** [comment]
我也是一直连不上，开代理不开代理都连不上

**Comment by lededev** [comment]
这种“连不上”三个字的issue没啥意义，没有操作系统平台信息，没有网络环境信息，没有可以重现故障的具体操作步骤，别人根本没法重复你的失败过程，神仙也帮不了你啊。
所以对“连不上”三个字，我只能回复一句：我能用。
