### ISSUE TITLE
提取的“风格”比较杂乱，希望优化一下

### ISSUE THREAD

**Issue by gbfang** [yoshiko2/Movie_Data_Capture#634]
提取的“风格”有的有番号，有的有日文，导致整理时风格太多，建议统一只生成常用的分类，“风格”宁可少不要多
![image](https://user-images.githubusercontent.com/92192093/141400533-6181997f-4895-4338-a17e-165c148c853b.png)

**Comment by hejianjun** [comment]
那个版本的，正常是提取的tag，可能是爬虫写错了

**Comment by ylongwang2782** [comment]
> 那个版本的，正常是提取的tag，可能是爬虫写错了

我也有这个问题，需要如何修改？
