### ISSUE TITLE
为什么名字变成了汉化过的？

### ISSUE THREAD

**Issue by eightsheep67** [yoshiko2/Movie_Data_Capture#639]
5.0.3版本，涼森れむ变成了凉森玲梦？？

**Comment by y49711** [comment]
config有個trnaslation改0

**Comment by eightsheep67** [comment]
> config有個translation改0
都是默认的config，我看里面和translate相关的都是0

**Comment by 0x11901** [comment]
我也是同样的问题，translate配置是0

**Comment by playmsg** [comment]
目测应该是
`
; 繁简转换 繁简转换模式mode=0:不转换 1:繁转简 2:简转繁
[cc_convert]
mode=0
`
的问题。把actor的日文当繁体了。

**Comment by 0x11901** [comment]
> 

确实是，我分析了一下重灾区是高桥圣子，更新了之后设置繁简转换模式mode=0问题就解决了
