### ISSUE TITLE
大佬，请问后期能否添加一个标签过滤功能

### ISSUE THREAD

**Issue by tecsar9000** [yoshiko2/Movie_Data_Capture#645]
![屏幕截图 2021-11-18 233309](https://user-images.githubusercontent.com/76143747/142446008-83c147da-93aa-4008-b53b-ce609a2198a2.png)
)，如图，刮削出来的nfo里几乎每一部都有番号的标签，导致plex识别的时候自动生成了一个合集，删起来好麻烦.....能否添加一个过滤规则，把不重要的非分类标签全给过滤掉

**Comment by lededev** [comment]
这是一个bug，下个版本标签不会包含番号。

**Comment by yoshiko2** [comment]
5.0.4已修复
