### ISSUE TITLE
问下各位大佬，extrafanart在jellyfin中怎么显示

### ISSUE THREAD

**Issue by eightsheep67** [yoshiko2/Movie_Data_Capture#646]
我看5.0.4刮的时候多了一个extrafanart文件夹，里面是剧照吧，这个东西在jellyfin中怎么显示出来呢？我现在只能在修改图片中看到有这些图片。

**Comment by lbcz-tian** [comment]
我也很好奇这个怎么显示，刮削的时候下载了但是jellyfin看不到😳帮顶

**Comment by hejianjun** [comment]
> 我也很好奇这个怎么显示，刮削的时候下载了但是jellyfin看不到😳帮顶

在编辑图片里面可以看到并切换背景，但是貌似没有太大作用

**Comment by kennylee60** [comment]
有人知道这个怎么显示了吗？

**Comment by nxy1999** [comment]
帮顶

**Comment by icedir** [comment]
@eightsheep67 我也发现了哈哈，这个你解决了吗
