### ISSUE TITLE
封面裁切不理想是否可以考虑引入AVDC的封面AI定位人脸功能

### ISSUE THREAD

**Issue by lbbboy** [yoshiko2/Movie_Data_Capture#656]
AVDC 我一直都在使用，可是最近不能用了，作者也没更新。AV_Data_Capture
 封面裁切不理想，AVDC有AI定位人脸功能。

**Comment by hejianjun** [comment]
AVDC的代码我看了，是要上传到百度的，这个可能之后要收费，而且要是监管的话可能会被逮到

**Comment by hejianjun** [comment]
import face_recognition
from PIL import Image

filename = "91CM-143.png"
image = face_recognition.load_image_file(filename)
face_locations = face_recognition.face_locations(image, 0, 'hog')
print(face_locations)
img = Image.open(filename)
width, height = img.size
print(width, height)
top, right, bottom, left = face_locations[0]
# 中心点
center = (right+left)/2
# 新宽带是高度的2/3
cropWidthHalf = int(height/3)
cropLeft = center-cropWidthHalf
cropRight = center+cropWidthHalf
# 越界处理
if cropLeft < 0:
    cropLeft = 0
    cropRight = cropWidthHalf*2
elif cropRight > width:
    cropLeft = width-cropWidthHalf*2
    cropRight = width
print(cropLeft, cropRight)
img2 = img.crop((cropLeft, 0, cropRight, height))
img2.show()

**Comment by hejianjun** [comment]
```
import face_recognition
from PIL import Image

filename = "91CM-143.png"
image = face_recognition.load_image_file(filename)
face_locations = face_recognition.face_locations(image, 0, 'hog')
print(face_locations)
img = Image.open(filename)
width, height = img.size
print(width, height)
top, right, bottom, left = face_locations[0]
# 中心点
center = (right+left)/2
# 新宽带是高度的2/3
cropWidthHalf = int(height/3)
cropLeft = center-cropWidthHalf
cropRight = center+cropWidthHalf
# 越界处理
if cropLeft < 0:
    cropLeft = 0
    cropRight = cropWidthHalf*2
elif cropRight > width:
    cropLeft = width-cropWidthHalf*2
    cropRight = width
print(cropLeft, cropRight)
img2 = img.crop((cropLeft, 0, cropRight, height))
img2.show()
```

**Comment by hejianjun** [comment]
写了个测试代码但是需要使用face_recognition和dlib

**Comment by hejianjun** [comment]
https://github.com/hejianjun/AV_Data_Capture/tree/feature/91
