### ISSUE TITLE
如果不麻烦的话，有外挂字幕时，可否也能给图片加上字幕的水印？

### ISSUE THREAD

**Issue by PerryLayne** [yoshiko2/Movie_Data_Capture#657]
一般-c之类的都是内封字幕用的。
外挂字幕的我不想加后缀之类的。
如果作者心情好能加一个的话先谢过了。

**Comment by icedrain0611** [comment]
我印象中naming rule 里面加上-c就行了，location rule不加的话文件名还是不带C的

**Comment by sirliu** [comment]
> 

哪里有外挂字幕，求推荐。
