### ISSUE TITLE
封面截取能否像GUI加入人脸识别+nfo标题过长jellyfin无法读取

### ISSUE THREAD

**Issue by shallwei** [yoshiko2/Movie_Data_Capture#659]
刮削素人片 发现几个问题
1.标准封面都是默认截取最右，现在很多素人片都不是这样，如200gana，能否像gui版一样加入人脸识别，gui已经很久不更新，现在已经不可用了
2.能否设置个参数控制nfo title/orgnaititele/sorttititle长度,jellyfin 10.77部分太长的标题 nfo无法读取

**Comment by hejianjun** [comment]
这边我添加了一个功能 不过需要安装 dlib和 face_recognition https://github.com/hejianjun/AV_Data_Capture/tree/feature/91
