### ISSUE TITLE
预告片下载的问题

### ISSUE THREAD

**Issue by MingzSu** [yoshiko2/Movie_Data_Capture#661]
当前软件版本：6.0.1
问题描述：当打开预告片下载的选项时，当元数据网站存有预告片资源和下载链接时，没有出现Bug；但当元数据网站时不存在预告片资源时或下载链接有问题，软件会下载预告片超时从而将原视频移动到failed文件夹中
问题举例以及截图：举例，以javdb为元数据站，视频为ipx-743，经确认，javdb目前尚无此视频预告片，在进行开启了下载预告片的刮削时
![image](https://user-images.githubusercontent.com/49946414/146634587-17da9be7-06f2-43ef-981d-1a0fa08b7760.png)
问题猜测：当我们查看已经刮削的数据时（即对应的nfo），可以看到
“<trailer>https:</trailer>”
可以看到此下载链接存在，但是是肯定下载不下来的，不知道能否稍微修改一下这里面的逻辑，若是预告片下载链接有误或者下载超时，就放弃预告片的下载，但是并不要将此视频直接放弃，移动到failed文件夹中

**Comment by lededev** [comment]
你得提供完整日志和配置，以便别人重现你的这种情况。

**Comment by MingzSu** [comment]
感谢开发人员关注，我现在完整的具体案例和日志进行提供
软件版本：windows amd64 6.0.1 exe版本
进行测试的环境：工作文件下包含3个文件：（ipx-743.mp4 config.ini 运行程序），具体配置文件如下（由于github的上传附件要求 这是txt版本）
[config.txt](https://github.com/yoshiko2/Movie_Data_Capture/files/7740403/config.txt)
其中，重要的选项为打开预览片的下载，元数据站选择javdb。现在开始运行后，运行后程序报错，但是仍然刮削了数据，其中刮削结果如下
![微信截图_20211219142329](https://user-images.githubusercontent.com/49946414/146666293-5d757603-bce7-45e6-ae56-0148026f0a05.png)
可以看到，视频没有正确的移动到对应的文件夹下，被移动到了failed文件夹中
![微信截图_20211219142401](https://user-images.githubusercontent.com/49946414/146666312-01c29dc5-d7f1-442a-94c5-06d989eee32a.png)
具体的工作日志如下
[mdc_20211219T142114.txt](https://github.com/yoshiko2/Movie_Data_Capture/files/7740408/mdc_20211219T142114.txt)

想法：此问题如同issure描述一样，只要元数据站中的预告片链接有问题，这个可以通过查看已经刮削到的元数据可以得知，以上面这个案例举例，刮削到的nfo文件中
![image](https://user-images.githubusercontent.com/49946414/146666416-aedf3846-c142-42ba-91d3-bb4b0557e187.png)
trailer的链接明显不能下载，软件能不能不要直接将此视频放弃执行并移动到failed文件夹中，而是在可以下载到的情况就下载，无法下载的话就不更新nfo文件的trailer内容，仍然正常工作

**Comment by MingzSu** [comment]
> 你得提供完整日志和配置，以便别人重现你的这种情况。 提供用-g参数打开调试信息的日志。

谢谢开发人员关注 详细日志案例配置我发在下面了

**Comment by yoshiko2** [comment]
javdb不存在预告片

**Comment by MingzSu** [comment]
> javdb不存在预告片

谢谢开发人员关注。是的，但是我觉得这个地方逻辑能不能稍微调整一下，因为现在是如果没有预告片的情况下，直接将视频移入failed文件夹，能不能调整为如果下载预告片失败不要移入failed，直接继续正常工作，nfo也不要更新预告片信息，这样选择性的运行，感觉这样更方便合理一些，仅仅是个人见解

**Comment by yoshiko2** [comment]
https://github.com/yoshiko2/Movie_Data_Capture/commit/21bd3c60b774fb7b86453b323b7c36ea3f4cabc3

**Comment by yoshiko2** [comment]
@MingzSu 示范性Issues 提供完整截图+配置+日志
