### ISSUE TITLE
重复的号取不到正确的

### ISSUE THREAD

**Issue by sr-72** [yoshiko2/Movie_Data_Capture#664]
MIDV-021
存在2007-05-25的一部、2021-12-21的一部，但只能刮削到2007-05-25的

**Comment by lededev** [comment]
一个番号有多集的电影，需要你手动改名为
MIDV-021-CD1.mp4
MIDV-021-CD2.mp4
然后再刮削。

**Comment by sr-72** [comment]
> 一个番号有多集的电影，需要你手动改名为 MIDV-021-CD1.mp4 MIDV-021-CD2.mp4 然后再刮削。

感谢回复   这个不是多集，是不同的电影。这种情况很少见，不过这部我在db上查真的是重了的不同电影
只不过配置里优先javbus而正好javbus里只有这部老的，换了javdb优先就正常了

**Comment by hecheng337** [comment]
> 一个番号有多集的电影，需要你手动改名为 MIDV-021-CD1.mp4 MIDV-021-CD2.mp4 然后再刮削。

开发者你好，我今天也碰到了一样的问题。
你可以看看[这个搜索结果](https://www.javbus.com/search/MIDV-024)，就知道为什么会出问题了

**Comment by hecheng337** [comment]
不好意思，我刚刚忘记贴日志了。

[*]======================================================
[!]              - 33.3% [24/72] -             23:59:50
[!] [MIDV-024] As Number making data for '\\Yui\video\Adult\MIDV-024\hhd800.com@MIDV-024.mp4'
[+]Find movie [MIDV-024] metadata on website 'javbus'
[+]Image Downloaded! Organized\#\[2010] 天使之吻特别版女同感性爱情合集 [MIDV-024]\MIDV-024-fanart.jpg
[+]Successfully downloaded 20 extrafanart to 'Organized\#\[2010] 天使之吻特别版女同感性爱情合集 [MIDV-024]\extrafanart'
[+]Use model         hog
[+]Found person      1
[+]Image Cutted!     Organized\#\[2010] 天使之吻特别版女同感性爱情合集 [MIDV-024]\MIDV-024-poster.jpg
[+]Wrote!            Organized\#\[2010] 天使之吻特别版女同感性爱情合集 [MIDV-024]\MIDV-024.nfo
[*]======================================================

而 MIDV-024 一般指的是石川澪21年底的作品。出现这个错误应该是网站的锅，但是确实造成很大的麻烦。
作为一个强迫症重度患者，我现在必须得一部一部检查刮削的结果才放心 lol

我还没有仔细研究过 javbus 部分的爬取逻辑，不过我在想 是否可以在抓取过程中增加判断逻辑，当存在多个搜索结果时 自动将番号映射为较新的那一个

**Comment by lededev** [comment]
不同发片商的番号撞号的问题没法避免，番号这玩意就没有相互协调的组织存在。
选较新的也不一定是正确的，这种重名问题不考虑用程序来解决。
