### ISSUE TITLE
请求添加刮削后不移动直接对原文件重命名的功能

### ISSUE THREAD

**Issue by xjc1119** [yoshiko2/Movie_Data_Capture#666]
请求添加功能：刮削后不移动到新建文件夹，而是直接对原文件重命名。这样会大幅提升winnas体验。
请求添加功能：字段刮削为空时临时换用另一个网站再刮削。比如actor就是重灾区，javdb刮削不到临时换javbus试试，而不需要修改配置文件再次运行。

**Comment by lededev** [comment]
运行参数用`-m3`就是不移动原地生成.nfo，一般是用在对已经刮削完成的目录里更新.NFO或者剧照或者封面图片，但你想初次就这么用应该也是支持的。
或者配置文件里main_mode改为3

**Comment by xjc1119** [comment]
> 运行参数用`-m3`就是不移动原地生成.nfo，一般是用在对已经刮削完成的目录里更新.NFO或者剧照或者封面图片，但你想初次就这么用应该也是支持的。 或者配置文件里main_mode改为3

并非生成.nfo，而是在整理模式下对视频原文件.mp4 .mkv之类进行改名，并且不移动文件

**Comment by xjc1119** [comment]
目前整理模式逻辑是：
对
temp/number.mp4
整理后结果是
temp/JAV_output/number+title+actor/number.mp4
希望有新模式可以只改名不归纳不移动
temp/number+title+actor.mp4
绞尽脑汁也不知道如何达成，只能整理后CtrlCV逐个重命名

**Comment by lededev** [comment]
如果是BT做种，需求是不能改名，也不能移动位置，不能引入破坏性，用模式三就很好。
你的需求是原地改名，引入了破坏性，模式三就不适用了。
要想达成你的需求，你可以用软链接模式1，加-p参数假装执行，会得到一份改名后的执行结果的日志。
你得自己写脚本分析该日志，用日志中的结果对原电影文件进行改名。
因为你这需求很小众，除非你自己提交代码或者有开发者也对这个需求感兴趣，否则软件直接支持的可能性不大。

**Comment by yoshiko2** [comment]
目前没有打算新增这个功能的想法，支持赏金制新增功能或者定制
