### ISSUE TITLE
请教有没有防被封功能，我几个日本IP肖刮了大概几十部就被DMM封禁了，能否伪装下UA或者什么？

### ISSUE THREAD

**Issue by sisikam** [yoshiko2/Movie_Data_Capture#672]
大佬谢谢！ 我今天刮了一批片子，一会这些IP 就都被DMM封锁了（直接拒绝），换了新IP就好了。但是IP总是有限的，有什么办法，比如伪装UA，人工设定肖刮下载时间间隔等。。。

**Comment by lededev** [comment]
一次太多请求就会被封IP，善用stop_counter配置参数，每次刮削5部，每隔10分钟再执行下一次刮削，这样多次少量完成，不容易被封IP。

**Comment by sisikam** [comment]
好 谢谢。

**Comment by uiopm** [comment]
> 

你好，想请问每隔10分钟进行刮削能通过config.ini配置吗，还是通过自己设定定时任务完成

**Comment by lededev** [comment]
> > 
> 
> 你好，想请问每隔10分钟进行刮削能通过config.ini配置吗，还是通过自己设定定时任务完成

目前我是写脚本来完成这个定时执行的。因为每次执行完成后我会分析日志，根据上一次的处理结果，如果没被封ip，就等待一定时间再次执行。如果已经封ip了，由脚本切换代理换个ip马上执行下一次刮削然后重复这个过程。直到日志中再没有待处理的视频。

**Comment by uiopm** [comment]
谢谢你的解答，还想请问stop_counter设置的大小多少合适呢，因为我视频数量和代理ip不是很多



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月16日(周日) 凌晨1:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yoshiko2/Movie_Data_Capture] 请教有没有防被封功能，我几个日本IP肖刮了大概几十部就被DMM封禁了，能否伪装下UA或者什么？ (Issue #672)




    
你好，想请问每隔10分钟进行刮削能通过config.ini配置吗，还是通过自己设定定时任务完成
  
目前我是写脚本来完成这个定时执行的。因为每次执行完成后我会分析日志，根据上一次的处理结果，如果没被封ip，就等待一定时间再次执行。如果已经封ip了，由脚本切换代理换个ip马上执行下一次刮削然后重复这个过程。直到日志中再没有待处理的视频。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lededev** [comment]
我设置的7，每被封一次IP就减少1。

**Comment by uiopm** [comment]
好的，谢谢你的解答



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月16日(周日) 上午10:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yoshiko2/Movie_Data_Capture] 请教有没有防被封功能，我几个日本IP肖刮了大概几十部就被DMM封禁了，能否伪装下UA或者什么？ (Issue #672)




 
我设置的7，每被封一次IP就减少1。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
