### ISSUE TITLE
软件无法使用ERROR

### ISSUE THREAD

**Issue by Dantezcx** [yoshiko2/Movie_Data_Capture#675]
[+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30
[+]Find 2 movies.
[*]======================================================
[!]                - 50.0% [1/2] -             14:42:13
[!] [SSIS-240] As Number making data for '\\192.168.0.124\影剧\H\整理\SSIS-240-C.mp4'
[+]Find movie [SSIS-240] metadata on website 'javdb'
[-] [\\192.168.0.124\影剧\H\整理\SSIS-240-C.mp4] ERROR:
[-] unexpected EOF while parsing (<string>, line 1)
[!]                - 100.% [2/2] -             14:42:17
[!] [ssis-291] As Number making data for '\\192.168.0.124\影剧\H\整理\ssis-291-C.mp4'
[+]Find movie [ssis-291] metadata on website 'javdb'
[-] [\\192.168.0.124\影剧\H\整理\ssis-291-C.mp4] ERROR:
[-] unexpected EOF while parsing (<string>, line 1)
[+]Running time 0:00:08.091  End at 2022-01-15 14:42:20
[+]All finished!!!

**Comment by hejianjun** [comment]
javdb的cookie json异常

**Comment by hejianjun** [comment]
你需要检查你配置的javadb的json
