### ISSUE TITLE
person_info

### ISSUE THREAD

**Issue by QKSSliu** [yoshiko2/Movie_Data_Capture#677]
### **同一个文件夹前面好好地后来突然报错 Error in AVDC_Main: 'person_info'**
[*]======================================================
[!] - 1 - 100.% - [32/32] -
[!]Making Data for   [//Hannibaserver/收藏夹/骑兵/七海蒂娜/STARS121-C.mp4], the number is [STARS-121]
[+] ---Debug ### info---
   [+]-actor        : 七海ティナ
   [+]-cover        : https://javbus.com/pics/cover/7al0_b.jpg
   [+]-director     : ドラゴン西川
   [+]-imagecut     : 0
   [+]-number       : STARS-121
   [+]-release      : 2019-09-10
   [+]-runtime      : 120
   [+]-source       : javbus.py
   [+]-studio       : SODクリエイト
   [+]-tag          : 高畫質, 單體作品, 蕩婦, 苗條, 偶像藝人, 美容院, 多選提交
   [+]-title        : 七海ティナ-精巣吸引バキュームエステサロン
   [+]-website      : https://www.javbus.com/STARS-121
   [+]-year         : 2019
   [+]-naming_media : number-title
   [+]-naming_file  : number
   [+]-folder_name  : number-title-release
[+] ---Debug info---
[+]Folder : Hannibaserver\收藏夹\骑兵\七海蒂娜/JAV_output/STARS-121-七海ティナ-精巣吸引バキュームエステサロン-2019-09-10
[+]From   : https://www.javbus.com/STARS-121
[+]Thumb Downloaded!  STARS-121-C-thumb.jpg
[-]Error in AVDC_Main: 'person_info'
[*]======================================================
[+]All finished!!!
[*]======================================================

**Comment by hejianjun** [comment]
你这个是AVDC啊，这个缺少百度ai的账号
