### ISSUE TITLE
指定站点功能好像失效了？

### ISSUE THREAD

**Issue by skypjsfly** [yoshiko2/Movie_Data_Capture#679]
有些片子在别的站刮削内容不对，想指定某个站点刮削，但是好像测试不行，还是搜索所有站点

**Comment by lededev** [comment]
别好像啊，请贴一份可以重新问题的带调试信息日志。

**Comment by lededev** [comment]
别好像啊，请贴一份可以重现问题的带调试信息日志。

**Comment by skypjsfly** [comment]
![Uploading Screenshot_20220129-134130_Via.png…]()
![Uploading Screenshot_20220129-134322_Via.png…]()

**Comment by skypjsfly** [comment]
![Screenshot_20220129-134130_Via](https://user-images.githubusercontent.com/32484309/151649219-bacf22c8-59c4-45e9-9c15-90bb0adbf9b4.png)
![Screenshot_20220129-134322_Via](https://user-images.githubusercontent.com/32484309/151649221-adb19147-d690-4589-9f52-49138a4118d4.png)

**Comment by skypjsfly** [comment]
日志已经上传

**Comment by lededev** [comment]
我用你日志里的番号能抓到数据，默认配置文件但修改为软链接方式，数据源是javbus。
你指定的哪个站点，看你的日志我认为你应该先检查从NAS到外网的网络访问是否正常。

```
[*]================= Movie Data Capture =================
[*]                        6.0.1
[*]======================================================
[*] - Windows-10-10.0.22000-SP0
[*] - AMD64 - Python-3.10.2
[*]======================================================
[*] - 严禁在墙内宣传本项目 -
[*]======================================================
[+]Start at 2022-01-29 13:56:38
[+]Load Config file 'C:\Users\user\.mdc\config.ini'.
[+]Enable debug
[!]Enable soft link
[!]CmdLine: -d0 -igp .
[+]Main Working mode ## 1: Scraping ## , stop_counter=20
[+]Find 1 movies.
[*]======================================================
[!]                - 100.% [1/1] -             13:56:38
[!] [GDTM-012] As Number making data for 'Z:\t\GDTM-012.mp4'
[+]select javbus
[!]MP 进程[airavwiki]运行0.410秒，结束于13:56:42返回结果: どうやったらそんな格好に！？娘のあまりの寝相の悪さにビックリ！？しかし、その寝相の悪さのおかげで立派に成長した娘のおっぱいやお尻！さらにはマ○コまでが丸見え！父親としてここは我慢！と思いつつも柔らかそうなおっぱいとかわいい乳首！スケベなお尻に興奮が抑えられずについつい触ってしまい、キレイなマ○コは舐めてしまう父親失格の私に気付いた娘も興奮したのか禁断の近親相姦に！6組のイケない父娘セックス収録！
[-]MP getOutline_xcity Error: list index out of range, number [GDTM-012].
[!]MP 进程[xcity]运行1.370秒，结束于13:56:43返回结果: [空]
[!]MP 进程[airav]运行1.641秒，结束于13:56:43返回结果: 怎麼衣服亂成這樣在睡啊！？女兒睡姿真欠幹！？奶子屁屁都成長到美味可口啊、只好趕快用肉棒來好好教訓她了！6組 亂倫父女幹砲！
[!]MP 进程[avno1]运行2.444秒，结束于13:56:44返回结果: 怎么衣服乱成这样在睡啊！？女儿睡姿真欠幹！？奶子屁屁都成长到美味可口啊、只好赶快用肉棒来好好教训她了！6组 乱伦父女幹砲！
[-]get_html_session() failed. HTTPSConnectionPool(host='www.amazon.co.jp', port=443): Max retries exceeded with url: /s?k=%E4%BD%95%E3%81%A7%E3%81%9D%E3%82%93%E3%81%AA%E3%82%B9%E3%82%B1%E3%83%99%E3%81%AA%E7%8A%B6%E6%85%8B%E3%81%A7%E5%AF%9D%E3%81%A6%E3%82%8B%E3%81%AE%EF%BC%81%EF%BC%9F%E5%AF%9D%E7%9B%B8%E3%81%AE%E6%82%AA%E3%81%84%E5%A8%98%E3%81%8C%E3%81%82%E3%82%89%E3%82%8C%E3%82%82%E3%81%AA%E3%81%84%E5%A7%BF%E3%81%A7%E5%AF%9D%E3%81%A6%E3%81%84%E3%81%9F%EF%BC%81%E7%88%B6%E3%81%A8%E3%81%97%E3%81%A6%E4%BA%BA%E3%81%A8%E3%81%97%E3%81%A6%E6%88%91%E6%85%A2%E3%81%97%E3%81%AA%E3%81%8F%E3%81%A6%E3%81%AF%E3%81%84%E3%81%91%E3%81%AA%E3%81%84%E3%81%AE%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A4%E3%81%84%E8%A7%A6%E3%81%A3%E3%81%A6%E3%81%97%E3%81%BE%E3%81%84%E2%80%A6 (Caused by ResponseError('too many 503 error responses'))
[-]MP getOutline_amazon Error: cannot unpack non-iterable NoneType object, number [GDTM-012], title: 何でそんなスケベな状態で寝てるの！？寝相の悪い娘があられも ない姿で寝ていた！父として人として我慢しなくてはいけないのについつい触ってしまい…
[!]MP 进程[amazon]运行7.564秒，结束于13:56:49返回结果: [空]
[!]Storyline线程池模式运行5个任务共耗时(含启动开销)7.564秒，结束于13:56:49，[选 中avno1字数:60]，airav字数:60，airavwiki字数:199，xcity:空，amazon:空
[+]Find movie [GDTM-012] metadata on website 'javbus'
[+] ------- DEBUG INFO -------
[+]  - actor          :
[+]  - cover          : https://www.javbus.com/pics/cover/4k2i_b.jpg
[+]  - director       : ロビーくん
[+]  - extrafanart    : 19 links
[+]  - imagecut       : 1
[+]  - label          :
[+]  - number         : GDTM-012
[+]  - outline        : 60 characters
[+]  - release        : 2014-12-05
[+]  - runtime        : 240
[+]  - series         :
[+]  - source         : javbus.py
[+]  - studio         : ゴールデンタイム
[+]  - tag            : ['ゴールデンタイム', '4小时+', '乱伦', '企画', 'DMM独家', '高中生']
[+]  - title          : 你怎么睡得这么淫荡！ ？？我的女儿，睡得不好，睡得没有冰 雹！作为一个人作为一个父亲，我不得不忍受它，但我只是碰了它......
[+]  - website        : https://www.javbus.com/GDTM-012
[+]  - original_title : 何でそんなスケベな状態で寝てるの！？寝相の悪い娘があられもない姿で寝ていた！父として人として我慢しなくてはいけないのについつい触ってしまい…
[+]  - cover_small    :
[+]  - actor_list     : ['']
[+]  - trailer        :
[+]  - naming_rule    : 你怎么睡得这么淫荡！ ？？我的女儿，睡得不好，睡得没有冰 雹！作为一个人作为一个父亲，我不得不忍受它，但我只是碰了它......
[+] ------- DEBUG INFO -------
[+]Image Downloaded! Z:\#JAV_output\#\[2014] 何でそんなスケベな状態で寝てるの！ ？寝相の悪い娘があられもない姿で寝ていた！父として人として我慢しなくてはいけないのについつい触ってしまい… [GDTM-012]\GDTM-012-fanart.jpg
[+]Successfully downloaded 19 extrafanart to 'Z:\#JAV_output\#\[2014] 何でそんなスケベな状態で寝てるの！？寝相の悪い娘があられもない姿で寝ていた！父として人として我慢しなくてはいけないのについつい触ってしまい… [GDTM-012]\extrafanart'
[!]Extrafanart download ThreadPool mode runtime 1.596s
[+]Image Cutted!     Z:\#JAV_output\#\[2014] 何でそんなスケベな状態で寝てるの！ ？寝相の悪い娘があられもない姿で寝ていた！父として人として我慢しなくてはいけないのについつい触ってしまい… [GDTM-012]\GDTM-012-poster.jpg
[+]Wrote!            Z:\#JAV_output\#\[2014] 何でそんなスケベな状態で寝てるの！ ？寝相の悪い娘があられもない姿で寝ていた！父として人として我慢しなくてはいけないのについつい触ってしまい… [GDTM-012]\GDTM-012.nfo
[*]======================================================
[+]Running time 0:00:12.847  End at 2022-01-29 13:56:51
[+]All finished!!!
```

**Comment by skypjsfly** [comment]
> 我用你日志里的番号能抓到数据，默认配置文件但修改为软链接方式，数据源是javbus。 你指定的哪个站点，看你的日志我认为你应该先检查从NAS到外网的网络访问是否正常。
> 
> ```
> [*]================= Movie Data Capture =================
> [*]                        6.0.1
> [*]======================================================
> [*] - Windows-10-10.0.22000-SP0
> [*] - AMD64 - Python-3.10.2
> [*]======================================================
> [*] - 严禁在墙内宣传本项目 -
> [*]======================================================
> [+]Start at 2022-01-29 13:56:38
> [+]Load Config file 'C:\Users\user\.mdc\config.ini'.
> [+]Enable debug
> [!]Enable soft link
> [!]CmdLine: -d0 -igp .
> [+]Main Working mode ## 1: Scraping ## , stop_counter=20
> [+]Find 1 movies.
> [*]======================================================
> [!]                - 100.% [1/1] -             13:56:38
> [!] [GDTM-012] As Number making data for 'Z:\t\GDTM-012.mp4'
> [+]select javbus
> [!]MP 进程[airavwiki]运行0.410秒，结束于13:56:42返回结果: どうやったらそんな格好に！？娘のあまりの寝相の悪さにビックリ！？しかし、その寝相の悪さのおかげで立派に成長した娘のおっぱいやお尻！さらにはマ○コまでが丸見え！父親としてここは我慢！と思いつつも柔らかそうなおっぱいとかわいい乳首！スケベなお尻に興奮が抑えられずについつい触ってしまい、キレイなマ○コは舐めてしまう父親失格の私に気付いた娘も興奮したのか禁断の近親相姦に！6組のイケない父娘セックス収録！
> [-]MP getOutline_xcity Error: list index out of range, number [GDTM-012].
> [!]MP 进程[xcity]运行1.370秒，结束于13:56:43返回结果: [空]
> [!]MP 进程[airav]运行1.641秒，结束于13:56:43返回结果: 怎麼衣服亂成這樣在睡啊！？女兒睡姿真欠幹！？奶子屁屁都成長到美味可口啊、只好趕快用肉棒來好好教訓她了！6組 亂倫父女幹砲！
> [!]MP 进程[avno1]运行2.444秒，结束于13:56:44返回结果: 怎么衣服乱成这样在睡啊！？女儿睡姿真欠幹！？奶子屁屁都成长到美味可口啊、只好赶快用肉棒来好好教训她了！6组 乱伦父女幹砲！
> [-]get_html_session() failed. HTTPSConnectionPool(host='www.amazon.co.jp', port=443): Max retries exceeded with url: /s?k=%E4%BD%95%E3%81%A7%E3%81%9D%E3%82%93%E3%81%AA%E3%82%B9%E3%82%B1%E3%83%99%E3%81%AA%E7%8A%B6%E6%85%8B%E3%81%A7%E5%AF%9D%E3%81%A6%E3%82%8B%E3%81%AE%EF%BC%81%EF%BC%9F%E5%AF%9D%E7%9B%B8%E3%81%AE%E6%82%AA%E3%81%84%E5%A8%98%E3%81%8C%E3%81%82%E3%82%89%E3%82%8C%E3%82%82%E3%81%AA%E3%81%84%E5%A7%BF%E3%81%A7%E5%AF%9D%E3%81%A6%E3%81%84%E3%81%9F%EF%BC%81%E7%88%B6%E3%81%A8%E3%81%97%E3%81%A6%E4%BA%BA%E3%81%A8%E3%81%97%E3%81%A6%E6%88%91%E6%85%A2%E3%81%97%E3%81%AA%E3%81%8F%E3%81%A6%E3%81%AF%E3%81%84%E3%81%91%E3%81%AA%E3%81%84%E3%81%AE%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A4%E3%81%84%E8%A7%A6%E3%81%A3%E3%81%A6%E3%81%97%E3%81%BE%E3%81%84%E2%80%A6 (Caused by ResponseError('too many 503 error responses'))
> [-]MP getOutline_amazon Error: cannot unpack non-iterable NoneType object, number [GDTM-012], title: 何でそんなスケベな状態で寝てるの！？寝相の悪い娘があられも ない姿で寝ていた！父として人として我慢しなくてはいけないのについつい触ってしまい…
> [!]MP 进程[amazon]运行7.564秒，结束于13:56:49返回结果: [空]
> [!]Storyline线程池模式运行5个任务共耗时(含启动开销)7.564秒，结束于13:56:49，[选 中avno1字数:60]，airav字数:60，airavwiki字数:199，xcity:空，amazon:空
> [+]Find movie [GDTM-012] metadata on website 'javbus'
> [+] ------- DEBUG INFO -------
> [+]  - actor          :
> [+]  - cover          : https://www.javbus.com/pics/cover/4k2i_b.jpg
> [+]  - director       : ロビーくん
> [+]  - extrafanart    : 19 links
> [+]  - imagecut       : 1
> [+]  - label          :
> [+]  - number         : GDTM-012
> [+]  - outline        : 60 characters
> [+]  - release        : 2014-12-05
> [+]  - runtime        : 240
> [+]  - series         :
> [+]  - source         : javbus.py
> [+]  - studio         : ゴールデンタイム
> [+]  - tag            : ['ゴールデンタイム', '4小时+', '乱伦', '企画', 'DMM独家', '高中生']
> [+]  - title          : 你怎么睡得这么淫荡！ ？？我的女儿，睡得不好，睡得没有冰 雹！作为一个人作为一个父亲，我不得不忍受它，但我只是碰了它......
> [+]  - website        : https://www.javbus.com/GDTM-012
> [+]  - original_title : 何でそんなスケベな状態で寝てるの！？寝相の悪い娘があられもない姿で寝ていた！父として人として我慢しなくてはいけないのについつい触ってしまい…
> [+]  - cover_small    :
> [+]  - actor_list     : ['']
> [+]  - trailer        :
> [+]  - naming_rule    : 你怎么睡得这么淫荡！ ？？我的女儿，睡得不好，睡得没有冰 雹！作为一个人作为一个父亲，我不得不忍受它，但我只是碰了它......
> [+] ------- DEBUG INFO -------
> [+]Image Downloaded! Z:\#JAV_output\#\[2014] 何でそんなスケベな状態で寝てるの！ ？寝相の悪い娘があられもない姿で寝ていた！父として人として我慢しなくてはいけないのについつい触ってしまい… [GDTM-012]\GDTM-012-fanart.jpg
> [+]Successfully downloaded 19 extrafanart to 'Z:\#JAV_output\#\[2014] 何でそんなスケベな状態で寝てるの！？寝相の悪い娘があられもない姿で寝ていた！父として人として我慢しなくてはいけないのについつい触ってしまい… [GDTM-012]\extrafanart'
> [!]Extrafanart download ThreadPool mode runtime 1.596s
> [+]Image Cutted!     Z:\#JAV_output\#\[2014] 何でそんなスケベな状態で寝てるの！ ？寝相の悪い娘があられもない姿で寝ていた！父として人として我慢しなくてはいけないのについつい触ってしまい… [GDTM-012]\GDTM-012-poster.jpg
> [+]Wrote!            Z:\#JAV_output\#\[2014] 何でそんなスケベな状態で寝てるの！ ？寝相の悪い娘があられもない姿で寝ていた！父として人として我慢しなくてはいけないのについつい触ってしまい… [GDTM-012]\GDTM-012.nfo
> [*]======================================================
> [+]Running time 0:00:12.847  End at 2022-01-29 13:56:51
> [+]All finished!!!
> ```

我的意思是，我只设置javdb和javbus，但是他好像也会去查这两个站点以外的站点。
至于访问问题，应该是我刮削太多了被黑名单了。

**Comment by lededev** [comment]
`[+]Find movie [GDTM-012] metadata on website 'javbus'`
日志中这一行就是使用的数据站点，你截图里正好用个黑框挡住了站点名称，除非站点名称不是你指定的那两个，才说明它找了指定之外的站点，看日志中是图片下载不下来，超时了。

**Comment by lededev** [comment]
截图最后一行Log file '文件路径.txt' saved，那个才是完整的日志，你截屏里有效信息太少，而且没开调试运行

**Comment by skypjsfly** [comment]
> 截图最后一行Log file '文件路径.txt' saved，那个才是完整的日志，你截屏里有效信息太少，而且没开调试运行

那个路径我没有映射出来，回头我再看看吧😄

**Comment by hejianjun** [comment]
javdb里面刮削不到剧情，所以会调用默认的剧情刮削工具storyline-switch设置为0就不会访问其他网站了
