### ISSUE TITLE
No longer able to load config.ini or operate on ramdisk drives

### ISSUE THREAD

**Issue by abtsh** [yoshiko2/Movie_Data_Capture#680]
## Version
`6.0.1`

## Platform
`Windows-10-10.0.22000-SP0`

## Description
No longer able to load config.ini or operate on ramdisk drives created via ImDisk.  
This is a known issue with [`pathlib`](https://bugs.python.org/issue31842) unable to work with ramdisks.  

## Reproduction
1. Create a ramdisk via [ImDisk 2.0.10](https://sourceforge.net/projects/imdisk-toolkit) (DeviceType=Auto, ImageFileAccess="Create virtual disk in physical memory")
2. Run `Movie_Data_Capture` with `config.ini` in the newly created ramdisk, and/or with `source_folder` set to the newly created ramdisk
3. Observe failure

## Since
https://github.com/yoshiko2/Movie_Data_Capture/commit/39ad0257603f734a812cea0a0ad2fe487b31b29b  

## References
https://bugs.python.org/issue31842
https://sourceforge.net/projects/imdisk-toolkit

## Logs
[mdc_20220126T012118_err.txt](https://github.com/yoshiko2/Movie_Data_Capture/files/7939347/mdc_20220126T012118_err.txt)
[mdc_20220126T012118.txt](https://github.com/yoshiko2/Movie_Data_Capture/files/7939348/mdc_20220126T012118.txt)

**Comment by lededev** [comment]
Format RAMDisk to exFAT or FAT32 file system, Python3 will work.
ImDisk is no longer maintenance anymore, and it lacks some important function implementation of NTFS.

**Comment by abtsh** [comment]
Also attempted OSFMount and exFAT and they seem to fail the same way.  
FAT32 volumes function correctly, but that filesystem limits the maximum file size to 4GB.  
![exfat](https://user-images.githubusercontent.com/98447218/151406838-5772d49b-a50e-43fa-af7f-a51a20835410.png)  

Is this workflow no longer supported?

**Comment by lededev** [comment]
[ImDisk Toolkit](https://sourceforge.net/projects/imdisk-toolkit/) can Format RAM disk into exFAT file system, when Windows OS startup.

**Comment by lededev** [comment]
I am pretty sure exFAT ImDisk RAM disk support python 3 pathlib.Path.reslove()

**Comment by abtsh** [comment]
I could not seem to make it work. Am I missing something?
![exfat_imdisk](https://user-images.githubusercontent.com/98447218/151646668-fddde3dc-4b6b-4ef6-b35d-00a48257a23e.png)

**Comment by lededev** [comment]
That caused by Python 3.8's pathlib which did not fixed a bug.
git checkout the latest mdc source code
```
git checkout https://github.com/yoshiko2/Movie_Data_Capture.git
cd Movie_Data_Capture
```
install Python 3.10.2 for windows x64
run from powershell `pip install -r requirements.txt`
`pip install pyinstaller`
and run `.\py_to_exe.ps1` in source code directory, to build a exe file with the lastest pathlib bug fixed.

**Comment by lededev** [comment]
by the way, keep config.ini and excutable file in RAM disk is not a good idea, you can put exe file to any dir in PATH, and can also rename it to shorter form like mdc.exe.
delet config.ini and run mdc command in cmd or powershell, it can create config file in you user profile dir.
and run `mdc -p r:/` any where, if current dir no config.ini file, program will find config file in dir list
```
            Path.home() / "mdc.ini",
            Path.home() / ".mdc.ini",
            Path.home() / ".mdc/config.ini",   # mdc.exe will prompt create config file here if nothing be found
            Path.home() / ".config/mdc/config.ini"

```

**Comment by abtsh** [comment]
Using python 3.10.2 does resolve the issue.  
Do you have an estimate on when the mainstream's python version will be updated?

**Comment by lededev** [comment]
I'm not the owner of this project and I think the mainstream remains in Python 3.8 as some devices still lack support for Python 3.10.

**Comment by abtsh** [comment]
Manually repackaging with Python 3.10 is more of a workaround I suppose. 
Though I agree, given the small # of use-cases affected, it might not be worth the effort to push for a project-wise python upgrade. 

I assume this would probably be "won't fix" in the mainstream then.
