### ISSUE TITLE
Win10环境下硬连接视频无法刮削

### ISSUE THREAD

**Issue by holyluna620** [yoshiko2/Movie_Data_Capture#684]
当前软件版本：6.0.1
问题描述：在win10环境下，以模式1对win下创建的硬连接文件进行刮削时，无法识别相应的视频文件。
问题举例以及截图：
对于创建出的硬连接文件”IPZ-628-C.mp4“为例，
以模式1进行刮削时：
![01](https://user-images.githubusercontent.com/98998343/152467099-13b09660-e0b7-49a9-8e6d-b0b5e8fc85d6.jpg)
以模式3进行刮削时：
![02](https://user-images.githubusercontent.com/98998343/152467102-367ea36a-dbf6-4288-9b95-61ee184d363b.jpg)
文件的连接属性：
![03](https://user-images.githubusercontent.com/98998343/152467270-bc982b36-945f-41f2-9c84-5c8243feb075.jpg)

**Comment by holyluna620** [comment]
对应的config.ini文件
`# 详细教程请看
# - https://github.com/yoshiko2/Movie_Data_Capture/wiki#%E9%85%8D%E7%BD%AEconfigini
[common]
main_mode=1
source_folder=./
failed_output_folder=failed
success_output_folder=JAV_output
soft_link=0
failed_move=1
auto_exit=0
transalte_to_sc=0
multi_threading=0
;actor_gender value: female(♀) or male(♂) or both(♀ ♂) or all(♂ ♀ ⚧)
actor_gender=female
del_empty_folder=1
; 跳过最近(默认:30)天新修改过的.NFO，可避免整理模式(main_mode=3)和软连接(soft_link=0)时
; 反复刮削靠前的视频文件，0为处理所有视频文件
nfo_skip_days=0
; 处理完多少个视频文件后停止，0为处理所有视频文件
stop_counter=0
; 以上两个参数配合使用可以以多次少量的方式刮削或整理数千个文件而不触发翻译或元数据站封禁
ignore_failed_list=0
download_only_missing_images=1
mapping_table_validity=7

[proxy]
;proxytype: http or socks5 or socks5h switch: 0 1
switch=1
type=http
proxy=127.0.0.1:10080
timeout=10
retry=3
cacert_file=

[Name_Rule]
location_rule=actor+'/'+number
naming_rule=number+'-'+title
max_title_len=50

[update]
update_check=1

[priority]
website=javbus,airav,fanza,xcity,javdb,mgstage,fc2,avsox,dlsite,carib,fc2club

[escape]
literals=\()/
folders=failed,JAV_output

[debug_mode]
switch=0

; 机器翻译
[transalte]
switch=0
;可选项 google-free,azure
engine=google-free
; azure翻译密钥
key=
; 翻译延迟
delay=1
values=title,outline
service_site=translate.google.cn

; 预告片
[trailer]
switch=0

; 用来确定是否是无码
[uncensored]
uncensored_prefix=S2M,BT,LAF,SMD,SMBD,SM3D2DBD,SKY-,SKYHD,CWP,CWDV,CWBD,CW3D2DBD,MKD,MKBD,MXBD,MK3D2DBD,MCB3DBD,MCBD,RHJ,MMDV

[media]
; 影片后缀
media_type=.mp4,.avi,.rmvb,.wmv,.mov,.mkv,.flv,.ts,.webm,.iso,.mpg,.m4v
; 字幕后缀
sub_type=.smi,.srt,.idx,.sub,.sup,.psb,.ssa,.ass,.txt,.usf,.xss,.ssf,.rt,.lrc,.sbv,.vtt,.ttml

; 水印
[watermark]
switch=1
water=2
; 左上 0, 右上 1, 右下 2， 左下 3

; 剧照
[extrafanart]
switch=1
parallel_download=5
extrafanart_folder=extrafanart

; 剧情简介
[storyline]
switch=1
; website为javbus javdb avsox xcity carib时，site censored_site uncensored_site 为获取剧情简介信息的
; 可选数据源站点列表。列表内站点同时并发查询，取值优先级由冒号前的序号决定，从小到大，数字小的站点没数据才会采用后面站点获得的。
; 其中airavwiki airav avno1 58avgo是中文剧情简介，区别是airav只能查有码，avno1 airavwiki 有码无码都能查，
; 58avgo只能查无码或者流出破解马赛克的影片(此功能没使用)。
; xcity和amazon是日语的，由于amazon商城没有番号信息，选中对应DVD的准确率仅99.6%。如果三个列表全部为空则不查询，
; 设置成不查询可大幅提高刮削速度。
; site=
site=1:avno1,4:airavwiki
censored_site=2:airav,5:xcity,6:amazon
uncensored_site=3:58avgo
; 运行模式：0:顺序执行(最慢) 1:线程池(默认值) 2:进程池(启动开销比线程池大，并发站点越多越快)
run_mode=1
; show_result剧情简介调试信息 0关闭 1简略 2详细(详细部分不记入日志)，剧情简介失效时可打开2查看原因
show_result=0

; 繁简转换 繁简转换模式mode=0:不转换 1:繁转简 2:简转繁
[cc_convert]
mode=1
vars=outline,series,studio,tag,title

[javdb]
sites=33,34`

**Comment by lededev** [comment]
参考 https://github.com/yoshiko2/Movie_Data_Capture/issues/635

**Comment by holyluna620** [comment]
> 参考 #635

谢谢你的答复！

期望增加一个开关功能。

**Comment by lededev** [comment]
> > 参考 #635
> 
> 谢谢你的答复！
> 
> 期望增加一个开关功能。

你这个需求不典型，如确有需要请自行修改代码增加开关，并提交PR。
