### ISSUE TITLE
[Bug] 当naming_rule配置中有tag命名参数时，会发生TypeError:can only concatenate str (not "list") to str

### ISSUE THREAD

**Issue by sastar** [yoshiko2/Movie_Data_Capture#685]
当前版本：[ece2ee4](https://github.com/yoshiko2/Movie_Data_Capture/commit/ece2ee451c56ae8e7abf6743a2ca288e44b01ebb)
问题描述：在配置参数naming_rule中加入tag命名参数，会发生TypeError错误
举例：以javdb为数据源，番号为lulu-007
问题点发生在https://github.com/yoshiko2/Movie_Data_Capture/blob/ece2ee451c56ae8e7abf6743a2ca288e44b01ebb/WebCrawler/__init__.py#L329
json_data中tag参数为list，naming_rule为str，所以发生错误
![image](https://user-images.githubusercontent.com/35725622/152631472-4c22cef0-ea61-491f-ab12-73d6f58d5f63.png)

**Comment by hejianjun** [comment]
忘记加str转换了，我感觉你需要提交pull request
