### ISSUE TITLE
搜刮到了内容但是gbk编码问题，希望尽快修复下

### ISSUE THREAD

**Issue by xinmans** [yoshiko2/Movie_Data_Capture#687]
[!] [112117-010] As Number making data for '\\\Caribbean-112117-010\Caribbean-112117-010.mp4'
[-]Connect retry 1/3
[+]Find movie [112117-010] metadata on website 'carib'
[+]Image Downloaded! [-] [\\Caribbean-112117-010\Caribbean-112117-010.mp4] ERROR:
[-] 'gbk' codec can't encode character '\u301c' in position 32: illegal multibyte sequence
'[-]Move to Failed output folder, see '\failed\where_was_i_before_being_moved.txt'

$ ./AV_Data_Capture.exe -v
5.0.2

**Comment by xinmans** [comment]
解决 办法：增加 encoding = ‘utf-8’

**Comment by xinmans** [comment]
$ grep gbk * |uniq
avdc_20220205T172307_err.txt:UnicodeEncodeError: 'gbk' codec can't encode character '\u301c' in position 84: illegal multibyte sequence
avdc_20220205T172449.txt:[-] 'gbk' codec can't encode character '\u301c' in position 44: illegal multibyte sequence
avdc_20220205T172449.txt:[-] 'gbk' codec can't encode character '\u301c' in position 32: illegal multibyte sequence
avdc_20220205T172449.txt:[-] 'gbk' codec can't encode character '\u301c' in position 31: illegal multibyte sequence
avdc_20220205T172449.txt:[-] 'gbk' codec can't encode character '\u301c' in position 32: illegal multibyte sequence
avdc_20220205T172449.txt:[-] 'gbk' codec can't encode character '\u2665' in position 51: illegal multibyte sequence
avdc_20220205T172449.txt:[-] 'gbk' codec can't encode character '\u2665' in position 72: illegal multibyte sequence
avdc_20220205T172449.txt:[-] 'gbk' codec can't encode character '\u2661' in position 61: illegal multibyte sequence
avdc_20220205T172449.txt:[-] 'gbk' codec can't encode character '\xa0' in position 79: illegal multibyte sequence
avdc_20220205T172449.txt:[-] 'gbk' codec can't encode character '\u2216' in position 76: illegal multibyte sequence
avdc_20220205T172449_err.txt:UnicodeEncodeError: 'gbk' codec can't encode character '\u30fb' in position 100: illegal multibyte sequence
avdc_20220205T173018.txt:[-] 'gbk' codec can't encode character '\xa0' in position 79: illegal multibyte sequence
avdc_20220205T173018.txt:[-] 'gbk' codec can't encode character '\u2216' in position 76: illegal multibyte sequence
avdc_20220205T173018.txt:[-] 'gbk' codec can't encode character '\u30fb' in position 60: illegal multibyte sequence
avdc_20220205T173018.txt:[-] 'gbk' codec can't encode character '\u30fb' in position 81: illegal multibyte sequence
avdc_20220205T173018.txt:[-] 'gbk' codec can't encode character '\u30fb' in position 60: illegal multibyte sequence
avdc_20220205T173018.txt:[-] 'gbk' codec can't encode character '\u30fb' in position 15: illegal multibyte sequence
avdc_20220205T173018.txt:[-] 'gbk' codec can't encode character '\ua789' in position 47: illegal multibyte sequence
avdc_20220205T173018.txt:[-] 'gbk' codec can't encode character '\ua789' in position 44: illegal multibyte sequence
avdc_20220205T173018.txt:[-] 'gbk' codec can't encode character '\ua789' in position 48: illegal multibyte sequence
avdc_20220205T173018.txt:[-] 'gbk' codec can't encode character '\ua789' in position 72: illegal multibyte sequence
avdc_20220205T173018_err.txt:UnicodeEncodeError: 'gbk' codec can't encode character '\ua789' in position 112: illegal multibyte sequence
avdc_20220205T180659_err.txt:UnicodeEncodeError: 'gbk' codec can't encode character '\ua789' in position 112: illegal multibyte sequence
avdc_20220205T180939.txt:[-] 'gbk' codec can't encode character '\u301c' in position 50: illegal multibyte sequence
avdc_20220205T180939.txt:[-] 'gbk' codec can't encode character '\u301c' in position 63: illegal multibyte sequence
avdc_20220205T180939.txt:[-] 'gbk' codec can't encode character '\u301c' in position 64: illegal multibyte sequence
avdc_20220205T180939.txt:[-] 'gbk' codec can't encode character '\u301c' in position 54: illegal multibyte sequence
avdc_20220205T180939.txt:[-] 'gbk' codec can't encode character '\u301c' in position 59: illegal multibyte sequence
avdc_20220205T180939.txt:[-] 'gbk' codec can't encode character '\u30fb' in position 60: illegal multibyte sequence
avdc_20220205T180939.txt:[-] 'gbk' codec can't encode character '\ua789' in position 36: illegal multibyte sequence
avdc_20220205T180939.txt:[-] 'gbk' codec can't encode character '\ua789' in position 40: illegal multibyte sequence
avdc_20220205T180939.txt:[-] 'gbk' codec can't encode character '\ua789' in position 62: illegal multibyte sequence
avdc_20220205T180939.txt:[-] 'gbk' codec can't encode character '\ua789' in position 42: illegal multibyte sequence
avdc_20220205T180939.txt:[-] 'gbk' codec can't encode character '\ua789' in position 40: illegal multibyte sequence
avdc_20220205T180939.txt:[-] 'gbk' codec can't encode character '\ua789' in position 60: illegal multibyte sequence
avdc_20220205T180939.txt:[-] 'gbk' codec can't encode character '\u30fb' in position 34: illegal multibyte sequence
avdc_20220205T191209.txt:[-] 'gbk' codec can't encode character '\u301c' in position 53: illegal multibyte sequence
avdc_20220205T191209.txt:[-] 'gbk' codec can't encode character '\u301c' in position 55: illegal multibyte sequence
avdc_20220205T191209.txt:[-] 'gbk' codec can't encode character '\u2216' in position 53: illegal multibyte sequence
avdc_20220205T191209.txt:[-] 'gbk' codec can't encode character '\u301c' in position 54: illegal multibyte sequence
avdc_20220205T191209.txt:[-] 'gbk' codec can't encode character '\u301c' in position 51: illegal multibyte sequence
avdc_20220205T191209.txt:[-] 'gbk' codec can't encode character '\u301c' in position 54: illegal multibyte sequence
avdc_20220205T191209.txt:[-] 'gbk' codec can't encode character '\u30fb' in position 26: illegal multibyte sequence
avdc_20220205T191209.txt:[-] 'gbk' codec can't encode character '\ua789' in position 41: illegal multibyte sequence
avdc_20220205T191209.txt:[-] 'gbk' codec can't encode character '\ua789' in position 45: illegal multibyte sequence

**Comment by xinmans** [comment]
一大堆片假名解析不了

**Comment by xinmans** [comment]
正波浪线“～” 编码为\u301c

**Comment by lededev** [comment]
这个是你的运行环境的问题吧，如果在Linux下运行，需要设置语言环境为:
```
LANG=zh_CN.UTF8
LC_CTYPE=zh_CN.UTF-8

```

**Comment by lededev** [comment]
另外请用最新版本测试并反馈，你的5.0.2也太早了一点吧，现在是6.0.1，很快又要更新版本了。
