### ISSUE TITLE
人脸识别图片裁切问题

### ISSUE THREAD

**Issue by ifunboy** [yoshiko2/Movie_Data_Capture#690]
最新的人脸识别功能很棒，但在使用中发现以下问题。

1. core.py 第387行
`img2 = img.crop(0, 0, width, cropBottom)`
缺括号，应为
`img2 = img.crop((0, 0, width, cropBottom))`

2. 使用javdb,fc2等搜刮fc2，xxx-av系列时无法裁切封面。
建议加入全局裁切封面选项（imagecut=1）

3. 希望加入翻译失败、封面图裁切失败移动到failed文件夹选项

**Comment by hejianjun** [comment]
这边我看到错误了，等会儿重新推送一下修改bug的代码

**Comment by hejianjun** [comment]
> 最新的人脸识别功能很棒，但在使用中发现以下问题。
> 
> 1. core.py 第387行
>    `img2 = img.crop(0, 0, width, cropBottom)`
>    缺括号，应为
>    `img2 = img.crop((0, 0, width, cropBottom))`
> 2. 使用javdb,fc2等搜刮fc2，xxx-av系列时无法裁切封面。
>    建议加入全局裁切封面选项（imagecut=1）
> 3. 希望加入翻译失败、封面图裁切失败移动到failed文件夹选项

https://github.com/yoshiko2/Movie_Data_Capture/pull/692
