### ISSUE TITLE
请问最新加入的人脸识别裁剪功能后，程序报错。

### ISSUE THREAD

**Issue by jerryluo2022** [yoshiko2/Movie_Data_Capture#691]
actor+'/'+number
[+]Image Downloaded! JAV_output\多人作品\GAS-471\GAS-471-fanart.jpg
[+]Successfully downloaded 20 extrafanart to 'JAV_output\多人作品\GAS-471\extrafanart'
[!]Extrafanart download ThreadPool mode runtime 7.306s
[+]Use model         hog
[-]Model found face  JAV_output\多人作品\GAS-471\GAS-471-fanart.jpg
**ERROR:root:No module named 'dlib'**
[+]Image Cutted!     JAV_output\多人作品\GAS-471\GAS-471-poster.jpg
[+]Wrote!            JAV_output\多人作品\GAS-471\GAS-471.nfo
[*]======================================================

提示： ERROR:root:No module named 'dlib' 
不知道是什么原因？

**Comment by hejianjun** [comment]
没有安装`dlib`人脸识别库

**Comment by hejianjun** [comment]
> actor+'/'+number [+]Image Downloaded! JAV_output\多人作品\GAS-471\GAS-471-fanart.jpg [+]Successfully downloaded 20 extrafanart to 'JAV_output\多人作品\GAS-471\extrafanart' [!]Extrafanart download ThreadPool mode runtime 7.306s [+]Use model hog [-]Model found face JAV_output\多人作品\GAS-471\GAS-471-fanart.jpg **ERROR:root:No module named 'dlib'** [+]Image Cutted! JAV_output\多人作品\GAS-471\GAS-471-poster.jpg [+]Wrote! JAV_output\多人作品\GAS-471\GAS-471.nfo [*]======================================================
> 
> 提示： ERROR:root:No module named 'dlib' 不知道是什么原因？

如果使用Anaconda3 可以使用`conda install -c conda-forge face_recognitio`快速安装
没有的话需要编译安装`https://github.com/ageitgey/face_recognition`

**Comment by hejianjun** [comment]
linux下的同学可以使用`pip install -r requirement.txt`执行环境安装

**Comment by neatgz** [comment]
6.0.2 版本还会在 release 里 放出 编译好的 windows 版吗？谢谢
