### ISSUE TITLE
Windows使用已编译程序可以连接代理刮削，但使用源码时无法通过代理连接网络

### ISSUE THREAD

**Issue by kglife** [yoshiko2/Movie_Data_Capture#696]
Windows使用已编译程序可以连接代理刮削，但使用源码时无法通过代理连接网络

失败日志
[*]================= Movie Data Capture =================
[*]                        6.0.1                         
[*]======================================================
[*] - Windows-10-10.0.19041-SP0 
[*] - AMD64 - Python-3.9.6
[*]======================================================
[*] - 严禁在墙内宣传本项目 - 
[*]======================================================
[+]Start at 2022-02-14 16:08:26
[+]Load Config file 'D:\DATA\Downloads\Movie_Data_Capture-6.0.1\config.ini'.
[+]Enable debug
[+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/yoshiko2/Movie_Data_Capture/releases/latest (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
[-]Connect Failed! Please check your Proxy or Network!
[-]Failed to update! Please check new version manually:
[-] https://github.com/yoshiko2/Movie_Data_Capture/releases
[*]======================================================
[+]Find 1 movies.
[*]======================================================
[!]                - 100.% [1/1] -             16:08:26
[!] [IPX-580] As Number making data for 'D:\DATA\Downloads\Movie_Data_Capture-6.0.1\IPX-580.mp4'
[+]select javdb
[!]javdb:select site javdb36
[-]get_html_by_scraper() failed. HTTPSConnectionPool(host='javdb36.com', port=443): Max retries exceeded with url: /search?q=IPX-580&f=all (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))
cannot unpack non-iterable NoneType object
[-]Movie number has changed! [IPX-580]->[None]
[*]======================================================
[+]Deleting empty folder D:\DATA\Downloads\Movie_Data_Capture-6.0.1\failed
[+]Running time 0:00:06.230  End at 2022-02-14 16:08:32
[+]All finished!!!

成功日志
[*]================= Movie Data Capture =================
[*]                        6.0.1                         
[*]======================================================
[*] - Windows-10-10.0.19041-SP0 
[*] - AMD64 - Python-3.8.10
[*]======================================================
[*] - 严禁在墙内宣传本项目 - 
[*]======================================================
[+]Start at 2022-02-14 16:02:06
[+]Load Config file 'D:\DATA\Documents\Movie_Data_Capture-CLI-6.0.1-Windows-amd64\config.ini'.
[+]Enable debug
[+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30
[+]Find 1 movies.
[*]======================================================
[!]                - 100.% [1/1] -             16:02:06
[!] [IPX-580] As Number making data for 'D:\DATA\Documents\Movie_Data_Capture-CLI-6.0.1-Windows-amd64\ipx-580.mp4'
[+]select javdb
[!]javdb:select site javdb35
[!]MP 进程[airavwiki]运行0.304秒，结束于16:02:07返回结果: 【高画質機材による圧倒的映像美・圧倒的なエロスを再現！】楓カレンが長い禁欲を解いた日、体液を絡ませ子宮のウズきが鎮まるまで交尾し続けた3日間の記録。（1日目）汗を流し本能剥き出しで没頭した激イキ交尾（2日目）マゾに堕ちて潮吹き痙攣絶頂SEX（3日目）ひと時もチンポを離さない快楽貪り追撃性交…。綺麗な顔は乱れ、激しい高揚は「脳イキ」に達する。美しく卑猥にひたすらヤリまくった超絶アクメ72時間。
[!]MP 进程[avno1]运行0.584秒，结束于16:02:08返回结果: 枫可憐长期禁欲后解禁的日子，持续体液交络做爱的3日间纪录！千万别错过！
[-]MP getOutline_xcity Error: list index out of range, number [IPX-580].
[!]MP 进程[xcity]运行1.191秒，结束于16:02:08返回结果: [空]
[!]MP 进程[airav]运行1.491秒，结束于16:02:09返回结果: 楓可憐長期禁欲後解禁的日子，持續體液交絡做愛的3日間紀錄！千萬別錯過！
[!]MP 进程[amazon]运行3.781秒，结束于16:02:11返回结果: [空]
[!]Storyline线程池模式运行5个任务共耗时(含启动开销)4.095秒，结束于16:02:11，[选中avno1字数:35]，airav字数:35，airavwiki字数:197，xcity:空，amazon:空
[+]Find movie [IPX-580] metadata on website 'javdb'

请问博主知道可能是什么原因导致吗？

**Comment by hejianjun** [comment]
```
[update]
update_check=1
```
修改`update_check`未2

**Comment by kglife** [comment]
> 改为2的话会报错，但改为0实际上只是跳过更新检查，但实际仍无法调用代理

[update]
update_check=1

**Comment by hejianjun** [comment]
说错了做另一个项目习惯了，检查你的代理服务
