### ISSUE TITLE
能教一下如何打包程式碼成exe?

### ISSUE THREAD

**Issue by jason22432150** [yoshiko2/Movie_Data_Capture#700]
我用 pyinstaller -F Movie_Data_Capture.py 打包除來的exe會出現閃退
![image](https://user-images.githubusercontent.com/52876522/154785789-5129cbfc-32fa-4ccd-bddf-7b57edb713a2.png)

**Comment by lededev** [comment]
方法不对，照这个步骤做。
https://github.com/yoshiko2/Movie_Data_Capture/issues/680#issuecomment-1024831480
