### ISSUE TITLE
Fatal error! Can not make folder

### ISSUE THREAD

**Issue by walk728** [yoshiko2/Movie_Data_Capture#705]
[-]Fatal error! Can not make folder 'JAV_output/長谷川しずく,倉木みお,朝倉ことみ,小嶋ジュンナ,琥珀うた,北川瞳,仁科百華,朝田ばなな,吉田花,大堀香奈,桜花えり,雫パイン,つくし（大沢つくし）,みづなれい（みずなれい）,つぼみ,あざみねね/MIRD-098'

检查了下，是有的演员太多，文件夹名字太长，创建失败，希望限制下创建文件夹的字数

**Comment by lededev** [comment]
https://github.com/yoshiko2/Movie_Data_Capture/wiki#%E8%AE%BE%E7%BD%AE%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9B%AE%E5%BD%95%E5%92%8C%E5%BD%B1%E7%89%87%E9%87%8D%E5%91%BD%E5%90%8D%E8%A7%84%E5%88%99%E6%A0%87%E9%A2%98%E6%9C%80%E9%95%BF%E5%AD%97%E7%AC%A6%E6%95%B0%E8%AE%BE%E7%BD%AE
