### ISSUE TITLE
Emby 分集片名(例xxx-cd1.xxx xxx-cd2.xxx)劇照無法顯示，劇照檔名修改方式。

### ISSUE THREAD

**Issue by liteliu** [yoshiko2/Movie_Data_Capture#708]
Core.py  第657行底下修改與下相同
    # main_mode
    #  1: 刮削模式 / Scraping mode
    #  2: 整理模式 / Organizing mode
    #  3：不改变路径刮削
    if conf.main_mode() == 1:
        # 创建文件夹
        path = create_folder(json_data)
        if multi_part == 1:
            number += part  # 这时number会被附加上CD1后缀

            fanart_path = f"{number}{leak_word}{c_word}{hack_word}-fanart{ext}"
            poster_path = f"{number}{leak_word}{c_word}{hack_word}-poster{ext}"
            thumb_path = f"{number}{leak_word}{c_word}{hack_word}-thumb{ext}"

Core.py  原第705行底下修改與下相同
    elif conf.main_mode() == 3:
        path = str(Path(file_path).parent)
        if multi_part == 1:
            number += part  # 这时number会被附加上CD1后缀

            fanart_path = f"{number}{leak_word}{c_word}{hack_word}-fanart{ext}"
            poster_path = f"{number}{leak_word}{c_word}{hack_word}-poster{ext}"
            thumb_path = f"{number}{leak_word}{c_word}{hack_word}-thumb{ext}"

**Comment by diannei** [comment]
这种其实不用修改。把“-CD1”删掉就可以。例如xxxx-010，xxxx-010-CD2
