### ISSUE TITLE
FC2刮削出现乱码的情况

### ISSUE THREAD

**Issue by chengc630** [yoshiko2/Movie_Data_Capture#721]
版本：6.0.2 系统：windows10
![image](https://user-images.githubusercontent.com/14369791/156924643-bedffbca-2956-44e8-b68c-ecd1dfdd8d3a.png)
怎么可以让编码格式正确呢

**Comment by lededev** [comment]
fc2club我这里根本连不上，我从配置文件里已经将之去掉了

**Comment by chengc630** [comment]
这个应该是用fc2刮出来的，我fc2club用chrome能连上，但是工具里面也连不上。

**Comment by lededev** [comment]
修了乱码问题[commit](https://github.com/yoshiko2/Movie_Data_Capture/pull/720/commits/b6786ef9d71df32ca245f08cf6e259096e58d5f8)，等编译完成生成exe以后可以去Action下载一份试试。

**Comment by chengc630** [comment]
thx！
