### ISSUE TITLE
有些番号有多个结果，如何选择想要的结果？

### ISSUE THREAD

**Issue by colaKot** [yoshiko2/Movie_Data_Capture#724]
比如MIDV-010  
手动指定番号
-n或--number
如果遇到番号比较奇葩的影片，同时存在于可刮削的网站，可用输入以下

Movie_Data_Capture xxxxxxxx.mp4 -n xxxxxxxx 
这个最后的 xXXXXXXX是什么意思？

**Comment by lededev** [comment]
配置文件只设置一个网站，就能得到单一结果，或者得不到结果。
```ini
[priority]
website=
```

**Comment by hecheng337** [comment]
我估计这位朋友也碰到 #664 这个问题了

MOODYZ 的新番号 MIDV 和十多年前的某个系列冲突了，导致大部分网站爬取的结果不匹配
类似的情况还发生在 GS-416 上。
我觉得增加额外的检查/允许手动指定实际搜索的编号还是很有必要的

MIDV的问题可以暂时只用 fanza 搜索来避免

**Comment by lededev** [comment]
你觉得有必要你就做
