### ISSUE TITLE
【建议】使用Nuitka打包，更换掉pyinstaller，效率更高，体积更小

### ISSUE THREAD

**Issue by tinyboxxx** [yoshiko2/Movie_Data_Capture#726]
参见：
https://pypi.org/project/Nuitka/

**Comment by yoshiko2** [comment]
目前需要找到支持静态链接的封装器 而且带人脸识别的二进制包体积小不了

**Comment by lededev** [comment]
@yoshiko2 现在KODI竖版封面和横板封面都能支持了，在我看来封面裁剪和人脸识别都没什么必要了，直接原始封面就能用，就是不知道其它软件的支持度如何。
