### ISSUE TITLE
更新模式下仍然下载了封面

### ISSUE THREAD

**Issue by SanaeMio** [yoshiko2/Movie_Data_Capture#729]
当前软件版本：6.0.2
问题描述：已设置main_mode=3和download_only_missing_images=1，但是发现刮削后仍然额外下载了poster.jpg覆盖了原有封面文件，对于已手工处理过封面但只想更新下nfo内翻译的场景不太友好，望优化

**Comment by lededev** [comment]
贴份可重现这个bug的日志我可以调试一下看看

**Comment by SanaeMio** [comment]
> 贴份可重现这个bug的日志我可以调试一下看看

日志如下，原本文件夹里已经存在了以前手动处理过的poster.jpg，但本次更新后再次下载了封面并覆盖了原有文件。
另：版本号实际是6.0.2，可能是作者上次发布忘了改。
辛苦大佬调试，感谢

[*]================= Movie Data Capture =================
[*]                        6.0.1                         
[*]======================================================
[*] - Windows-10-10.0.18363-SP0 
[*] - AMD64 - Python-3.8.10
[*]======================================================
[*] - 严禁在墙内宣传本项目 - 
[*]======================================================
[+]Start at 2022-03-26 23:22:59
[+]Load Config file '\\sanaemio-nas\Video\Other\emmmm\NORMAL\七海ティナ\config.ini'.
[+]Main Working mode ## 3: Scraping in analysis folder ## , nfo_skip_days=30
[*]                 * New update 6.0.2 *                 
[*]                     ↓ Download ↓                     
[*]https://github.com/yoshiko2/Movie_Data_Capture/releases
[*]======================================================
[+]Find 1 movies.
[*]======================================================
[!]                - 100.% [1/1] -             23:23:01
[!] [STARS-210] As Number making data for '\\sanaemio-nas\Video\Other\emmmm\NORMAL\七海ティナ\STARS-210 ヤリたい放題いいなり調教イカセダンジョン-七海ティナ 2020-03-10\STARS-210.mp4'
[+]Find movie [STARS-210] metadata on website 'javbus'
[+]Image Cutted!     \\sanaemio-nas\Video\Other\emmmm\NORMAL\七海ティナ\STARS-210 ヤリたい放題いいなり調教イカセダンジョン-七海ティナ 2020-03-10\STARS-210-poster.jpg
[+]Wrote!            \\sanaemio-nas\Video\Other\emmmm\NORMAL\七海ティナ\STARS-210 ヤリたい放題いいなり調教イカセダンジョン-七海ティナ 2020-03-10\STARS-210.nfo
[*]======================================================
[+]Deleting empty folder \\sanaemio-nas\Video\Other\emmmm\NORMAL\七海ティナ\failed
[+]Running time 0:00:21.826  End at 2022-03-26 23:23:21
[+]All finished!!!

**Comment by lededev** [comment]
读了你的日志，更新模式下确实没有下载封面，你这个ISSUE的标题与事实不符。
然而为什么你的封面被改变了呢，这个虽然与下载无关，但也是事实。
日志里显示，封面经过了裁剪，就是这一行。
`[+]Image Cutted! \sanaemio-nas\Video\Other\emmmm\NORMAL\七海ティナ\STARS-210 ヤリたい放題いいなり調教イカセダンジョン-七海ティナ 2020-03-10\STARS-210-poster.jpg`
裁剪这个工序，是以下载的封面为原材料，我用你这个番号，做了一次模式3的封面fanart下载，日志如下
`[+]Image Downloaded! Z:\test\STARS-210-fanart.jpg`
再次运行模式3 `mdc.exe -d0 -m3 -p z:\test\`，不会有这一行，因为我设置了`download_only_missing_images=1`，不会重复下载。
然而裁剪会用fanart生成一份poster，可能是复制，也可能是纵幅切割成横幅，可能你手工处理过的封面，只处理了poster图片，fanart还是原先默认下载低质量版本的。
因此裁剪就用低质量的fanart图片对你处理过的poster图片进行了覆盖，出现你现在的效果。

如何解决。用处理过的poster图片覆盖一遍对应的fanart图片就行了。自己写个简单脚本，搜索全部*-poster.jpg，复制到对应的*-fanart.jpg即可。如果数量不多，手工完成也行。

**Comment by SanaeMio** [comment]
> 读了你的日志，更新模式下确实没有下载封面，你这个ISSUE的标题与事实不符。 然而为什么你的封面被改变了呢，这个虽然与下载无关，但也是事实。 日志里显示，封面经过了裁剪，就是这一行。 `[+]Image Cutted! \sanaemio-nas\Video\Other\emmmm\NORMAL\七海ティナ\STARS-210 ヤリたい放題いいなり調教イカセダンジョン-七海ティナ 2020-03-10\STARS-210-poster.jpg` 裁剪这个工序，是以下载的封面为原材料，我用你这个番号，做了一次模式3的封面fanart下载，日志如下 `[+]Image Downloaded! Z:\test\STARS-210-fanart.jpg` 再次运行模式3 `mdc.exe -d0 -m3 -p z:\test\`，不会有这一行，因为我设置了`download_only_missing_images=1`，不会重复下载。 然而裁剪会用fanart生成一份poster，可能是复制，也可能是纵幅切割成横幅，可能你手工处理过的封面，只处理了poster图片，fanart还是原先默认下载低质量版本的。 因此裁剪就用低质量的fanart图片对你处理过的poster图片进行了覆盖，出现你现在的效果。
> 
> 如何解决。用处理过的poster图片覆盖一遍对应的fanart图片就行了。自己写个简单脚本，搜索全部*-poster.jpg，复制到对应的*-fanart.jpg即可。如果数量不多，手工完成也行。

感谢解答，看到您的说明我也理解了现在为什么会出现覆盖封面的情况，与我开始理解的情况稍有不同。
之前我手工处理封面是因为类似STARS-* 这一类番号的封面下载下来基本都是横向的，软件裁剪为纵向之后大部分情况下都没落到正确的位置，所以我手动去网上找了纵向的封面替换掉了自动裁剪的封面（我是plex用户，都是纵向封面）。
能否增加一个开关控制是否裁剪封面？因为我目前需求也只是想更新nfo内的简介和标签/流派，图片类的并不想重新处理。因数量较多，需要逐一排查封面是否被覆盖掉了，工作量较大暂时没敢批量更新处理，所以来提了这个ISSUE，如果能考虑控制裁剪封面那就帮大忙了。。

**Comment by lededev** [comment]
对裁剪功能进行了修改，设置了`download_only_missing_images=1`的情况下，如果裁剪后的图片已经存在，不进行再次裁剪。
一会自动生成完成后，你可以到Action下载一份试试。

**Comment by SanaeMio** [comment]
> 对裁剪功能进行了修改，设置了`download_only_missing_images=1`的情况下，如果裁剪后的图片已经存在，不进行再次裁剪。 一会自动生成完成后，你可以到Action下载一份试试。

已验证，问题解决，非常感谢！

**Comment by lededev** [comment]
只更新.NFO，速度比较快，请求过多容易被封IP，建议用脚本、crontab或计划任务运行，用`-c`参数或配置文件`stop_counter=`控制每次处理的影片个数，例如每处理5个后停止7分钟，再进行下一次处理。
