### ISSUE TITLE
JavDB用户评分输出标签有误

### ISSUE THREAD

**Issue by OrangeTien** [yoshiko2/Movie_Data_Capture#737]
（由于此处会自动将html标签给屏蔽，所以写标签时不加右边的尖括号）
刚刚发布了版本6.0.3，测试了一下，发现在JAVDB站中抓到用户评分会被保存到“<userrating </ userrating>”标签中。
但是经过测试，无论是在Emby还是Jellyfin中，都无法识别"<userrating"标签
正确输出标签为“ <rating </ rating>‘
稍后我会尝试提交Commit，如果有其他的大佬看到，也可以帮忙修改一下。

另外，其实在Emby和Jellyfin中，评分系统都会有两个评分指标，一个评分为公众评分（10分制），也就是直接从JavDB站抓取到的评分；另一个评分是影评人评分（百分制），也就是观影者自己评分，但是由于Emby和Jellyfin开发的失误，没有给用户提交评分的渠道。在这里，我建议把公众评分*20作为影评人评分。

简述版本：
1. 抓取JAVDB站的评分到 "<rating </ rating>" 标签
2. 如果大家觉得有必要，可以把第一步抓到的分数*20输出到 "<criticrating </ criticrating>"标签

十分感谢！

**Comment by lededev** [comment]
KODI的[文档](https://kodi.wiki/view/NFO_files/Templates#Movie_Template)里是`<userrating>`标签，我只有KODI没有Emby和Jellyfin没法测试，你有需要可以提交PR再增加一个`<rating>`标签，分数的乘数也可以按软件的设定做相应调整。

**Comment by OrangeTien** [comment]
我先去测试一下同时保留三个标签 `<userrating>, <rating>, <criticrating>`会不会出问题

**Comment by lededev** [comment]
看了你写的用户评分，还有点问题，要不我来改吧，如果你测试过了，就按你这个计算方式来填写这三个tags

**Comment by lededev** [comment]
![image](https://user-images.githubusercontent.com/30518126/160275862-4a02f812-a949-4334-880d-3673f872ac44.png)
这是我改过以后的效果，番号STARS-210，你再用Emby和Jellyfin试试吧

**Comment by OrangeTien** [comment]
不是，老哥你这么写不太对

**Comment by OrangeTien** [comment]
round()之后，评分4.1和评分4.4都是8分，（可是事实上4.1和4.4差的比较多）原JAVDB站中的的小分点精确到后两位

**Comment by OrangeTien** [comment]
使用round()，需要保留小数点，否则评分4.1和评分4.4都是8分（事实上4.1和4.4差的比较多）。
由于原JAVBD站中评分精确到小数点后两位，乘2然后round()之后最好也保留两位，不然评分都集中在8或者9的话就失去意义了

**Comment by lededev** [comment]
我在KODI里试了一下，如果填写8.9分，软件显示为8分，而不是9分，因此小数点后的部分四舍五入到整数是适合的，KODI这边不用保留小数点后的部分。
你看看其它两个软件如何显示的这种带小数点的分数呢？

**Comment by OrangeTien** [comment]
Emby和Jellyfin中的评分都是精确到小数点后1位的，老哥你的代码写的规范一些，建议作者Merge你的PR。然后的话，还是建议能够保留一下小数点，round()挺容易实现的。

**Comment by lededev** [comment]
![image](https://user-images.githubusercontent.com/30518126/160278278-b844c67f-f1a4-4289-a41d-a88daee8216b.png)
已经按你的反馈调整了评分的精度

**Comment by lededev** [comment]
Emby和Jellyfin的用户评分已经被支持，欢迎你继续改进。

**Comment by OrangeTien** [comment]
好的，多谢！

**Comment by Serious423** [comment]
Jellyfin还是无法识别评分，请问如何用KODI刷新

**Comment by lededev** [comment]
> Jellyfin还是无法识别评分，请问如何用KODI刷新

影片上按右键显示信息，右偏中下有几个图标，最右边有个刷新，如果没显示出来就向右滚动一下。
就是因为需要每部都刷新一下，所以我觉得比较烦，把缓存都删了，模式3补完全部.nfo重新建库试试。
