### ISSUE TITLE
仅停留在刮削黄片吗？

### ISSUE THREAD

**Issue by fbigun** [yoshiko2/Movie_Data_Capture#742]
为什么不刮削一些普通电影呢，有什么可以推荐的，最好是cli的工具。这样可以cron

**Comment by OrangeTien** [comment]
个人觉得是因为普通电影的刮削器都比较成熟了，就比如tinymediamanager，能自动刮削也能手动刮提高精度

**Comment by timk-lalala** [comment]
刮削正常电视剧电影去用tinyMediaManager =。=，你可真是个大聪明

**Comment by OrangeTien** [comment]
有问题直接说，别在这阴阳怪气，tinymediamannger可以完全手刮，保证影片的信息的正确性，你喜欢emby和plex去自动刮都是个人选择。需求不同，工具不同，你还有什么问题。

**Comment by OrangeTien** [comment]
> 刮削正常电视剧电影去用tinyMediaManager =。=，你可真是个大聪明

有问题直接说，别在这阴阳怪气，tinymediamannger可以完全手刮，保证影片的信息的正确性，你喜欢emby和plex去自动刮都是个人选择。需求不同，工具不同，你还有什么问题。

**Comment by fbigun** [comment]
问这个就是能不能自动刮削，不需要人为干预，后台自动运行。楼上推的都是在电脑手动运行的。

**Comment by fbigun** [comment]
我只想下载好电影后，后台自动刮削后保存。有需要的手动刮削替换就好。

**Comment by OrangeTien** [comment]
> 我只想下载好电影后，后台自动刮削后保存。有需要的手动刮削替换就好。

@lededev , 你出来看看这个需求。我明白你意思了，就是想跟cron一起用实现下载后马上自动刮削对吧。如果是现成的工具的话好像是没有，我认为最好的解决方案是infuse和plex，他们都有自动监控，文件夹新增电影会马上响应自己刮，缺点是都要会员，而且搭建需要费点时间去学习一下。

**Comment by fbigun** [comment]
> 

是的，我看这个项目能够满足我的需求，但是这个项目好像只会黄的

**Comment by kangbeicai** [comment]
> > 
> 
> 是的，我看这个项目能够满足我的需求，但是这个项目好像只会黄的

普通的电影刮削可以试试这个，可以实现实时监控目录变化并刮削。[https://github.com/jxxghp/nas-tools](url)
