### ISSUE TITLE
天美传媒（madou）部分番号会出现list index out range的报错

### ISSUE THREAD

**Issue by Naozheng** [yoshiko2/Movie_Data_Capture#744]
![image](https://user-images.githubusercontent.com/102581434/160561410-371714d4-1b1a-49e8-91b1-74b79907e324.png)
如图，如题。
[config.txt](https://github.com/yoshiko2/Movie_Data_Capture/files/8369138/config.txt)
config如附件，前天下载的6.0.3版本

另外，这个问题在6.0.2也有出现，但部分6.0.2能刮削的片子，6.0.3又不行了。比如上图中的TM0002

**Comment by Naozheng** [comment]
不会自己封装exe，等你们发布下一版吧：）

**Comment by lededev** [comment]
在Action页面直接可以下载，exe已经自动编译完成了。

**Comment by Naozheng** [comment]
仍有部分刮削不出来
![image](https://user-images.githubusercontent.com/102581434/160813783-93a08bd3-7758-43c7-a7d9-33bd98347009.png)
编号列表：TM0029~TM0036，TM0045，TM0050，TM0051，TM0075，TM0085
另外还发现了这个err记录，截图如下：
![image](https://user-images.githubusercontent.com/102581434/160813490-2ad4a898-d8aa-4b6c-80bf-eb6a8be896ff.png)
是不是人脸识别就不能用cnn，只能用hog？

**Comment by Naozheng** [comment]
另外刚刚试了一下，把TM0050文件名改成这个提示的TM0050-32D就能刮出来了，TM0051也一样，其他提示改成None的还是没法刮削

**Comment by lededev** [comment]
TM0029到TM0036在madou.club网站搜索不到，这些番号不存在。
TM0075和TM0085我这里测试没问题，你需要确定用的是Actions里面最新的版本。
```json
{
    "actor":"",
    "cover":"https://madou.club/covers/2021/05/22803b04cea8452.jpg",
    "director":"",
    "extrafanart":"",
    "imagecut":1,
    "label":"",
    "number":"TM0085",
    "outline":"",
    "release":"",
    "runtime":"",
    "series":"",
    "source":"madou.py",
    "studio":"天美传媒",
    "tag":[
        "林小樱",
        "董小宛",
        "麻将"
    ],
    "title":"自摸雀后",
    "website":"https://madou.club/tm0085-%e8%87%aa%e6%91%b8%e9%9b%80%e5%90%8e.html",
    "year":""
}
{
    "actor":"",
    "cover":"https://madou.club/covers/2021/04/8e26b3f6360bb17.jpg",
    "director":"",
    "extrafanart":"",
    "imagecut":1,
    "label":"",
    "number":"TM0075",
    "outline":"",
    "release":"",
    "runtime":"",
    "series":"",
    "source":"madou.py",
    "studio":"天美传媒",
    "tag":[
        "吸血鬼",
        "胡蓉蓉"
    ],
    "title":"吸血鬼打炮不留情",
    "website":"https://madou.club/tm0075-%e5%90%b8%e8%a1%80%e9%ac%bc%e6%89%93%e7%82%ae%e4%b8%8d%e7%95%99%e6%83%85.html",
    "year":""
}
```

**Comment by Naozheng** [comment]
好的谢谢。
29-36的信息在https://chicav.com/找到了。这么几个我就手动弄一下吧~哈哈

**Comment by neatgz** [comment]
> 在Action页面直接可以下载，exe已经自动编译完成了。
MD0129刮削失败，网站上有这个番号。
[!] [MD0129] As Number making data for '\\192.168.2.22\Porn\Movie_Data_Capture-CLI-6.0.3-Windows-amd64\MD0129.TS'
[+]select madou
list index out of range
