### ISSUE TITLE
请问有什么办法只更新NFO文件的评分么

### ISSUE THREAD

**Issue by Serious423** [yoshiko2/Movie_Data_Capture#745]
新更新了评分，特别好
但是媒体库太大了 6000多个媒体，重新刮是一项巨大工程，且之前的最爱标注会取消
请问有没有什么办法，只更新评分

**Comment by lededev** [comment]
用模式3进行整理就行了，如果需要评分，web站点只选择javdb，限制为每次处理5个就停止，计划任务每十分钟执行一次处理，以免被封IP。
如果已经有图片，Actions里最新版本默认不会重复下载，缺图片或者剧照才会补齐。
但评分还是要在KODI里手动刷新，才会显示，也许可以清空全部库重新扫描试试。

**Comment by lededev** [comment]
用模式3进行整理就行了，如果需要评分，web站点只选择javdb，限制为每次处理5个就停止，计划任务每十分钟执行一次处理，以免被封IP。
如果已经有图片，Actions里最新版本默认不会重复下载，缺图片或者剧照才会补齐。
但评分还是要在KODI里手动刷新，才会显示，也许可以清空全部库重新扫描试试。

**Comment by Serious423** [comment]
请问一下计划任务\KODI的手动刷新如何设置，说明没有找到Q-Q

**Comment by lededev** [comment]
从Actions页面下载最新版本的就行了，不需要计划任务了。使用说明看[PR](https://github.com/yoshiko2/Movie_Data_Capture/pull/746)

**Comment by Serious423** [comment]
感谢，但目前清空全部库重新扫描还是无法出评分
只能KODI手动刷新么。。

**Comment by lededev** [comment]
> 感谢，但目前清空全部库重新扫描还是无法出评分 只能KODI手动刷新么。。

你是怎么清空的，我是进 `%UserProfile%\Kodi\userdata\Database` 删光全部文件，不过还没重新建库。
