### ISSUE TITLE
可以提供关闭人脸识别的开关吗

### ISSUE THREAD

**Issue by kjstart** [yoshiko2/Movie_Data_Capture#747]
标准封面的片子直接截取右半边效果更好.

**Comment by lededev** [comment]
我觉得大部分有码的都可以直接切，无码的部分影片才有人脸识别的需求。
而且KODI已经支持横版封面了，直接显示横版封面，比人脸识别后切为竖版，更完整。

**Comment by hejianjun** [comment]
```
locations_model=
```
locations_model設置爲空就好了
