### ISSUE TITLE
搜刮间隔和番号重名或相似名问题

### ISSUE THREAD

**Issue by namco223** [yoshiko2/Movie_Data_Capture#748]
1 可不可以加入搜刮间隔时间参数，比如没搜刮一个间隔30秒之类的以防止被禁IP
2 有些番号有重名或者相似名，网页搜索会出现多个结果，用搜刮器时候会失败。可不可以手动指定链接和文件 进行搜刮分类。

**Comment by lededev** [comment]
已经加了https://github.com/yoshiko2/Movie_Data_Capture/pull/746，欢迎测试，直接去Actions页面下载最新的就行。

**Comment by lededev** [comment]
2.可以注意日志中的已经改名提示信息，如果符合，按网站结果改名后重新刮削一次。

**Comment by dfldylan** [comment]
> 2.可以注意日志中的已经改名提示信息，如果符合，按网站结果改名后重新刮削一次。

怎么改名啊老哥，比如MIDV-016，我想要的是小野六花的，它总给我下载那个2010年的老片子
