### ISSUE TITLE
收刮后名字没变

### ISSUE THREAD

**Issue by Marcus-Wa** [yoshiko2/Movie_Data_Capture#750]
为什么影片名字没有换的? 而我加在 file location那边就有
![image](https://user-images.githubusercontent.com/102940213/161546047-ed60375c-de6f-4cee-ab90-9b972afc674c.png)
![image](https://user-images.githubusercontent.com/102940213/161546410-e0afe486-67a7-46a8-80fd-c19f9e30a513.png)
![image](https://user-images.githubusercontent.com/102940213/161546479-9ad7af90-ccb1-4c6d-8ef3-2f07cec37acf.png)
![image](https://user-images.githubusercontent.com/102940213/161546523-49b3762c-c1ca-4d9d-89d0-20b4c1528fce.png)

**Comment by yoshiko2** [comment]
<img width="660" alt="image" src="https://user-images.githubusercontent.com/42309414/161561019-ac574a92-36f5-4661-a149-71ee80a4ee84.png">

**Comment by lededev** [comment]
改一下文件名长度限制，例如我的是这样的。
```ini
[Name_Rule]
location_rule='#'+actor+'/'+'['+year+'] '+original_title+' ['+number+']'
naming_rule=title
max_title_len= 78

```
另外，需要放开NTFS文件名路径最大长度限制，安装[python 3.10.4 64位](https://www.python.org/ftp/python/3.10.4/python-3.10.4-amd64.exe)的时候，安装程序给了这个选项。安装完成后重启生效。
![image](https://user-images.githubusercontent.com/30518126/161605816-6e35316b-03ef-4bc5-a25b-7922461d4315.png)

**Comment by lededev** [comment]
如果你所谓的“名字”是指文件名，那么理解错误了，文件名是不变的，不可配置，就是番号加后缀。
配置文件的的名字其实是指影片在软件里显示的影片标题，文字名称。
