### ISSUE TITLE
更新6.03后出现封面截屏的BUG

### ISSUE THREAD

**Issue by Serious423** [yoshiko2/Movie_Data_Capture#752]
更新到6.03后封面截图出现BUG，有时候封面截图到了缩展图的中间，目前削刮10部会出现一部这种情况

**Comment by hejianjun** [comment]
```
locations_model=cnn
```
可以提高準確率

**Comment by lededev** [comment]
@hejianjun 用cnn我总是返回 0, 0
除了face_recognition还需要安装别的模块吗？

**Comment by neatgz** [comment]
> ```
> locations_model=cnn
> ```
> 
> 可以提高準確率

你好，windows 版，直接使用 locations_model=cnn ，会提示缺少模块。请问需要单独安装其他模块吗？能否给个简易的安装说明？

**Comment by Minidoracat** [comment]
我這邊也是設定 locations_model=cnn 
出現了
`No module named 'ImageProcessing.cnn'`

**Comment by hejianjun** [comment]
windows 版 是指打包后的版本么

**Comment by hejianjun** [comment]
exe打包的时候没有 
```
 --hidden-import "ImageProcessing.cnn" `
```
这边你们可以使用`python`版本或者自己打包试试

**Comment by lededev** [comment]
我直接用python.exe以脚本方式运行，不做exe打包，cnn也没生效，需要安装其它模块吗？
