### ISSUE TITLE
6.03版本NFO评分的问题

### ISSUE THREAD

**Issue by wind-snow-moon** [yoshiko2/Movie_Data_Capture#753]
1. 在6.03中，来自网站的评分信息会被写入NFO的userrating字段，而在Kodi中，NFO的userrating字段是给用户打分用的，来自网站抓取的评分信息应该写入ratings字段，下图就是一段拷贝自Kodi NFO的片段（代码中用‘《’代替了'<'，用'》'代替了'>'，以免无法显示）；因此能否将来自网站的评分字段写入NFO的ratings字段，并将userrating字段保留给用户使用；
    《ratings》
        《rating name="imdb" max="10"》
            《value》7.400000《/value》
            《votes>62234《/votes》
        《/rating》
        《rating name="themoviedb" max="10" default="true"》
            《value》7.900000《/value》
            《votes》1234《/votes》
        《/rating》
    《/ratings》
    《userrating>0《/userrating》

2. 如果将NFO中的userrating字段保留给用户使用，能否在程序的模式3“更新”中，更新NFO信息时，可以选择保留userrating字段的内容不更新，这样可以方便保留用户自己的评分，即使更新NFO内容也不会丢失

**Comment by lededev** [comment]
最新代码已经是这样的了，等下个版本吧
https://github.com/yoshiko2/Movie_Data_Capture/blob/38b18efdb2590a83ecda3e98729bcda2912fca42/core.py#L363

**Comment by lededev** [comment]
2. KODI记录用户评分不会改写.nfo文件，它自己有一套缓存机制。

**Comment by wind-snow-moon** [comment]
1. KODI可以选择导出用户数据，这时用户的评分会写入NFO的userrating文件；
2. 如果用户使用Movie_Data_Capture的更新功能更新了NFO文件内容，KODI要重新导入才能重新读取NFO的内容，此时KODI中用户的评分会被NFO中userrating字段的内容覆盖；
3. 因此用户如果既想使用Movie_Data_Capture的更新功能更新了NFO文件内容，又想保留用户自己的评分，我认为只能这样操作：A. KODI导出用户数据，这时用户的评分会写入NFO的userrating文件，B. 用户使用Movie_Data_Capture的更新功能更新了NFO文件内容（但需要MDC提供保留userrating内容的功能），C. KOD要重新导入文件，重新读取NFO的内容；这样可以实现既更新了NFO等内容，也保留了用户评分
4. TinyMediaManager也是类似的过程

**Comment by lededev** [comment]
你有有KODI导出userrating文件的例子以及对应番号吗，上传一份我试试。

**Comment by wind-snow-moon** [comment]
[IPX-235-C 6.03输出的文件.nfo.txt](https://github.com/yoshiko2/Movie_Data_Capture/files/8448242/IPX-235-C.6.03.nfo.txt)
[IPX-235-C kodi导出的数据，Userrating为9.nfo.txt](https://github.com/yoshiko2/Movie_Data_Capture/files/8448243/IPX-235-C.kodi.Userrating.9.nfo.txt)

**Comment by lededev** [comment]
我现在正在更新全套.nfo，KODI缓存被我清空了，暂时没法用KODI测试导出，得等全部更新完成。
所以还是直接问你吧，因为我没用过KODI的导出userrating功能，KODI导出是直接修改原有的.nfo文件还是会新建一个其它文件名的.nfo文件呢？

**Comment by wind-snow-moon** [comment]
KODI导出时，会覆盖之前的NFO文件

**Comment by wind-snow-moon** [comment]
谢谢！

**Comment by lededev** [comment]
等会儿自动生成完成之后，你可以到Actions页面下载一份执行试试，看是不是能保留导出的自定义评分了，我现在还没法试。

**Comment by wind-snow-moon** [comment]
PyInstaller #993: Pull request https://github.com/yoshiko2/Movie_Data_Capture/pull/746 synchronize by [lededev](https://github.com/lededev) 
从Action上下载了上述版本，测试通过，Userrating字段在使用模式3时会保留
