### ISSUE TITLE
可否把硬字幕和软字幕的水印分开？

### ISSUE THREAD

**Issue by Huaneg** [yoshiko2/Movie_Data_Capture#754]
也就是增加一个开关，硬字幕和软字幕（软字幕就是外挂字幕）的水印分开。硬字幕就根据文件名后面是否有"-C"去判断。软字幕根据是否有外挂字幕去判断~~~~~

**Comment by neatgz** [comment]
支持，确实，外挂字幕的影片，后缀也带个 -C ，很别扭

**Comment by lededev** [comment]
我认为外挂字幕可移动可删除，为它做水印本身就不符合逻辑，还要为它做个特殊的水印那就更没必要了。

**Comment by lededev** [comment]
外挂字幕的视频文件本来就可以不加-C，检查和复制字幕文件时并不看有没有-C后缀，都会进行检查。

**Comment by neatgz** [comment]
> 外挂字幕的视频文件本来就可以不加-C，检查和复制字幕文件时并不看有没有-C后缀，都会进行检查。


硬字幕 的文件名是 “番号-C.mp4”，会自动 在 nfo 文件里 加入 “<tag>字幕</tag>” “<genre>字幕</genre>” 的标签，海报上也会加入 字幕 的水印。nfo 文件方便在 plex jellyfin 里 直接点击 字幕 标签 筛选。
外挂字幕 的文件名是 “番号.mp4” 和 “番号.srt” ，字幕文件会自动移动。但是  nfo 文件里 没有 “<tag>字幕</tag>” “<genre>字幕</genre>” 的标签，也不会在海报上加水印。除非把外挂字幕的文件名改成   “番号-C.mp4” 和 “番号-C.srt” 
我对水印分开没需求，是希望 外挂字幕 不加 -C，也能自动加标签和水印

**Comment by lededev** [comment]
.nfo里面为什么要加字幕标签？如果字幕文件被删除了，谁来移除那个标签？
我觉的这些都是播放软件的责任，扫描影片库之后，软件自然知道那些视频带了外挂字幕，至于是不是没有给归类排序或者加上标签，到对应播放软件那边发ISSUE比较合理。
移动复制字幕的代码我会改一下，让它尽量不漏掉各种形式的字幕。

**Comment by neatgz** [comment]
有道理，筛选带有字幕的视频文件应该是 播放软件的责任。你说得对

**Comment by Huaneg** [comment]
是这样，我倒是没考虑到tag的问题。我的习惯是收藏无水印的5744原版+外挂字幕的。有的时候看到有新的字幕出来，总是习惯去看一眼我有没有这个视频。有的话就把字幕拷进去。因为这个原因，总是弄错。如果能在水印上加以区别的话，我就能知道这个视频是硬字幕的还是不是。就不用再点进去看播放页面了。
