### ISSUE TITLE
刮削出现的nfo信息里含有![CDATA[字符导致使用本地影片导入nfo信息时也出现该字符

### ISSUE THREAD

**Issue by RAY1021155762** [yoshiko2/Movie_Data_Capture#755]
![image](https://user-images.githubusercontent.com/103305932/162561545-3723f793-f14b-4ad7-a9aa-9ace314db3f1.png)
请问作者可否将nfo信息里的“”![CDATA[“”字符去除，谢谢

**Comment by lededev** [comment]
CDATA是这个PR加上的https://github.com/yoshiko2/Movie_Data_Capture/pull/670/commits/2483a9fc2f015c6596efc1c3c704c5efc9c2c3f6
你想去掉得和这个PR的作者商量，他需要CDATA。
不知道你用的哪个播放软件，KODI里这个CDATA毫无影响，也许你应该去播放软件那边发ISSUE让他们支持CDATA。

**Comment by lededev** [comment]
他需要CDATA的理由见此[issue](https://github.com/yoshiko2/Movie_Data_Capture/issues/668)
