### ISSUE TITLE
FC2刮削问题，Movie number has changed! [FC2-424646]->[None]

### ISSUE THREAD

**Issue by CNAITIME** [yoshiko2/Movie_Data_Capture#756]
只有FC2刮削会出现问题，求大佬分析

**Comment by CNAITIME** [comment]
[!] [FC2-424646] As Number making data for 'T:\123\日本\FC2-424646.mp4'












FC2-424646
[-]Movie number has changed! [FC2-424646]->[None]

**Comment by icedrain0611** [comment]
试试看源网站删掉 javdb

**Comment by icedrain0611** [comment]
不过这个番号估计是下架了吧 是不是太早了，首先确保fc2官网有这个商品。。

**Comment by STAR-2411** [comment]
> 不过这个番号估计是下架了吧 是不是太早了，首先确保fc2官网有这个商品。。

我也碰到了同样的问题，FC2的番号全都搜刮不了了，前天还是好的，其他影片正常搜刮。希望有大佬解答一下。

**Comment by Juhraya** [comment]
FC2 同样无法刮削

**Comment by kudouxinyi** [comment]
javdb改版了，应该是页面元素名称变了，需要重新适配

**Comment by yunxiujun** [comment]
我也同样的问题。。我还冲了javdb永久会员 也刮削不了

**Comment by icedrain0611** [comment]
不要用javdb




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2022年4月16日(星期六) 晚上11:39
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [yoshiko2/Movie_Data_Capture] FC2刮削问题，Movie number has changed! [FC2-424646]-&gt;[None] (Issue #756)





  
不过这个番号估计是下架了吧 是不是太早了，首先确保fc2官网有这个商品。。
  
我也碰到了同样的问题，FC2的番号全都搜刮不了了，前天还是好的，其他影片正常搜刮。希望有大佬解答一下。
