### ISSUE TITLE
.actors是否已经支持

### ISSUE THREAD

**Issue by wind-snow-moon** [yoshiko2/Movie_Data_Capture#758]
已经关闭的issue #355提到是否可以支持.actors目录，以便kodi可以显示演员头像，issue #355目前已经关闭，这个功能目前似乎仍不支持（刮削好的目录中没有.actors目录），后续有无可能支持该功能？谢谢！

**Comment by yoshiko2** [comment]
https://github.com/xinxin8816/gfriends

**Comment by wind-snow-moon** [comment]
Kodi要求演员头像必须放在电影所在目录的".actors"子目录下，gfriends这个软件目前只支持Emby 、 Jellyfin和plex，不支持Kodi。如果能在刮削时生成".actors"子目录并保持相应演员的头像（演员头像的名字要和nfo中actor字段一致），这样刮削完Kodi就可以直接使用了。
