### ISSUE TITLE
6.0版本后运行闪退

### ISSUE THREAD

**Issue by 7ordy** [yoshiko2/Movie_Data_Capture#762]
系统win11 x64，用5.0.2使用正常，换成6.0.1/2/3之后运行就闪退

**Comment by lededev** [comment]
这个版本跨度有点大，最好写明可重现的使用步骤，以及出现闪退和正常的两个相邻版本号，以便查找原因。

**Comment by lededev** [comment]
另外提示一下，不同版本的配置文件并不兼容，需要使用对应版本的配置文件。

**Comment by 7ordy** [comment]
> 另外提示一下，不同版本的配置文件并不兼容，需要使用对应版本的配置文件。

好的，使用6.0版本的未修改配置文件后可以正常了。
不过我就是把5.0.2的文件配置复制了进去就闪退了
[Name_Rule]
location_rule=number
naming_rule=number+'-'+title
max_title_len=50
我再看一下格式设置方式

谢谢
