### ISSUE TITLE
请问支持能支持arm64吗？

### ISSUE THREAD

**Issue by keeno1982** [yoshiko2/Movie_Data_Capture#763]
硬盘是挂在arm的一台debian server上，不知道如何编译支持arm64

**Comment by lededev** [comment]
不用编译，直接脚本方式运行也可以。
就是不知道你是否能装全依赖库。

**Comment by keeno1982** [comment]
@lededev 求教如何用脚本运行，只看到amd相关的可执行文件

**Comment by lededev** [comment]
先运行python3 -V，看看版本号多少，如果没安装就安一下，需要3.7以上。
然后`sudo apt-get install python3-pip git`把pip3和git装上。
接下来克隆本项目的源代码，并且安装依赖库
```
git clone https://github.com/yoshiko2/Movie_Data_Capture.git
cd Movie_Data_Capture
pip3 install pyinstaller
pip3 install -r requirements.txt
```
如果都运行通过了，就可以试试脚本运行了
`python3 ./Movie_Data_Capture.py --help`

**Comment by keeno1982** [comment]
感谢，可以运行了！不过有个问题是，我硬盘是通过远程挂载的，这一刮就把原文件给刮到我本地了哈，相当于我又下载了一遍，不知道如何只在远程目录整理

**Comment by lededev** [comment]
配置文件里可以指定成功存储目录，你的脚本运行在远程的话，将那个目录指定为远程的目录就行了。

**Comment by keeno1982** [comment]
太谢谢了，可行。果然是同道中人最温暖哈。

**Comment by wind-snow-moon** [comment]
git clone https://github.com/yoshiko2/Movie_Data_Capture.git
cd Movie_Data_Capture
pip3 install pyinstaller
pip3 install -r requirements.txt
上述步骤都已经安装成功，请问如何编译成单个执行文件，在windows下运行make命令提示“'make' 不是内部或外部命令，也不是可运行的程序或批处理文件”

**Comment by yoshiko2** [comment]
@wind-snow-moon 把我秀到了
