### ISSUE TITLE
代理出现网络错误

### ISSUE THREAD

**Issue by h806600727** [yoshiko2/Movie_Data_Capture#766]
[*] - 严禁在墙内宣传本项目 -
[*]======================================================
[+]Start at 2022-04-18 22:20:41
[+]Load Config file 'F:\新建文件夹\config.ini'.
[+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30
[+]Find 8 movies.
[*]======================================================
[!]                - 12.5% [1/8] -             22:20:43
[!] [AOZ090] As Number making data for 'F:\新建文件夹\AOZ090.avi'
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]HTTPSConnectionPool(host='madou.club', port=443): Max retries exceeded with url: /aoz090.html (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
[-]Connect Failed! Please check your Proxy or Network!

**Comment by kudouxinyi** [comment]
同上
