### ISSUE TITLE
cnn mode error

### ISSUE THREAD

**Issue by bladesz123** [yoshiko2/Movie_Data_Capture#769]
在使用cnn mode 剪裁封面时出现
ERROR:root:No Module named 'ImageProcessing.cnn'，请问是我本地缺失了什么模块么？

**Comment by lededev** [comment]
下载Actions里[这个版本](https://github.com/yoshiko2/Movie_Data_Capture/actions/runs/2196294918)运行试试

**Comment by bladesz123** [comment]
> 下载Actions里[这个版本](https://github.com/yoshiko2/Movie_Data_Capture/actions/runs/2196294918)运行试试

可以了，多谢！
