### ISSUE TITLE
docker版本能否增加一项功能:刮削完成后不自动退出.

### ISSUE THREAD

**Issue by ztx0079** [yoshiko2/Movie_Data_Capture#771]
docker版本目前在刮削完成后会自动退出,如果勾选了自动重新启动,那么就会不断退出又重启,于是群晖不断的通知mdc意外退出又重启又意外退出.

能否通过配置文件让程序
1.执行N部电影的刮削
2.静默A时间
3.再次执行下N部电影的刮削
4.直至刮削任务完成后,不退出程序,静默一段时间后再重新读取目录并执行刮削任务.

这样可以降低调用这些元数据网站的频率,防止封号,同时又可以让程序常驻后台,省去了手动开关的操作,以及开启自动重启时不断的通知问题.

**Comment by lededev** [comment]
> 能否通过配置文件让程序 1.执行N部电影的刮削 2.静默A时间 3.再次执行下N部电影的刮削 

有这个功能，看wiki了解用法
https://github.com/yoshiko2/Movie_Data_Capture/wiki#%E8%AF%B7%E6%B1%82%E5%BB%B6%E8%BF%9F

> 4.直至刮削任务完成后,不退出程序,静默一段时间后再重新读取目录并执行刮削任务.

这个你需要自己写脚本来实现对某个目录的新文件监听检测和启动刮削程序。
任务完成后不退出程序对绝大多数用户而言不适用，你这个需求不典型。

> 这样可以降低调用这些元数据网站的频率,防止封号,同时又可以让程序常驻后台,省去了手动开关的操作,以及开启自动重启时不断的通知问题.

我没用docker版本和群晖系统，怎么设置能避免这个问题不清楚，建议写脚本来解决。

**Comment by VergilGao** [comment]
目前程序已经集成了类似的功能，无需docker实现。
