### ISSUE TITLE
[-] int() argument must be a string, a bytes-like object or a number, not 'NoneType'

### ISSUE THREAD

**Issue by oOtroyOo** [yoshiko2/Movie_Data_Capture#772]
core.py :729
`uncensored = int(unce) if isinstance(unce, bool) else int(is_uncensored(number))`

[-] int() argument must be a string, a bytes-like object or a number, not 'NoneType'

似乎是可以这样改：
`uncensored = int(unce) if isinstance(unce, bool) else is_uncensored(number)`

**Comment by lededev** [comment]
源代码中有大量的`if uncensored == 1:`判断，所以这里还是只能赋值数字，我改一下吧。
