### ISSUE TITLE
先检测文件是否已经存在，再刮削

### ISSUE THREAD

**Issue by OrangeTien** [yoshiko2/Movie_Data_Capture#774]
![image](https://user-images.githubusercontent.com/61771046/164588316-864cebcf-83d9-497c-975f-5ff614072d7d.png)

如图，目前程序读到文件后是先开始刮削（先把图片视频下载好，然后给某些图片加入Mark），然后再检测文件是否存在，这里我觉得是能改进的，就是先检测 targetpath 是否存在，然后再刮削，省得浪费流量去刮削了。@lededev大佬去解决一下？

**Comment by lededev** [comment]
不刮削不取得元数据拿不到最终的文件完整路径，信息不足，没法检测文件是否存在。
因此这个先后步骤不能互换。
就下几个网页几张图片，而且图片在默认设置下不会重复下载，这点流量你也在意，小水管该扩容了。

**Comment by lededev** [comment]
说句题外话
javdb39.com和jdbimgs.com没有在大防火墙的名单里，所以也可以加到软路由的直连白名单里面，万一被封IP，而你的宽带又有公网IP的话，重新PPPoE拨号换个IP就行了。
而且不用代理流量，也就不担心流量问题了。

**Comment by OrangeTien** [comment]
行，言之有理，我的公网IP每天都变动了，它封不了。
