### ISSUE TITLE
能否在config.ini中增加一个开关，将同一个影片不同扩展名的视频文件认为是同一个文件来进行处理，以免刮削和导入同一个影片重复的视频文件？

### ISSUE THREAD

**Issue by wind-snow-moon** [yoshiko2/Movie_Data_Capture#775]
1. 在目前程序中，如果之前已经刮削了ABC-123.MP4文件，当再次刮削同一个影片的一个不同扩展名的文件（如ABC-123.MKV、ABC-123.WMV等）时，程序还是会将这些不同扩展名等文件刮削进来；
2. 能否在config.ini中增加一个开关，通过开启该开关，从而将上述同一个影片不同扩展名等视频文件是否可以认为是同一个文件？这样可以避免导入重复内容的文件；
3. 进一步的，对于同一个视频，带字幕的、分割成多CD等文件（如ABC-123.MKV、ABC-123-C.MP4、ABC-123-CD1.MKV等），能否也提供一个开关，从而可以选择是否作为相同文件刮削和导入；
谢谢！

**Comment by lededev** [comment]
多多练习使用Everything，查找类型限制为视频，指定路径后按名称排序，然后你就可以删除重复的影片了。

**Comment by wind-snow-moon** [comment]
视频比较多的话，eveything手动删除比较麻烦，而且每隔一段时间就需要重新检视整个目录查找是否有重复的视频，因此能否在MDC软件中增加这个特性，在刮削和导入时就实现自动去重

**Comment by lededev** [comment]
我认为造成重复下载是你自己的问题。
在KODI下可以很容易的发现重复影片，影片的详细信息页显示了番号（我做的），记下番号输入Everything能查到并删除重复的影片，这对我就够用了。
刮削工具不是影片库管理器，所以没必要干影片管理器的活。

**Comment by wind-snow-moon** [comment]
了解了，谢谢
