### ISSUE TITLE
爬取url增加请求

### ISSUE THREAD

**Issue by GuoJiangpeng** [yoshiko2/Movie_Data_Capture#777]
能不能增加一个爬取地址呢  https://dahlia-av.jp/

**Comment by yoshiko2** [comment]
对于需要的新功能，可通过[Release](https://github.com/yoshiko2/Movie_Data_Capture/releases/latest)下方联系方式付费，会在下一个版本交付，或者坐等有缘人提交代码

**Comment by lededev** [comment]
它家的内容javbus和javdb都有，作品也不多就4页，你想要高像素的封面图还是自己下载覆盖源文件吧，然后运行`mdc.exe -Nm3 -d0 -p 视频库路径 -q 番号 -d0`就能制作出裁剪好的封面。
