### ISSUE TITLE
封面剪裁是否可以增加位置选项？

### ISSUE THREAD

**Issue by Juhraya** [yoshiko2/Movie_Data_Capture#782]
能否增加靠左边剪切/中间剪切/右边剪切的选项？
比方说STARS-053，STARTS-152，STARS-156这类靠左剪切比较合适，开了cnn人脸识别也切的不太好；
STARS-145，STARS-133，这类在中间剪裁比较合适；

**Comment by lededev** [comment]
你发的这几个番号的封面我都看了，只能说你的要求比较独特，人家正式封面还是都在右边的。
指定靠左切不是做不到，而是哪怕你也是只要求个例靠左切，估计大部分还是认可靠右切的。
这种为了解决你的问题，可能会带来更多人问题的功能，还是你自己手工裁剪封面，或者自己改程序或请人做私人定制版本吧。
