### ISSUE TITLE
Linux版使用hog时崩溃

### ISSUE THREAD

**Issue by BarryAlanPan** [yoshiko2/Movie_Data_Capture#789]
使用版本为6.1.2。在调用Hog后报错Illegal instruction

log：

> [*]================= Movie Data Capture =================
[*]                        6.1.2                         
[*]======================================================
[*] - Linux-5.4.0-109-generic-x86_64-with-glibc2.14 
[*] - x86_64 - Python-3.8.12
[*]======================================================
[*] - 严禁在墙内宣传本项目 - 
[*]======================================================
[+]Start at 2022-05-02 02:32:33
[+]Load Config file '/data/Movie_Data_Capture/config.ini'.
[+]Enable debug
[+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30, stop_counter=10
[+]Find 8 movies.
[*]======================================================
[!]                - 12.5% [1/8] -             02:32:33
[!] [MD0165-5] As Number making data for '/data/Movie_Data_Capture/MD0165-5.mp4'
[+]select madou
[+]Find movie [MD0165-5] metadata on website 'madou'
[+] ------- DEBUG INFO -------
[+]  - actor          : 
[+]  - cover          : https://madou.club/covers/2021/10/1619efe8d4c34fd.jpg
[+]  - director       : 
[+]  - extrafanart    : 0 links
[+]  - imagecut       : 1
[+]  - label          : 
[+]  - number         : MD0165-5
[+]  - outline        : 0 characters
[+]  - release        : 
[+]  - runtime        : 
[+]  - series         : 
[+]  - source         : madou.py
[+]  - studio         : 麻豆传媒
[+]  - tag            : ['季妍希', '少妇', '少年阿宾', '熟女', '苏语棠']
[+]  - title          : 少年阿宾 第二季-篇章五 寒假开始
[+]  - website        : https://madou.club/md0165-5.html
[+]  - 无码           : True
[+]  - original_title : 少年阿宾 第二季-篇章五 寒假开始
[+]  - cover_small    : 
[+]  - actor_list     : ['']
[+]  - trailer        : 
[+]  - naming_rule    : MD0165-5-少年阿宾 第二季-篇章五 寒假开始
[+] ------- DEBUG INFO -------
[+]Use model         hog
Illegal instruction (core dumped)

**Comment by lededev** [comment]
看起来像是CPU太低端了，不支持AVX2指令集，hog不行就换cnn试试，要是都不行，就将那行置空，不使用面部检测。

**Comment by BarryAlanPan** [comment]
> 看起来像是CPU太低端了，不支持AVX2指令集，hog不行就换cnn试试，要是都不行，就将那行的等号后面置空，不使用面部检测。

置空解决了，感谢🍺
