### ISSUE TITLE
JavDB站刮削耗时长

### ISSUE THREAD

**Issue by OrangeTien** [yoshiko2/Movie_Data_Capture#795]
JavDB 刮削失败率高，耗时长

一般如果被Javdb给封了，就会直接遇到番号变成None, 比如 `Movie number has changed! [DASD-821]->[None]`

如果是开启了代理能正常访问javdb站的话，一般会卡在 `javdb.py` 的286行: `  'outline': getOutline(number, title),`

Author是建议了很多次非必要不用Javdb站，可是这个网站资料最全啊，有预告片，有评分
有没有其他替代站点啊....
或者脑洞打开，在每个网站上各取所需，比如在javbus上抓文字的元数据，上DMM抓预告片和评分

**Comment by lededev** [comment]
用`-R 6m35s`，每次处理的个数少一点`-c 5`，我用72小时都没被javdb封过IP，而且我用的公网PPPoE拨号IP，封了我随时可以重新拨号换个IP。

**Comment by kudouxinyi** [comment]
> JavDB 刮削失败率高，耗时长
> 
> 一般如果被Javdb给封了，就会直接遇到番号变成None, 比如 `Movie number has changed! [DASD-821]->[None]`
> 
> 如果是开启了代理能正常访问javdb站的话，一般会卡在 `javdb.py` 的286行: ` 'outline': getOutline(number, title),`
> 
> Author是建议了很多次非必要不用Javdb站，可是这个网站资料最全啊，有预告片，有评分 有没有其他替代站点啊.... 或者脑洞打开，在每个网站上各取所需，比如在javbus上抓文字的元数据，上DMM抓预告片和评分

我目前也是同样的问题，全部番号变成了none

**Comment by OrangeTien** [comment]
是,javdb站改版，然后MDC目前的改动还没有调校好，我目前是开代理刮一部要很久，直连的话（手动登录javdb站无问题），但是MDC会报 [number] -> [None]
