### ISSUE TITLE
6.1.2版本连接javdb出现503，浏览器能正常访问

### ISSUE THREAD

**Issue by luugh** [yoshiko2/Movie_Data_Capture#800]
**Describe the bug 错误描述**
已开启调试模式，错误如下：
`[+]select javdb
[!]javdb:select site javdb38
[-]get_html_by_scraper() failed. HTTPSConnectionPool(host='javdb38.com', port=443): Max retries exceeded with url: /search?q=LEGSJAPAN-1001&f=all (Caused by ResponseError('too many 503 error responses'))
cannot unpack non-iterable NoneType object`

**Expected behavior 预期结果 **
梯子全程打开，浏览器访问这个页面正常，cookie也是能用的，但是就是这个程序连接它的时候报错，比较奇怪。
**Logs 日志**

[+]select javdb
[!]javdb:select site javdb38
[-]get_html_by_scraper() failed. HTTPSConnectionPool(host='javdb38.com', port=443): Max retries exceeded with url: /search?q=LEGSJAPAN-1001&f=all (Caused by ResponseError('too many 503 error responses'))
cannot unpack non-iterable NoneType object

**Running Env 运行环境**
 - OS : win11
 - Python Version : 3.x

**Comment by lededev** [comment]
将以下域名加入软路由的直连白名单，然后用Actions里[这个版本](https://github.com/yoshiko2/Movie_Data_Capture/actions/runs/2288475634)试试。
大防火墙并没有屏蔽javdb及其图床，不过最近这个网站一直在改版，需要程序做一些适配。
javdb39.com
javdb38.com
javdb40.com
javdb41.com
jdbimgs.com

**Comment by kudouxinyi** [comment]
> 将以下域名加入软路由的直连白名单，然后用Actions里[这个版本](https://github.com/yoshiko2/Movie_Data_Capture/actions/runs/2288475634)试试。 大防火墙并没有屏蔽javdb及其图床，不过最近这个网站一直在改版，需要程序做一些适配。 javdb39.com javdb38.com javdb40.com javdb41.com jdbimgs.com

测试了611r3和612都不行，番号都变成了none，可能还是改版的问题

**Comment by luugh** [comment]
> 将以下域名加入软路由的直连白名单，然后用Actions里[这个版本](https://github.com/yoshiko2/Movie_Data_Capture/actions/runs/2288475634)试试。 大防火墙并没有屏蔽javdb及其图床，不过最近这个网站一直在改版，需要程序做一些适配。 javdb39.com javdb38.com javdb40.com javdb41.com jdbimgs.com

我尝试了下，加入直连之后浏览器无法直接访问这个网站了，
actions里的软件报错了：
[-]HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/yoshiko2/Movie_Data_Capture/releases/latest (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
[-]Connect Failed! Please check your Proxy or Network!

**Comment by lededev** [comment]
> > 将以下域名加入软路由的直连白名单，然后用Actions里[这个版本](https://github.com/yoshiko2/Movie_Data_Capture/actions/runs/2288475634)试试。 大防火墙并没有屏蔽javdb及其图床，不过最近这个网站一直在改版，需要程序做一些适配。 javdb39.com javdb38.com javdb40.com javdb41.com jdbimgs.com
> 
> 测试了611r3和612都不行，番号都变成了none，可能还是改版的问题

我的运行结果，javdb访问没问题，是你网络问题，被封IP了。
![image](https://user-images.githubusercontent.com/30518126/167290350-1663cc66-5a77-45b2-9b8e-903605d58868.png)

**Comment by luugh** [comment]
> 

请问下，你是能直连到javdb吗

**Comment by luugh** [comment]
> > > 将以下域名加入软路由的直连白名单，然后用Actions里[这个版本](https://github.com/yoshiko2/Movie_Data_Capture/actions/runs/2288475634)试试。 大防火墙并没有屏蔽javdb及其图床，不过最近这个网站一直在改版，需要程序做一些适配。 javdb39.com javdb38.com javdb40.com javdb41.com jdbimgs.com
> > 
> > 
> > 测试了611r3和612都不行，番号都变成了none，可能还是改版的问题
> 
> 我的运行结果，javdb访问没问题，是你网络问题，被封IP了。 ![image](https://user-images.githubusercontent.com/30518126/167290350-1663cc66-5a77-45b2-9b8e-903605d58868.png)

这个封ip，是指javdb封禁我这边的ip吗

**Comment by lededev** [comment]
> 请问下，你是能直连到javdb吗

我在2楼写了哪几个域名是直连的，其余的诸如api.github.com走的代理。

**Comment by luugh** [comment]
> > 请问下，你是能直连到javdb吗
> 
> 我在2楼写了哪几个域名是直连的，其余的诸如api.github.com走的代理。

这个是写了并发的吗？我看请求的时候连续3个请求到javdb，能麻烦告知一下并发代码的位置吗？

**Comment by lededev** [comment]
> 这个是写了并发的吗？我看请求的时候连续3个请求到javdb，能麻烦告知一下并发代码的位置吗？

没什么并发，我在用的是39，图方便把 40 41 这些未来会用到的也设置进软路由直连规则了而已。
