### ISSUE TITLE
611r3和612均无法选择javdb进行刮削

### ISSUE THREAD

**Issue by kudouxinyi** [yoshiko2/Movie_Data_Capture#801]
关闭梯子和开启梯子浏览器均可以访问javdb，已经使用https://github.com/yoshiko2/Movie_Data_Capture/actions/runs/2288475634  这个版本进行测试了

关闭梯子进行刮削提示如下错误
`
[-]get_html_session() failed. HTTPSConnectionPool(host='javdb.com', port=443): Max retries exceeded with url: /search?q=ARA-526&f=all (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001B96DBBC160>, 'Connection to javdb.com timed out. (connect timeout=10)'))
[-]get_html_by_scraper() failed. HTTPSConnectionPool(host='javdb.com', port=443): Max retries exceeded with url: /search?q=ARA-526&f=all (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001B96DBBC190>, 'Connection to javdb.com timed out. (connect timeout=10)'))
[-]Movie number has changed! [ARA-526]->[None]
`
开启梯子全局代理提示如下错误
`
[!] [ARA-526] As Number Processing for 'D:\迅雷下载\WASH\分析站\ARA-526.MP4'
[-]Movie number has changed! [ARA-526]->[None]
[*]======================================================
`

**Comment by OrangeTien** [comment]
是有问题的，我几天前反馈过了，可以参考 #795 . 最近版本不推荐用javdb去刮了，要么换网站刮，要么就先囤点资源等更新版本去刮吧。
