### ISSUE TITLE
6.1.3版本nfo演员关键字输出错误

### ISSUE THREAD

**Issue by hw54** [yoshiko2/Movie_Data_Capture#802]
**Describe the bug 错误描述**
![image](https://user-images.githubusercontent.com/70341574/167371059-00df0061-9987-4d08-a52d-6ed6c6c668b6.png)
![image](https://user-images.githubusercontent.com/70341574/167370822-27c08893-873f-49b1-9a98-8f714f0afb97.png)
上图是源代码(core.py)，下图是输出的.nfo
源代码里红框中的两行并没有print出来，导致演员关键字出现错误

**Running Env 运行环境**
 - OS : Windows 11

config.ini配置：
[actor_photo]
download_for_kodi=0

**Comment by yoshiko2** [comment]
fixed
