### ISSUE TITLE
发现已有影片档案, 可以在CONFIG选择删除搬前原档

### ISSUE THREAD

**Issue by anson338** [yoshiko2/Movie_Data_Capture#803]
[+]Find movie [] metadata on website 'fc2'
[+]Image Copyed!     output/***/***/FC2-2663992-poster.jpg
[-]FileExistsError: File Exists on destination path, we will never overwriting.

我本人是用RSS 自动下载影片的. 另外mdc.ini 设定了 failed_move=1
导致很多重覆影片卡在档案中.

**Comment by caihua** [comment]
发现重复后，现在的文件还放在原来的目录下，建议如果发现重复了，将其搬离到一个单独的目录，方便处理
