### ISSUE TITLE
重构 WebCrawler

### ISSUE THREAD

**Issue by Suwmlee** [yoshiko2/Movie_Data_Capture#807]
对 WebCrawler 进行重构，完全独立出来，可以作为单独的库维护
简单例子 ~~https://github.com/Suwmlee/template~~ https://github.com/Suwmlee/scrapinglib

这个库只抓取信息不进行翻译，命名规则等修改。翻译，命名修改放到外部去处理
这样做的好处是，业务逻辑更清晰，扩展其他网站更方便，维护简单。

扩展的时候，只需要继承基础的刮削类，更改针对网站的 actor，title 等参数即可。特殊情况也可以单独修改

**Comment by yoshiko2** [comment]
目前暂无独立WebCrawler的打算 后期可能会上脚本热加载

**Comment by Suwmlee** [comment]
我计划在  https://github.com/Suwmlee/ikaros 重构了，重构后把独立的库推到这边？
