### ISSUE TITLE
6.1.4，部分影片写到本地的文件夹/nfo信息是乱码

### ISSUE THREAD

**Issue by slimekingwin8cn** [yoshiko2/Movie_Data_Capture#810]
部分影片写到本地的文件夹/nfo信息是乱码

log大致记录：
Find movie [DKSW-284] metadata on website 'javbus'
actor+'/'+year+'_'+number+'_'+title
[+]Wrote!            JAV_output\多人作品\2011_DKSW-284_еҘіеӯҗж Ўз”ҹгҒ®е·Ёе°»гғҮгӮЈгғ«гғүгӮӘгғҠгғӢгғј\DKSW-284.nfo

Find movie [DOKS-139] metadata on website 'javbus'
Wrote!            JAV_output\MOE,й·№е®®гӮҠгӮҮгҒҶ,еӨ§ж§»гҒІгҒігҒҚ,ArisuпјҲйҲҙжңЁгҒӮгӮҠгҒҷпјү,жҰҠгҒӘгҒЎ,AliceпјҲйҲҙжңЁгҒӮгӮҠгҒҷпјү\2010_DOKS-139_зҫҺе°»гғҮгӮЈгғ«гғүгӮӘгғҠгғӢгғј\DOKS-139.nfo

Find movie [PSSD-274] metadata on website 'javbus'
Wrote!            JAV_output\гҒӮгҒҷгҒӢдјҠеӨ®,ArisuпјҲйҲҙжңЁгҒӮгӮҠгҒҷпјү,ж—©д№ҷеҘігғ«гӮӨ,гҒӨгҒјгҒҝ,AliceпјҲйҲҙжңЁгҒӮгӮҠгҒҷпјү\2013_PSSD-274_Beautiful Girl зҫҺе°‘еҘізі»еҪјеҘігҒЁгҒ®гғүгӮӯгғүгӮ\PSSD-274-CD1.nfo

昨天试着整理某目录下100多个文件，有三个是乱码
<img width="667" alt="Snipaste_2022-05-18_07-19-34" src="https://user-images.githubusercontent.com/43713125/168927612-a45f7a2f-1c90-4881-b90d-f5288449ee32.png">

但是去bus网站直接搜番号的话，是正常显示的

另外就是，这个【多人作品】的判断
DKSW-284这个就是最后放到多人作品里面，但是类似WNZ-243，DOKS-286，这类的，反而是把人物都列出来放到文件夹

<img width="676" alt="Snipaste_2022-05-18_07-16-47" src="https://user-images.githubusercontent.com/43713125/168927363-423646a6-50b1-41ef-b557-b8a138a7fa29.png">
<img width="664" alt="Snipaste_2022-05-18_07-18-00" src="https://user-images.githubusercontent.com/43713125/168927455-b420eda9-9c20-4df4-96af-5fa7d5a25287.png">

【多人作品】的判断，是否也加入一个侦测值？比如两人以上，三人以上可选的？

**Comment by cychou** [comment]
發現同樣問題
開DEBUG看時，是正常的
 tag            : ['单体作品', '剧情]
不過看nfo裡面就是亂碼 
  <tag>σìòΣ╜ôΣ╜£σôü</tag>
  <tag>σëºµâà</tag>

**Comment by Rebuilding127** [comment]
这个问题还没有解决吗？

**Comment by Karitsuki** [comment]
我自己是换了个站，好像只有javbus有这个问题

**Comment by Rebuilding127** [comment]
是的，我尝试过只用javdb做搜刮源，就没有乱码了
