### ISSUE TITLE
几个以前能刮削的番号6.1.4版本刮削不了了？

### ISSUE THREAD

**Issue by neatgz** [yoshiko2/Movie_Data_Capture#813]
日志如下所示：
MXGS-705 MXGS-791 HODV-20666 等番号半年以前刮削过一次是可以刮削的，今天想全新刮削一下，发现刮削不了。
再提供几个无法刮削的番号 KTSN-07  LUXU-467  MXGS-784  DS-006(MX3DS-006) ，以上提到的所有番号都是 流出无码版。
感谢！

> [*]================= Movie Data Capture =================
[*]                        6.1.4                         
[*]======================================================
[*] - Windows-10-10.0.19043-SP0 
[*] - AMD64 - Python-3.8.10
[*]======================================================
[*] - 严禁在墙内宣传本项目 - 
[*]======================================================
[+]Start at 2022-05-20 10:22:16
[+]Load Config file '\\192.168.2.22\Porn\Movie_Data_6.1.4\config.ini'.
[+]Enable debug
[+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30, stop_counter=5
[+]Find 1 movies.
[*]======================================================
[!]                - 100.% [1/1] -             10:22:17
[!] [HODV-20666] As Number Processing for '\\192.168.2.22\Porn\Movie_Data_6.1.4\HODV-20666-C-流出.mp4'
[+]select madou
list index out of range
[+]select javbus
[+]select airav
HODV-20666
local variable 'javbus_json' referenced before assignment
[+]select jav321
[-]Movie number has changed! [HODV-20666]->[None]
[*]======================================================
[+]Deleting empty folder X:\Movie_Data_6.1.4\failed
[+]Running time 0:00:04.911  End at 2022-05-20 10:22:21
[+]All finished!!!

> [*]================= Movie Data Capture =================
[*]                        6.1.4                         
[*]======================================================
[*] - Windows-10-10.0.19043-SP0 
[*] - AMD64 - Python-3.8.10
[*]======================================================
[*] - 严禁在墙内宣传本项目 - 
[*]======================================================
[+]Start at 2022-05-20 10:28:27
[+]Load Config file '\\192.168.2.22\Porn\Movie_Data_6.1.4\config.ini'.
[+]Enable debug
[+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30, stop_counter=5
[+]Find 1 movies.
[*]======================================================
[!]                - 100.% [1/1] -             10:28:28
[!] [MXGS-791] As Number Processing for '\\192.168.2.22\Porn\Movie_Data_6.1.4\MXGS-791-流出.mp4'
[+]select madou
list index out of range
[+]select javbus
[+]select airav
MXGS-791
local variable 'javbus_json' referenced before assignment
[+]select jav321
[-]Movie number has changed! [MXGS-791]->[None]
[*]======================================================
[+]Deleting empty folder X:\Movie_Data_6.1.4\failed
[+]Running time 0:00:06.621  End at 2022-05-20 10:28:34
[+]All finished!!!

**Comment by neatgz** [comment]
经过测试，以 MXGS-783 为代表的 MXGS 系列番号，使用 6.13  6.12 版本都可以刮削，但是使用 6.14 版本不能刮削。

**Comment by yoshiko2** [comment]
fixed
