### ISSUE TITLE
Proxy ERROR 但是不是代理有问题

### ISSUE THREAD

**Issue by Jyurineko** [yoshiko2/Movie_Data_Capture#815]
**Describe the bug 错误描述**
[*]================= Movie Data Capture =================
[*]                        6.1.4
[*]======================================================
[*] - Windows-10-10.0.19044-SP0
[*] - AMD64 - Python-3.9.12
[*]======================================================
[*] - 严禁在墙内宣传本项目 -
[*]======================================================
[+]Start at 2022-05-21 22:56:15
[+]Load Config file 'E:\迅雷下载\NormalMDC\config.ini'.
[+]Main Working mode ## 1: Scraping ## , multi_threading on, nfo_skip_days=30
[+]Find 4 movies.
[*]======================================================
[!]                - 25.0% [1/4] -             22:56:16
[!] [ARA-540] As Number Processing for 'E:\迅雷下载\MDCwait4sort\ARA-540.mp4'
[-]get_html_by_form() Proxy error! Please check your Proxy
[-]get_html_session() Proxy error! Please check your Proxy
[-]get_html_session() Proxy error! Please check your Proxy
[-] [E:\迅雷下载\MDCwait4sort\ARA-540.mp4] ERROR:
[-] list index out of range
[-]get_html_by_scraper() Proxy error! Please check your Proxy
[!]                - 50.0% [2/4] -             22:56:31
[!] [GANA-2701] As Number Processing for 'E:\迅雷下载\MDCwait4sort\GANA-2701.mp4'
[-]get_html_by_form() Proxy error! Please check your Proxy
[-]get_html_session() Proxy error! Please check your Proxy
[-]get_html_session() Proxy error! Please check your Proxy
[-] [E:\迅雷下载\MDCwait4sort\GANA-2701.mp4] ERROR:
[-] list index out of range
[-]get_html_by_scraper() Proxy error! Please check your Proxy
[!]                - 75.0% [3/4] -             22:56:45
[!] [MAAN-708] As Number Processing for 'E:\迅雷下载\MDCwait4sort\MAAN-708.mp4'
[-]get_html_by_form() Proxy error! Please check your Proxy
[-]get_html_session() Proxy error! Please check your Proxy
[-]get_html_session() Proxy error! Please check your Proxy
[-] [E:\迅雷下载\MDCwait4sort\MAAN-708.mp4] ERROR:
[-] list index out of range
[-]get_html_by_scraper() Proxy error! Please check your Proxy
[!]                - 100.% [4/4] -             22:56:59
[!] [SWEET-071] As Number Processing for 'E:\迅雷下载\MDCwait4sort\sweet-071.mp4'
[-]get_html_session() Proxy error! Please check your Proxy
[-]get_html_by_form() Proxy error! Please check your Proxy
[-]get_html_session() Proxy error! Please check your Proxy
[-] [E:\迅雷下载\MDCwait4sort\sweet-071.mp4] ERROR:
[-] list index out of range
[-]get_html_by_scraper() Proxy error! Please check your Proxy
[+]Running time 0:00:57.236  End at 2022-05-21 22:57:13
[+]All finished!!!
Press enter key exit, you can check the error message before you exit...

![image](https://user-images.githubusercontent.com/36675941/169657244-8b58add4-7539-4a1b-87c6-1693bdcb07a5.png)

代理开全局也是这样 http 和 sock5 都是一样的错误，其他番号搜刮都没什么问题，不会error，虽然也有乱码的情况，不过倒也算小问题，但是这个proxy问题是每一部都会有这三四条提醒
![image](https://user-images.githubusercontent.com/36675941/169657477-5e4ae77c-c247-4f87-b060-5c71378829bf.png)

![image](https://user-images.githubusercontent.com/36675941/169657308-ecd06115-3950-47d7-b9ee-5ac39e37bd05.png)

LOG没开...没法贴了

**Comment by lbbboy** [comment]
一样，用MDCx吧，等更新。

**Comment by Jyurineko** [comment]
兄弟你有没有遇到是同一个演员的，在网站上也能看到她名字，但是搜刮下来，有的能搜刮进同一个演员文件夹，有的却不能么？


> 一样，用MDCx吧，等更新。

**Comment by neatgz** [comment]
> 一样，用MDCx吧，等更新。
你好，问一下 MDCx 是什么？能给个链接吗，谢谢

**Comment by yoshiko2** [comment]
番号不全

**Comment by Jyurineko** [comment]
> 番号命名不全

哦哦和那个maan 和gana 前面一定要有200、300对吧？ 但是另外两个 像是sweet javdb看了和下载的文件 都没有说用什么数字前缀 就不知道怎么改名字了
