### ISSUE TITLE
6.2.1版本提示无法连接github

### ISSUE THREAD

**Issue by JohnGodzilla** [yoshiko2/Movie_Data_Capture#818]
**Describe the bug 错误描述**
Describe clearly and concisely what the error is
启动程序提示,无法连接github

网络环境:路由器层级科学上网,浏览器可访问google,github,尝试绕过墙内ip,gfwlist,全局模式,均无接.

**To Reproduce 如何重现BUG**
重现行为的步骤：

**Expected behavior 预期结果 **
对您期望发生的事情进行清晰简洁的描述

**Screenshots BUG发生截图**
 
<img width="714" alt="image" src="https://user-images.githubusercontent.com/6863411/170444132-add8a7a2-2ca5-412a-86b8-32ef8a7ac02c.png">

**Logs 日志**
[+]Start at 2022-05-26 15:51:28
[+]Load Config file '/Volumes/data/download/电影/config.ini'.
[+]Enable debug
[+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30
[!] ==================== ERROR ====================
[!]          Mapping Table Download FAILED         
[!]                    无法连接github                  
[!]                     请过几小时再试试                   
[-]      ------ AUTO EXIT AFTER 30s !!! ------     
Logs location:
Windows : C:/Users/username/.mlogs/
Linux/MacOS/BSD: /home/username/.mlogs/

**Running Env 运行环境**
 - OS : m1 macbook 和windows 都一样
 - Python Version : 3.x

**Comment by sagehou** [comment]
同样的问题 Mapping Table Download FAILED

**Comment by ntbowen** [comment]
Windows11有同样的问题，M1 MacOS正常

**Comment by jerryluo2022** [comment]
Windows10和 Ubuntu有同样的问题

**Comment by ntbowen** [comment]
> Windows11有同样的问题，M1 MacOS正常

M1 MacOS也出现同样的问题了

**Comment by ylongwang2782** [comment]
我也是win11，6.2.1版本，开启全局代理仍显示无法连接GitHub

**Comment by ylongwang2782** [comment]
> 我也是win11，6.2.1版本，开启全局代理仍显示无法连接GitHub

6.14版本同样无法连接GitHub
6.13版本能够正常使用

**Comment by VergilGao** [comment]
临时解决方案，运行程序之前先执行
mkdir -p ~/.local/share/mdc && cd ~/.local/share/mdc
wget https://raw.githubusercontent.com/yoshiko2/Movie_Data_Capture/master/MappingTable/mapping_actor.xml || true
wget https://raw.githubusercontent.com/yoshiko2/Movie_Data_Capture/master/MappingTable/mapping_info.xml || true
wget https://raw.githubusercontent.com/yoshiko2/Movie_Data_Capture/master/MappingTable/c_number.json || true

**Comment by ntbowen** [comment]
https://github.com/yoshiko2/Movie_Data_Capture/actions/runs/2391636488
解决了这个问题，在Windows11和MacOS测试通过。

**Comment by JohnGodzilla** [comment]
> https://github.com/yoshiko2/Movie_Data_Capture/actions/runs/2391636488 解决了这个问题，在Windows11和MacOS测试通过。

windows11验证通过,关闭issue

**Comment by yoshiko2** [comment]
fixed
