### ISSUE TITLE
由于目标计算机积极拒绝，无法连接。

### ISSUE THREAD

**Issue by jyh9521** [yoshiko2/Movie_Data_Capture#819]
![QQ截图20220528104519](https://user-images.githubusercontent.com/11244739/170806861-35e41c2f-c479-4dcb-8b61-2db15e230c7f.png)
确认梯子没问题，版本号6.2.2-r2，config已经重写。

**Comment by VergilGao** [comment]
程序有问题，稍等，正在调试

**Comment by VergilGao** [comment]
如果方便的话， 可以用这里编译出来的二进制测试 https://github.com/yoshiko2/Movie_Data_Capture/actions/runs/2400100953

**Comment by jyh9521** [comment]
> 如果方便的话， 可以用这里编译出来的二进制测试 https://github.com/yoshiko2/Movie_Data_Capture/actions/runs/2400100953

正常啦，感谢。
