### ISSUE TITLE
6.2.2-r3我这边是全部影片都不能刮削，确认梯子没问题 socks5 http 全局都不行 一直提示网络错误

### ISSUE THREAD

**Issue by racoonqg** [yoshiko2/Movie_Data_Capture#820]
运行状态如下

[*]================= Movie Data Capture =================
[*]                        6.2.2
[*]======================================================
[*] - Windows-10-10.0.22000-SP0
[*] - AMD64 - Python-3.9.13
[*]======================================================
[*] - 严禁在墙内宣传本项目 -
[*]======================================================
[+]Start at 2022-05-28 12:10:04
[+]Load Config file 'E:\Y\config.ini'.
[+]Main Working mode ## 1: Scraping ## , multi_threading on, stop_counter=50
[+]Find 4 movies.
[*]======================================================
[!]                - 25.0% [1/4] -             12:10:06
[!] [420ERK-010] As Number Processing for 'E:\Y\420ERK-010.mp4'
[+]Find movie [420ERK-010] metadata on website 'mgstage'
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[-]Connect Failed! Please check your Proxy or Network!
[-] [E:\Y\420ERK-010.mp4] ERROR:
[-] Connect Failed
[!]                - 50.0% [2/4] -             12:10:13
[!] [ABW-238] As Number Processing for 'E:\Y\ABW-238.mp4'
[-]Connect retry 1/3
[+]Find movie [ABW-238] metadata on website 'javbus'
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[-]Connect Failed! Please check your Proxy or Network!
[-] [E:\Y\ABW-238.mp4] ERROR:
[-] Connect Failed
[!]                - 75.0% [3/4] -             12:10:31
[!] [DRKC-002] As Number Processing for 'E:\Y\drkc-002.mp4'
[+]Find movie [DRKC-002] metadata on website 'javbus'
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[-]Connect Failed! Please check your Proxy or Network!
[-] [E:\Y\drkc-002.mp4] ERROR:
[-] Connect Failed
[!]                - 100.% [4/4] -             12:10:42
[!] [KBI-077] As Number Processing for 'E:\Y\KBI-077.mp4'
[+]Find movie [KBI-077] metadata on website 'javbus'
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))
[-]Connect Failed! Please check your Proxy or Network!
[-] [E:\Y\KBI-077.mp4] ERROR:
[-] Connect Failed
[+]Deleting empty folder E:\Y\failed
[+]Running time 0:00:51.203  End at 2022-05-28 12:10:56
[+]All finished!!!
Log file 'C:\Users\xiaoh\.mlogs\mdc_20220528T121004.txt' saved.
All movies:4  processed:4  successes:0  remain:0  Elapsed time 0:00:51
Press enter key exit, you can check the error message before you exit...

**Comment by VergilGao** [comment]
修复中

**Comment by VergilGao** [comment]
如果方便的话， 可以用这里编译出来的二进制测试 https://github.com/yoshiko2/Movie_Data_Capture/actions/runs/2400100953

**Comment by racoonqg** [comment]
测试这个还是不行，问题一模一样

**Comment by VergilGao** [comment]
代理设置成你原本的状态

**Comment by racoonqg** [comment]
对 隔壁不是这个问题，我换了两个不同的tz都是一样的 哈哈哈

**Comment by yoshiko2** [comment]
fixed in new version
