### ISSUE TITLE
视频识别，并整理好但是没有下载封面和nfo文件

### ISSUE THREAD

**Issue by yilin101** [yoshiko2/Movie_Data_Capture#823]
**Describe the bug 错误描述**
Describe clearly and concisely what the error is
视频识别，并整理好但是没有下载封面和nfo文件

**To Reproduce 如何重现BUG**
重现行为的步骤：

**Expected behavior 预期结果 **
对您期望发生的事情进行清晰简洁的描述

**Screenshots BUG发生截图**
 
**Logs 日志**
Copy all or key content of the file to this
视频识别，并整理好但是没有下载封面和nfo文件
[*]================= Movie Data Capture =================
[*]                        6.2.2                         
[*]======================================================
[*] - Linux-3.10.108-x86_64-with 
[*] - x86_64 - Python-3.9.13
[*]======================================================
[*] - 严禁在墙内宣传本项目 - 
[*]======================================================
[+]Start at 2022-05-28 17:08:09
[+]Load Config file '/config/mdc.ini'.
[+]Main Working mode ## 2: Organizing ## , nfo_skip_days=30
[+]Find 27 movies.
[*]======================================================
[!]               - 3.70% [1/27] -             17:08:12
[!] [BUR-435A] As Number Processing for '/data/JAV/BUR-435A.mkv'
[-]get_html_by_scraper() failed. SOCKSHTTPSConnectionPool(host='javdb38.com', port=443): Max retries exceeded with url: /search?q=BUR-435A&f=all (Caused by ResponseError('too many 503 error responses'))
[-]Movie Number or Title not found!
[*]======================================================
[!]               - 7.40% [2/27] -             17:09:28
[!] [BUR-435B] As Number Processing for '/data/JAV/BUR-435B.mkv'
[-]get_html_by_scraper() failed. SOCKSHTTPSConnectionPool(host='javdb38.com', port=443): Max retries exceeded with url: /search?q=BUR-435B&f=all (Caused by ResponseError('too many 503 error responses'))
[-]Movie Number or Title not found!
[*]======================================================
[!]               - 11.1% [3/27] -             17:10:43
[!] [BUR-435C] As Number Processing for '/data/JAV/BUR-435C.mkv'
[-]get_html_by_scraper() failed. SOCKSHTTPSConnectionPool(host='javdb.com', port=443): Max retries exceeded with url: /search?q=BUR-435C&f=all (Caused by ResponseError('too many 503 error responses'))
[-]Movie Number or Title not found!
[*]======================================================
[!]               - 14.8% [4/27] -             17:11:57
[!] [FC2-2497913] As Number Processing for '/data/JAV/FC2-PPV-2497913.mp4'
[-]get_html_by_scraper() failed. SOCKSHTTPSConnectionPool(host='javdb38.com', port=443): Max retries exceeded with url: /search?q=FC2-2497913&f=all (Caused by ResponseError('too many 503 error responses'))
[-]Movie Number or Title not found!
[*]======================================================
[!]               - 18.5% [5/27] -             17:13:37
[!] [FC2-2497913] As Number Processing for '/data/JAV/FC2-PPV-2497913_2.mp4'
[-]get_html_by_scraper() failed. SOCKSHTTPSConnectionPool(host='javdb40.com', port=443): Max retries exceeded with url: /search?q=FC2-2497913&f=all (Caused by ResponseError('too many 503 error responses'))
[-]Movie Number or Title not found!
[*]======================================================
[!]               - 22.2% [6/27] -             17:15:10
[!] [FLNS-113] As Number Processing for '/data/JAV/FLNS-113.mp4'
[-]get_html_by_scraper() failed. SOCKSHTTPSConnectionPool(host='javdb.com', port=443): Max retries exceeded with url: /search?q=FLNS-113&f=all (Caused by ResponseError('too many 503 error responses'))
[-]Movie Number or Title not found!
[*]======================================================
[!]               - 25.9% [7/27] -             17:16:28
[!] [FLNS-114] As Number Processing for '/data/JAV/FLNS-114.mp4'
[-]get_html_by_scraper() failed. SOCKSHTTPSConnectionPool(host='javdb.com', port=443): Max retries exceeded with url: /search?q=FLNS-114&f=all (Caused by ResponseError('too many 503 error responses'))
[-]Movie Number or Title not found!
[*]======================================================
[!]               - 29.6% [8/27] -             17:17:43
[!] [STARS-086] As Number Processing for '/data/JAV/STARS-086.mp4'
[+]Find movie [STARS-086] metadata on website 'javbus'
[-] [/data/JAV/STARS-086.mp4] ERROR:
[-] File Exists on destination path, we will never overwriting.
[!]               - 33.3% [9/27] -             17:18:02
[!] [GETCHU-4042103] As Number Processing for '/data/JAV/GETCHU-4042103/GETCHU-4042103.mp4'
[+]Find movie [GETCHU-4042103] metadata on website 'getchu'
[*]======================================================
[!]              - 37.0% [10/27] -             17:18:27
[!] [GETCHU-911772] As Number Processing for '/data/JAV/KADOKAWA/GETCHU-911772/GETCHU-911772.mp4'
[-]get_html_by_scraper() failed. SOCKSHTTPSConnectionPool(host='javdb38.com', port=443): Max retries exceeded with url: /search?q=GETCHU-911772&f=all (Caused by ResponseError('too many 503 error responses'))
[-]Movie Number or Title not found!
[*]======================================================
[!]              - 40.7% [11/27] -             17:19:36
[!] [SIRO-4823] As Number Processing for '/data/JAV/SIRO-4823/hhd800.com@SIRO-4823.mp4'
[+]Find movie [SIRO-4823] metadata on website 'mgstage'
[*]======================================================
[!]              - 44.4% [12/27] -             17:19:50
[!] [FC2-2552104] As Number Processing for '/data/JAV/deruデるking/FC2-2552104/FC2-2552104.mp4'
[+]Find movie [FC2-2552104] metadata on website 'fc2'
[*]======================================================
[!]              - 48.1% [13/27] -             17:20:27
[!] [zzpp01', 'com@mkck306b] As Number Processing for '/data/JAV/zzpp01.com@mkck306b/zzpp01.com@mkck306b.mp4'
[-]get_html_by_scraper() failed. SOCKSHTTPSConnectionPool(host='javdb.com', port=443): Max retries exceeded with url: /search?q=ZZPP01',%20'COM@MKCK306B&f=all (Caused by ResponseError('too many 503 error responses'))
[-]Movie Number or Title not found!
[*]======================================================
[!]              - 51.8% [14/27] -             17:21:44
[!] [APAA-382] As Number Processing for '/data/JAV/ひなた澪/APAA-382/APAA-382.mp4'
[+]Find movie [APAA-382] metadata on website 'javbus'
[*]======================================================
[!]              - 55.5% [15/27] -             17:22:08
[!] [GETCHU-984478] As Number Processing for '/data/JAV/キングレコード/GETCHU-984478/GETCHU-984478.mp4'
[-]get_html_by_scraper() failed. SOCKSHTTPSConnectionPool(host='javdb39.com', port=443): Max retries exceeded with url: /search?q=GETCHU-984478&f=all (Caused by ResponseError('too many 503 error responses'))
[-]Movie Number or Title not found!
[*]======================================================
[!]              - 59.2% [16/27] -             17:23:16
[!] [GETCHU-677570] As Number Processing for '/data/JAV/バンダイビジュアル/GETCHU-677570/GETCHU-677570.mp4'
[-]get_html_by_scraper() failed. SOCKSHTTPSConnectionPool(host='javdb.com', port=443): Max retries exceeded with url: /search?q=GETCHU-677570&f=all (Caused by ResponseError('too many 503 error responses'))
[-]Movie Number or Title not found!
[*]======================================================
[!]              - 62.9% [17/27] -             17:24:28
[!] [FSDSS-407] As Number Processing for '/data/JAV/夏木りん/FSDSS-407/FSDSS-407.mp4'
[+]Find movie [FSDSS-407] metadata on website 'javbus'
[*]======================================================
[!]              - 66.6% [18/27] -             17:24:51
[!] [STARS-576] As Number Processing for '/data/JAV/工藤ゆら/STARS-576/STARS-576.mp4'
[+]Find movie [STARS-576] metadata on website 'javbus'
[*]======================================================
[!]              - 70.3% [19/27] -             17:25:23
[!] [FSDSS-416] As Number Processing for '/data/JAV/時田亜美/FSDSS-416/FSDSS-416.mp4'
[+]Find movie [FSDSS-416] metadata on website 'javbus'
[*]======================================================
[!]              - 74.0% [20/27] -             17:25:46
[!] [FC2-2714057] As Number Processing for '/data/JAV/暗黒王子/FC2-2714057/FC2-2714057.mp4'
[+]Find movie [FC2-2714057] metadata on website 'fc2'
[*]======================================================
[!]              - 77.7% [21/27] -             17:26:21
[!] [STARS-562] As Number Processing for '/data/JAV/月乃ひな/STARS-562/STARS-562.mp4'
[+]Find movie [STARS-562] metadata on website 'javbus'
[*]======================================================
[!]              - 81.4% [22/27] -             17:26:44
[!] [PKPD-188] As Number Processing for '/data/JAV/根本佳澄/PKPD-188/PKPD-188.mp4'
[+]Find movie [PKPD-188] metadata on website 'javbus'
[*]======================================================
[!]              - 85.1% [23/27] -             17:27:08
[!] [KBI-073] As Number Processing for '/data/JAV/桂木凛/KBI-073/KBI-073-C.mp4'
[+]Find movie [KBI-073] metadata on website 'javbus'
[-] [/data/JAV/桂木凛/KBI-073/KBI-073-C.mp4] ERROR:
[-] [Errno 2] No such file or directory: 'JAV_output/桂木凛/KBI-073/KBI-073-C-thumb.jpg'
[!]              - 88.8% [24/27] -             17:27:30
[!] [KBI-076] As Number Processing for '/data/JAV/桂木凛/KBI-076/KBI-076.mp4'
[+]Find movie [KBI-076] metadata on website 'javbus'
[*]======================================================
[!]              - 92.5% [25/27] -             17:27:48
[!] [MEYD-033] As Number Processing for '/data/JAV/森沢かな（飯岡かなこ）/MEYD-033/MEYD-033-流出.mp4'
[+]Find movie [MEYD-033] metadata on website 'javbus'
[-] [/data/JAV/森沢かな（飯岡かなこ）/MEYD-033/MEYD-033-流出.mp4] ERROR:
[-] [Errno 2] No such file or directory: 'JAV_output/森沢かな（飯岡かなこ）/MEYD-033/MEYD-033-流出-thumb.jpg'
[!]              - 96.2% [26/27] -             17:28:15
[!] [DTT-093] As Number Processing for '/data/JAV/真木今日子/DTT-093/DTT-093.mp4'
[+]Find movie [DTT-093] metadata on website 'javbus'
[*]======================================================
[!]              - 100.% [27/27] -             17:28:35
[!] [FSDSS-448] As Number Processing for '/data/JAV/逢月ひまり/FSDSS-448/FSDSS-448.mp4'
[+]Find movie [FSDSS-448] metadata on website 'javbus'
[*]======================================================
[+]Deleting empty folder /data/JAV/GETCHU-4042103
[+]Deleting empty folder /data/JAV/SIRO-4823
[+]Deleting empty folder /data/JAV/deruデるking/FC2-2552104
[+]Deleting empty folder /data/JAV/deruデるking
[+]Deleting empty folder /data/JAV/ひなた澪/APAA-382
[+]Deleting empty folder /data/JAV/ひなた澪
[+]Deleting empty folder /data/JAV/夏木りん/FSDSS-407
[+]Deleting empty folder /data/JAV/夏木りん
[+]Deleting empty folder /data/JAV/工藤ゆら/STARS-576
[+]Deleting empty folder /data/JAV/工藤ゆら
[+]Deleting empty folder /data/JAV/時田亜美/FSDSS-416
[+]Deleting empty folder /data/JAV/時田亜美
[+]Deleting empty folder /data/JAV/暗黒王子/FC2-2714057
[+]Deleting empty folder /data/JAV/暗黒王子
[+]Deleting empty folder /data/JAV/月乃ひな/STARS-562
[+]Deleting empty folder /data/JAV/月乃ひな
[+]Deleting empty folder /data/JAV/根本佳澄/PKPD-188
[+]Deleting empty folder /data/JAV/根本佳澄
[+]Deleting empty folder /data/JAV/桂木凛/KBI-073
[+]Deleting empty folder /data/JAV/桂木凛/KBI-076
[+]Deleting empty folder /data/JAV/桂木凛
[+]Deleting empty folder /data/JAV/森沢かな（飯岡かなこ）/MEYD-033
[+]Deleting empty folder /data/JAV/森沢かな（飯岡かなこ）
[+]Deleting empty folder /data/JAV/真木今日子/DTT-093
[+]Deleting empty folder /data/JAV/真木今日子
[+]Deleting empty folder /data/JAV/逢月ひまり/FSDSS-448
[+]Deleting empty folder /data/JAV/逢月ひまり
[+]Deleting empty folder /data/failed
[+]Running time 0:21:14.506  End at 2022-05-28 17:29:24
[+]All finished!!!

Logs location:
Windows : C:/Users/username/.mlogs/
Linux/MacOS/BSD: /home/username/.mlogs/

**Running Env 运行环境**
 - OS :
 - Python Version : 3.x

**Comment by yoshiko2** [comment]
远古内核
