### ISSUE TITLE
网络连接失败

### ISSUE THREAD

**Issue by duchanghexuhe** [yoshiko2/Movie_Data_Capture#830]
[*]================= Movie Data Capture =================
[*]                        6.2.2
[*]======================================================
[*] - Windows-10-10.0.22000-SP0
[*] - AMD64 - Python-3.9.13
[*]======================================================
[*] - 严禁在墙内宣传本项目 -
[*]======================================================
[+]Start at 2022-06-13 19:39:27
[+]Load Config file '\\SHIHAONAS\Pornhub\config.ini'.
[+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
[-]Connect Failed! Please check your Proxy or Network!
[!] ==================== ERROR ====================
[!]          Mapping Table Download FAILED
[!]                    无法连接github
[!]                     请过几小时再试试
[!] Connect Failed
[-]      ------ AUTO EXIT AFTER 30s !!! ------
===============================================================
昨晚刮削100部左右,后来全是网络连接失败,本地代理与网关代理全试过不行,试了下ping api.github.com 无法ping通.

**Comment by 820Reverse** [comment]
我也遇到这个问题，ping不通，但是直接网页打开https://api.github.com/和https://www.github.com/都是能访问的。我是路由器全局代理的。

**Comment by 820Reverse** [comment]
这里面的提示无法连接github其实是raw.githubusercontent.com，你可以试着添加hosts:
185.199.108.133 raw.githubusercontent.com
来解决
