### ISSUE TITLE
请教2个问题，一个是iterals的规则，一个是对已经文件夹/文件名的识别问题

### ISSUE THREAD

**Issue by tinyvane** [yoshiko2/Movie_Data_Capture#831]
请教2个问题，第一个问题：

escape下面的literals=后面是什么格式？比如iterals=\()请问这句话怎么理解？

是删掉所有文件名字的\()三个字符么？这个斜杠是转义符么？

假如写参数是iterals=\456,\654，是不是就会删除文件名字的456和654呢？

第二个问题：

我之前下载的电影使用qbittorrent，规则是为每个电影单独保存到一个目录内。

比如，我某个文件夹名字带着CN的后缀，标识电影是中文字幕，MDC有没有参数，可以识别这些文件夹，在整理的时候，默认给电影加上“字幕”的标签？谢谢

第二个问题我上传一个图片作为参考，谢谢大家。
![photo_2022-06-14_11-00-42](https://user-images.githubusercontent.com/150694/173484449-8432fc5f-40ea-4b0a-bd6e-93d7f3f54338.jpg)

上图这些文件夹，我还没敢整理，怕整理完了，字幕标签没有了。

**Comment by mela93** [comment]
第一个问题：literals=后面是什么就是忽略什么，比如是\()就是这三个符号都忽略
第二个问题：海报会加上中文的水印，可以复制一两部电影到本地测试一下
