### ISSUE TITLE
6.2.2的版本无法从Javdb获取用户评分

### ISSUE THREAD

**Issue by wind-snow-moon** [yoshiko2/Movie_Data_Capture#838]
6.2.2版本从Javdb抓取数据输出的nfo文件中没有包含ratings字段，即无法从Javdb获取用户评分

**Comment by ahqiuusa** [comment]
Javdb不是老早就不能用了吗?怎么还能搜刮

**Comment by wind-snow-moon** [comment]
Javdb现在还可以搜刮，只是无法获取到用户评分

**Comment by ahqiuusa** [comment]
你用的是哪个版本?

**Comment by wind-snow-moon** [comment]
最新的版本6.2.2

**Comment by ahqiuusa** [comment]
确定是javdb吗?你往前翻老早就不行了.
查一下nfo文件或者改一下config.ini试试看**只从**javdb搜刮
website=javdb

**Comment by wind-snow-moon** [comment]
发现问题在哪里了，javdb的页面改变，修改core.py的两行源代码就可以了
                f_rating = json_data['用户评分']
                uc = json_data['评分人数']
修改为：               
                f_rating = json_data['userrating']
                uc = json_data['uservotes']
