### ISSUE TITLE
VR片JAVBUS网站封面刮削建议

### ISSUE THREAD

**Issue by physicsmeGH** [yoshiko2/Movie_Data_Capture#839]
VR片的封面图一般是横向比例的，如果按照正常片光盘封面只切右半，通常会截出很多不知所谓的图。（不仅VR片，有些SOD社的片子，STARS开头的，也有这个问题） 例：[KIVR-025](https://www.javbus.com/KIVR-025)  [STARS-156](https://www.javbus.com/STARS-156)
但是我发现一个规律，javbus网站上面，VR片的第一个"样品图像"（也就是本工具归类为ExtraFanart的图片）一般就是片子的竖向封面。
在Javbus类的getCover函数里面加一个简单的Tag判断（Tag里面有没有VR字样），如果有的话就直接把第一个ExtraFanart作为封面，如此可以大幅改善VR片的封面刮削体验。

```
    def getCover(self, htmltree):
        tagList = self.getTags(htmltree)
        for tag in tagList:
            if 'VR' in tag:
                return super().getExtrafanart(htmltree)[0]    
        return urljoin("https://www.javbus.com", super().getCover(htmltree)) 
```

**Comment by hejianjun** [comment]
建议提个合并请求看看

**Comment by WarpTraveller** [comment]
这样改会少正常封面，而且剪切还是会有问题

**Comment by WarpTraveller** [comment]
这样改会少正常封面，而且剪切还是会有问题
