### ISSUE TITLE
同一个番号有多部影片的情况

### ISSUE THREAD

**Issue by colaKot** [yoshiko2/Movie_Data_Capture#844]
例如影片 SRXV-465
有两个番号,默认使用了第一个,但是我的其实是第二个影片,这种情况下要怎么处理?

**Comment by NinetyFour95** [comment]
我遇到了同样的问题，不过我的是第一个，总是使用第二个。过来找解决办法，找到了你这个问题 。

**Comment by hejianjun** [comment]
-cd1 -cd2
