### ISSUE TITLE
麻豆现在不能搜刮了吗？

### ISSUE THREAD

**Issue by gwll54** [yoshiko2/Movie_Data_Capture#850]
**Describe the bug 错误描述**
Describe clearly and concisely what the error is
清晰简洁地描述错误是什么

**To Reproduce 如何重现BUG**
重现行为的步骤：

**Expected behavior 预期结果 **
对您期望发生的事情进行清晰简洁的描述

**Screenshots BUG发生截图**
 
**Logs 日志**
Copy all or key content of the file to this
复制文件的全部或关键内容到此
Logs location:
Windows : C:/Users/username/.mlogs/
Linux/MacOS/BSD: /home/username/.mlogs/

**Running Env 运行环境**
 - OS :
 - Python Version : 3.x

**Comment by hejianjun** [comment]
我测试了一下，应该还可以，但是这个网站支持前缀不多
