### ISSUE TITLE
内置的解析域名失效

### ISSUE THREAD

**Issue by makergit365** [yoshiko2/Movie_Data_Capture#854]
多个内置域名失效，我网络环境没问题，里面有些连接失效的我手动打开也发现没了，大家都是梯子出来的，能不能都用原域名

**Comment by mashutong** [comment]
确实有这个问题，建议和以前一样手动设置网址

**Comment by WLYseven** [comment]
搞个参数，可以设置域名就好了。

**Comment by mela93** [comment]
刮削的站点网址可配置吗？

**Comment by mela93** [comment]
我粗略翻了一下以前的版本好像没有相关的设置，有大概的时间点或者版本号吗？

> 确实有这个问题，建议和以前一样手动设置网址
