### ISSUE TITLE
检索待刮削视频文件时，误识别后缀为.mp4的文件夹

### ISSUE THREAD

**Issue by whiskysheep** [yoshiko2/Movie_Data_Capture#857]
由于个人使用习惯，对于下载的单个视频文件，会利用Qbit在下载完成后自动建立同名文件夹，导致会出现/inbox/xxx.mp4/xxx.mp4这样的结构。在刮削完成后，会将xxx.mp4整个文件夹移动至目标文件夹，导致emby无法识别。

建议在检索时增加文件夹判断。

**Comment by yoshiko2** [comment]
那就改变你的个人习惯

**Comment by WarpTraveller** [comment]
配置文件好像可以设置目录结构吧
