### ISSUE TITLE
分集会导致图片加载不进emby里

### ISSUE THREAD

**Issue by aiwandexiong** [yoshiko2/Movie_Data_Capture#868]
**Describe the bug 错误描述**
Describe clearly and concisely what the error is
分集会导致图片加载不进emby里

**To Reproduce 如何重现BUG**
重现行为的步骤：
1. 文件名为xxxx-xxx-cd1,xxxx-xxx-cd2
2. 刮削后图片下载正常，但是emby并不会加载

**Expected behavior 预期结果 **
对您期望发生的事情进行清晰简洁的描述

**Screenshots BUG发生截图**

**Logs 日志**
Copy all or key content of the file to this
+]Start at 2022-09-03 15:36:07
[+]Load Config file 'C:\Users\26215\mdc.ini'.
[!]Enable hard link
[+]Main Working mode ## 1: Scraping ## , multi_threading on, nfo_skip_days=30
[!]Skip 1 movies in failed list 'D:\迅雷下载\av\failed\failed_list.txt'.
[!]Skip 10 movies in success folder 'D:\迅雷下载\av\JAV_output' who's .nfo modified within 30 days.
[+]Find 2 movies.
[*]======================================================
[!]                - 50.0% [1/2] -             15:36:10
[!] [NHDTA-309] As Number Processing for 'D:\迅雷下载\av\NHDTA-309-cd1.wmv'
[+]select madou
[+]select javdb
[!]Storyline线程池模式运行4个任务共耗时(含启动开销)35.802秒，结束于15:36:49，[选中avno1字数:88]，airav字数:88，airavwiki字数:88，xcity字数:159
[+]Find movie [NHDTA-309] metadata on website 'javdb'
[+]Image Downloaded! NHDTA-309-fanart.jpg
[+]Image Cutted!     NHDTA-309-poster.jpg
[+]Wrote!            JAV_output\木村つな\NHDTA-309\NHDTA-309-CD1.nfo
[*]======================================================
[!]                - 100.% [2/2] -             15:37:01
[!] [NHDTA-309] As Number Processing for 'D:\迅雷下载\av\NHDTA-309-cd2.wmv'
[+]select madou
[+]select javdb
[!]Storyline线程池模式运行4个任务共耗时(含启动开销)6.936秒，结束于15:37:12，[选中avno1字数:88]，airav字数:88，airavwiki字数:88，xcity字数:159
[+]Find movie [NHDTA-309] metadata on website 'javdb'
[+]Image Cutted!     NHDTA-309-poster.jpg
[+]Wrote!            JAV_output\木村つな\NHDTA-309\NHDTA-309-CD2.nfo
**Running Env 运行环境**
 - OS :win10
 - Python Version : 3.9.1.2

**Comment by FriedBrownRice** [comment]
我也遇到了这个问题

**Comment by bruceyang233** [comment]
好好看看wiki

**Comment by fnscar** [comment]
multi_part_fanart=1
