### ISSUE TITLE
6.3.2版本网络硬盘映射时，输出目录路径错误

### ISSUE THREAD

**Issue by rederror123** [yoshiko2/Movie_Data_Capture#877]
网络硬盘映射（SMB协议）成功输出时，封面切图及缩略图目录路径出错。
nfo文件输出正常

`[+]Successfully downloaded 10 extrafanarts.`
`[Errno 2] No such file or directory: 'JAV_output\\橋本ありな\\FSDSS-274\\FSDSS-274-C-fanart.jpg'`
`[-]Cover cut failed!`
`[-] [\\DiskStation\Download\fsdss-274ch\fsdss-274ch.mp4] ERROR:`
`[-] [Errno 2] No such file or directory: 'JAV_output\\橋本ありな\\FSDSS-274\\FSDSS-274-C-thumb.jpg'`
`[-]Cover cut failed!`
`[+]Wrote!            JAV_output\橋本ありな\JFSDSS-274\FSDSS-274-C.nfo`

 - OS :win10

**Comment by asukahan** [comment]
[-]Cover cut failed!
[+]Wrote! JAV_output\橋本ありな\JFSDSS-274\FSDSS-274-C.nfo
的目录是：

JAV_output\橋本ありな\JFSDSS-274


JPG的目录是：
JAV_output\橋本ありな\FSDSS-274

你这个log没改过吗？怎么两个目录不一样？
