### ISSUE TITLE
MD开头的番号会识别当成madou的格式处理，欧美类番号无法刮削

### ISSUE THREAD

**Issue by exocentricD** [yoshiko2/Movie_Data_Capture#884]
**Describe the bug 错误描述**
 - 1.MD开头的番号会识别当成madou的格式处理，如MDVR-001会处理成MDVR001，MDTM-001当成MDTM001，其他格式命名正常刮削
 - 2.Vixen.22.01.01之类的欧美番号无法识别，直接“Movie Number or Title not found!”，其他非欧美非MD格式命名正常刮削

**To Reproduce 如何重现BUG**
 - 使用"MDVR-XXX","Vixen.XX.XX.XX"等番号

**Expected behavior 预期结果 **
 - 正常刮削
 
**Logs 日志**
```
[!]               - 20.0% [6/30] -             03:11:44
[!] [vixen.19.11.10] As Number Processing for '/data/vixen.19.11.10.mp4'
[+]select javdb
[-]Movie Number or Title not found!
[*]======================================================
[!]               - 23.3% [7/30] -             03:11:50
[!] [MDTM0571] As Number Processing for '/data/MDTM-571.mkv'
[+]select javdb
[-]Movie Number [MDTM0571] not found!
[-]Movie Number not found!
```

**Running Env 运行环境**
 - 出现问题的版本 : Docker 6.3.1的版本，Windows 11 6.3.2的版本 均出现上述问题
 - Python Version : 3.x

**Comment by hejianjun** [comment]
MDTM已经处理了 #903
