### ISSUE TITLE
"zsh: illegal hardware instruction" on Apple M1 using ver.6.3.2

### ISSUE THREAD

**Issue by zshowing** [yoshiko2/Movie_Data_Capture#887]
**Describe the bug 错误描述**
出现 zsh: illegal hardware instruction 提示，程序终止
之前6.2.2版本正常

**To Reproduce 如何重现BUG**
直接运行

**Screenshots BUG发生截图**
JAV % ./Movie_Data_Capture
[*]================= Movie Data Capture =================
[*]                        6.3.2                         
[*]======================================================
[*] - macOS-10.16-x86_64-i386-64bit 
[*] - x86_64 - Python-3.9.13
[*]======================================================
[*] - 严禁在墙内宣传本项目 - 
[*]======================================================
[+]Start at 2022-10-03 23:30:19
[+]Load Config file '/Volumes/Matrix/JAV/config.ini'.
[+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30
[+]Find 7 movies.
[*]======================================================
[!]                - 14.2% [1/7] -             23:30:20
[!] [SMD-115] As Number Processing for '/Volumes/Matrix/JAV/smd-115.mp4'
[+]Find movie [SMD-115] metadata on website 'javbus'
[+]Successfully downloaded 1 actor photo.
[+]Use model         hog
zsh: illegal hardware instruction  ./Movie_Data_Capture

**Comment by zshowing** [comment]
搜索了一下之前的issue，在ini文件中把人脸识别模型的参数留空解决了问题。
即locations_model=

**Comment by WWWWM03** [comment]
感谢大佬！好久的问题终于解决了！
