### ISSUE TITLE
tag元数据刮削功能建议

### ISSUE THREAD

**Issue by tecsar9000** [yoshiko2/Movie_Data_Capture#893]
希望能增加一个tag过滤的功能，现在刮削会把所有的tag都刮削到，然而很多tag都是毫无意义的，导致在媒体库tag分类出现大量垃圾词缀，影响正常使用。
建议添加一个只刮削固定tag的功能，其他tag一律丢弃。很多时候比如系列、發行商、製作商、导演、[配信専用][DMM獨家]这种tag除了给媒体库分类碍事以外毫无意义，只有像[美少女] [巨乳]这种tag才有刮削的意义吧

**Comment by mark5231** [comment]
https://github.com/yoshiko2/Movie_Data_Capture/pull/916#issue-1437642548
https://github.com/yoshiko2/Movie_Data_Capture/pull/915#issue-1437552535

**Comment by tecsar9000** [comment]
上面两个commit都只是对个别tag的。还是建议添加一个用户自行设定tag过滤规则的功能，由用户自己选择过滤，比如对我来说，分类只是用来快速定位感兴趣的片，因此系列、發行商、製作商、导演、配信専用、首次亮相、DMM獨家这些tag都没有作用，相信应该不止我一个觉得这种tag在分类选项里刷屏很烦人吧？

**Comment by Marce1ek** [comment]
拿源码改呀 不想要的tag改成删除就行了

**Comment by Marce1ek** [comment]
用文本编辑器打开就可以改

**Comment by Marce1ek** [comment]
改一次就行了 怕的话就备份一个留着

**Comment by Marce1ek** [comment]
![QQ截图20221206165256](https://user-images.githubusercontent.com/99329516/205864909-9a14e039-2df1-414e-9a99-8f77151d7918.jpg)
config里这一项改大一点 不然会重新下载 之前忘了

**Comment by Lesaca** [comment]
确认tag多了有点乱,是否可以设置,当tag不满足那个规则文件里的条件,就不添加tag到元数据中,现在如果规则中没有会添加日文的进去,看着比较乱,这样就实现了过滤的功能,用户只需要在那个文件选择一些自己想要匹配的规则就可以了
