### ISSUE TITLE
可否恢复忽略120MB以下视频文件的功能？

### ISSUE THREAD

**Issue by fnscar** [yoshiko2/Movie_Data_Capture#896]
5月20号的提交取消了这个功能，不知是出于什么样的考虑？
我自己倒是用得挺顺，下载时不用为每个种子取消勾选广告，可以全部下载完成、正片整理进JAV_output目录后把剩下的文件全部删除。
现在得在刮削整理前就把每个种子里的广告删干净。。。

**Comment by hejianjun** [comment]
番号的范围不好确定，有些番号很奇葩的

**Comment by hejianjun** [comment]
我觉得应该是下载工具提供屏蔽的功能而不是刮削工具

**Comment by fnscar** [comment]
qbittorrent 4.5加入了flie name filter/blacklist功能
好在目前sht的广告视频文件名相对固定。
