### ISSUE TITLE
怎么越更新越慢啊

### ISSUE THREAD

**Issue by Yafeiml** [yoshiko2/Movie_Data_Capture#899]
HTTPSConnectionPool(host='www.buscdn.fun', port=443): Max retries exceeded with url: /DASS-054 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

[-]HTTPSConnectionPool(host='www.busjav.fun', port=443): Max retries exceeded with url: /DASS-058 (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)')))

都是些奇奇怪怪的域名，应该是某些站的镜像吧，关键是这些放到浏览器都打不开，而原站都能打开，一般能用这个都能自备梯子了吧，就不要搞这些其奇怪怪的镜像域名上来了吧。。。

**Comment by yilin101** [comment]
应该是ip被封了   如果能把域名全部列出来  可以想办法通过clash分流一下

**Comment by Yafeiml** [comment]
> 应该是ip被封了 如果能把域名全部列出来 可以想办法通过clash分流一下

不是的，因为openwrt使用的中国列表以外，这些镜像站域名走的就是代理，但是无法访问，不过已经解决了，把这些域名全部删除又编译了下，现在快多了。

**Comment by yilin101** [comment]
> 

就是ip被对方封了吧

**Comment by yilin101** [comment]
> 额，是被对方封了么，，那可能是目前用的梯子问题，回头换个测试下。

是因为访频率太高了 被对方封了你当前梯子的IP

**Comment by Bluefissure** [comment]
https://github.com/yoshiko2/Movie_Data_Capture/blob/a650e5483192a113c2aba971d8a3aa47841f34fc/scrapinglib/javbus.py#L41
都无法访问，域名好像都掉了，这个意义是什么？封IP的问题不应该通过代理池解决吗

**Comment by Yafeiml** [comment]
> https://github.com/yoshiko2/Movie_Data_Capture/blob/a650e5483192a113c2aba971d8a3aa47841f34fc/scrapinglib/javbus.py#L41-L46
> 
> 都无法访问，域名好像都掉了，这个意义是什么？封IP的问题不应该通过代理池解决吗

反正我是把这些都删掉重新编译了下，现在快多了

**Comment by Bluefissure** [comment]
[去除了javbus镜像的版本](https://mega.nz/file/xaJzxIKD#0-GJzxKpSJLZ43UiP1O6i548mPTaAvGMLf6x2ckbzC8)
