### ISSUE TITLE
6.3.2 翻译title会把元数据的originaltitle也翻译了，但翻译actor name却不翻译

### ISSUE THREAD

**Issue by oDaShuTz** [yoshiko2/Movie_Data_Capture#912]
**Describe the bug 错误描述**
Describe clearly and concisely what the error is
6.3.2 翻译title会把元数据的originaltitle也翻译了，但翻译actor name却不翻译

**To Reproduce 如何重现BUG**
重现行为的步骤：
配置文件：
; 机器翻译
[translate]
switch=1
engine=google-free
...
values=actor,director,title,outline
service_site=translate.google.com.hk

**Screenshots BUG现状**
  目录命名的actor 为翻译后的name
  
  但元数据为
  `<title><![CDATA[MIDE-622-在正在交往男友的面前被轮奸 过于敏感的女大学生 二宫光]]></title>`
  `<originaltitle><![CDATA[MIDE-622-在正在交往男友的面前被轮奸 过于敏感的女大学生 二宫光]]></originaltitle>`
  `<sorttitle><![CDATA[MIDE-622-在正在交往男友的面前被轮奸 过于敏感的女大学生 二宫光]]></sorttitle>`
   `......`
  `<actor>`
  `  <name>二宫ひかり</name>`
  `</actor>`

**Expected behavior 预期结果 **
originaltitle没配置values元数据不应该被翻译，actor配置了元数据name应该被翻译

**Running Env 运行环境**
 - OS : windows

**Comment by Juhraya** [comment]
同样发生这个问题

**Comment by oDaShuTz** [comment]
> 同样发生这个问题

我跑了一下源码，自己改了一下这个问题

**Comment by mark5231** [comment]
> > 同样发生这个问题
> 
> 我跑了一下源码，自己改了一下这个问题

这个问题是怎么改的，能提交一个PR吗？
