### ISSUE TITLE
希望能添加一个同时从多个元数据站获取数据，标签优先使用中文元数据的功能

### ISSUE THREAD

**Issue by tecsar9000** [yoshiko2/Movie_Data_Capture#919]
部分片(如DANDY-760、HND-916、HUNTA-619)抓取不到演员名字，查看发现抓取使用的元数据javbus里就没有演员信息。请问能否添加一个同时从多个网站抓取，优先使用中文元数据，只有空值项目才使用其他的元数据站来获取的功能？

**Comment by mark5231** [comment]
javdb的比较全。
