### ISSUE TITLE
部份影片outline 使用javbus/avno1 時只會顯示馬賽克破壞版,不是正確的中文劇情簡介

### ISSUE THREAD

**Issue by Prettyloveyyq** [yoshiko2/Movie_Data_Capture#924]
**错误描述**
部份影片outline 使用javbus/avno1 時只會顯示馬賽克破壞版,不是正確的中文劇情簡介

**如何重现BUG**
1.  使用以下config.ini

> [common]
> main_mode=3
> source_folder=./
> failed_output_folder=failed
> success_output_folder=JAV_output
> link_mode=0
> scan_hardlink=0
> failed_move=0
> auto_exit=0
> translate_to_sc=0
> multi_threading=0
> actor_gender=female
> del_empty_folder=1
> nfo_skip_days=0
> ignore_failed_list=0
> download_only_missing_images=1
> mapping_table_validity=7
> sleep=3
> 
> [advenced_sleep]
> stop_counter=0
> rerun_delay=0
> 
> [proxy]
> switch=0
> type=socks5h
> proxy=127.0.0.1:1080
> timeout=20
> retry=3
> cacert_file=
> 
> [Name_Rule]
> location_rule=number+'-R'
> naming_rule=number
> max_title_len=50
> 
> [update]
> update_check=1
> 
> [priority]
> website=javbus,airav,jav321,fanza,xcity,mgstage,fc2,avsox,dlsite,carib,madou,mv91,getchu,javdb,gcolle
> 
> [escape]
> literals=\()/
> folders=failed,JAV_output
> 
> [debug_mode]
> switch=0
> 
> [translate]
> switch=0
> engine=google-free
> key=
> delay=1
> values=title,outline
> service_site=translate.google.hk
> 
> [trailer]
> switch=0
> 
> [uncensored]
> uncensored_prefix=S2M,BT,LAF,SMD,SMBD,SM3D2DBD,SKY-,SKYHD,CWP,CWDV,CWBD,CW3D2DBD,MKD,MKBD,MXBD,MK3D2DBD,MCB3DBD,MCBD,RHJ,MMDV
> 
> [media]
> media_type=.mp4,.avi,.rmvb,.wmv,.mov,.mkv,.flv,.ts,.webm,.iso,.mpg,.m4v
> sub_type=.smi,.srt,.idx,.sub,.sup,.psb,.ssa,.ass,.usf,.xss,.ssf,.rt,.lrc,.sbv,.vtt,.ttml
> 
> ; 水印
> [watermark]
> switch=1
> water=2
> 
> [extrafanart]
> switch=1
> parallel_download=5
> extrafanart_folder=extrafanart
> 
> [storyline]
> switch=1
> site=1:avno1,4:airavwiki
> censored_site=2:airav,5:xcity,6:amazon
> uncensored_site=3:58avgo
> run_mode=1
> show_result=2
> 
> [cc_convert]
> mode=2
> vars=outline,series,studio,tag,title
> 
> [javdb]
> sites=38,39,40
> 
> [face]
> locations_model=hog
> uncensored_only=1
> aways_imagecut=0
> aspect_ratio=2.12
> 
> [jellyfin]
> multi_part_fanart=0
> 
> [actor_photo]
> download_for_kodi=0

2. 刮取IPX-815-C.mp4

3. outline只顯示"馬賽克破壞版",不是正確的中文劇情簡介

> outline![CDATA[IPX-815#馬賽克破壞版 IPX-815 西宮夢]]/outline
> plot![CDATA[IPX-815#馬賽克破壞版 IPX-815 西宮夢]]/plot

**预期结果 **
顯示正確的中文劇情簡介

 
**日志**
> [*]================= Movie Data Capture =================
> [*]                        6.4.1
> [*]======================================================
> [*] - Windows-10-10.0.22000-SP0
> [*] - AMD64 - Python-3.9.13
> [*]======================================================
> [*] - 严禁在墙内宣传本项目 -
> [*]======================================================
> [+]Start at 2022-11-20 00:02:05
> [+]Load Config file 'F:\download\org\nfofix\a\config.ini'.
> [+]Enable debug
> [+]Main Working mode ## 3: Scraping in analysis folder ##
> [!]Metadata IPX-815-C.nfo not found for 'F:\download\org\nfofix\a\IPX-815-C.mp4'
> [+]Find 1 movies.
> [*]======================================================
> [!]                - 100.% [1/1] -             00:02:05
> [!] [IPX-815] As Number Processing for 'F:\download\org\nfofix\a\IPX-815-C.mp4'
> [+]select madou
> [+]select javbus
> [!]Storyline线程池模式运行4个任务共耗时(含启动开销)0.982秒，结束于00:02:09，[选中avno1字数:18]，airav字数:35，airavwiki:空，xcity:空
> [+]Find movie [IPX-815] metadata on website 'javbus'
> [+] ------- DEBUG INFO -------
> [+]  - actor               : 西宮ゆめ
> [+]  - cover               : https://www.javbus.com/pics/cover/8qxy_b.jpg
> [+]  - cover_small         :
> [+]  - director            : イナバール
> [+]  - extrafanart         : 12 links
> [+]  - imagecut            : 1
> [+]  - label               : 禁欲の果て、汗と絶頂汁まみれで交わりまくった3日間
> [+]  - number              : IPX-815
> [+]  - outline             : 18 characters
> [+]  - release             : 2022-02-04
> [+]  - runtime             : 189
> [+]  - series              : 禁慾の果て、汗と絶頂汁まみれで交わりまくった3日間
> [+]  - source              : javbus
> [+]  - studio              : S級素人
> [+]  - tag                 : ['ティッシュ', '禁欲の果て、汗と絶頂汁まみれで交わりまくった3日間', '單體作品', '4K', 'DMM 獨家', '美少女', '潮吹', '接吻', '流汗', '癡女', '數位馬賽克']
> [+]  - title               : 禁慾の果て、汗と絶頂汁まみれで交わりまくった3日間 西宮ゆめ
> [+]  - trailer             :
> [+]  - uncensored          : False
> [+]  - userrating          :
> [+]  - uservotes           :
> [+]  - website             : https://www.javbus.com/IPX-815
> [+]  - original_title      : 禁欲の果て、汗と絶頂汁まみれで交わりまくった3日間 西宮ゆめ
> [+]  - actor_list          : ['西宮ゆめ']
> [+]  - naming_rule         : IPX-815
> [+] ------- DEBUG INFO -------
> [+]Image Downloaded! IPX-815-C-fanart.jpg
> [+]Successfully downloaded 12 extrafanarts.
> [!]Extrafanart download ThreadPool mode runtime 1.681s
> [+]Image Cutted!     IPX-815-C-poster.jpg
> [+]Add Mark:         字幕
> [+]Wrote!            F:\download\org\nfofix\a\IPX-815-C.nfo
> [*]======================================================
> [+]Deleting empty folder F:\download\org\nfofix\a\failed
> [+]Running time 0:00:08.806  End at 2022-11-20 00:02:14
> [+]All finished!!!

**运行环境**
 - OS : Windows-10-10.0.22000-SP0 
 - Python Version : Python-3.9.13

**Comment by LoserForever88** [comment]
`site=1:avno1,4:airavwiki
censored_site=2:airav,5:xcity,6:amazon
uncensored_site=3:58avgo`

我也有這個問題，無論我搞了大半天怎樣調這個一樣是破壞版，非常別扭，我用的是javdb削刮。
另外有些是日文簡介，有些是中文也很不一致

作者好像不怎樣在這裡解答問題了，不知道是不是只顧TG群裡的人...
