### ISSUE TITLE
pacopacomama & CAPPV 好像無法分類 希望能新增@@" win7已無法使用...

### ISSUE THREAD

**Issue by showcutes** [yoshiko2/Movie_Data_Capture#940]
For the new functions you need, you can contact me through the contact information below for a paid solution. I will respond as soon as possible and deliver it in the next version.

对于需要的新功能，可通过下方联系方式联系我有偿解决（支持众筹），我会尽快响应，会在下一个版本交付

# 联系方式 Contact：
* Email    : yoshiko2.dev@gmail.com
* Telegram : https://t.me/yoshiko2

**Comment by Marce1ek** [comment]
![QQ截图20221204143348](https://user-images.githubusercontent.com/99329516/205477917-b719cd63-fb12-4cea-8cde-6e32b1182a3a.jpg)
这么大的字就在联系方式下面 看得到联系方式看不到这个😀
