### ISSUE TITLE
刮削无码影片时出错

### ISSUE THREAD

**Issue by zhengweiqing** [yoshiko2/Movie_Data_Capture#951]
**Describe the bug 错误描述**
影片名称中含有 -001 字符时就会出错，例如：

> 091722-001.avi
如果把文件名修改为 091722-00.avi 、091722-01.avi、091722-002.avi都可以正常刮削，但是只要是091722-001.avi就会出错

**To Reproduce 如何重现BUG**
重现行为的步骤：
1. 新建一个文件夹，名称随意
2. 新建文件，取名为：091722-001.avi
3. 使用docker版本进行刮削
4. 提示出错

 
**Logs 日志**
```
 docker run --rm --name mdc -v "/volume4/Emby/无码/2023-01":/data -v /volume1/docker/mdc/config:/config -e UID=1026 -e GID=101 vergilgao/mdc:latest
---Setup Timezone to Asia/Shanghai---
---Checking if UID: 1026 matches user---
---Checking if GID: 101 matches user---
usermod: no changes
---Setting umask to 002---
---Taking ownership of data...---
Checking if config file exist
Starting...
Illegal instruction (core dumped)
```

**Running Env 运行环境**
 - OS :群晖Docker
 - Python Version : 3.9

**Comment by zhengweiqing** [comment]
> #887 试一下这个 issue 里面提到的

这个 issue 里说的是因为图片裁剪问题导致的，我说的问题是因为.mp4/.avi等视频文件的文件名导致的。我刚才又测试了一下，如果文件名中含有空格也洗，但是windows版就没问题，只有linux版本才会出来这个问题

**Comment by Vic-TT** [comment]
相同问题，但是用887的方案留空无效
