### ISSUE TITLE
FC2刮削的影片没有女优的信息

### ISSUE THREAD

**Issue by zs2766** [yoshiko2/Movie_Data_Capture#957]
刮削出来后演员那里只有素人什么的,或者拍摄制作的名字,并不是女优的名字,我目前知道一个网站总结了所有fc2演员的信息,根据一个fc2可以找到该女主的所有片,上面有演员信息,建议fc2从这个网站刮削!
https://db.msin.jp/

**Comment by harryruo** [comment]
正在找FC2的查询网站 感谢哥 哈哈
