### ISSUE TITLE
main_mode=3时无法输出nfo文件

### ISSUE THREAD

**Issue by Izumiko** [yoshiko2/Movie_Data_Capture#967]
**Describe the bug 错误描述**
Describe clearly and concisely what the error is
main_mode=3时，输出会报`Write failed!`错误

检查后发现是core.py的[1029行](https://github.com/yoshiko2/Movie_Data_Capture/blob/fee7873b68ec1dd8e94c8eead01de3bad7d8e8e9/core.py#L1029)在调用`print_files`时传递参数的顺序出错了，把`_4k`移动至`fanart_path`前就能修复bug。

**To Reproduce 如何重现BUG**
重现行为的步骤：
1. config.ini设置main_mode=3
2. 启动刮削

**Expected behavior 预期结果 **
正常更新nfo文件

**Screenshots BUG发生截图**
 ```shell
[+] ------- DEBUG INFO -------
[+]Image Downloaded! DOKS-563-thumb.jpg
[+]Successfully downloaded 3 actor photo.
[+]Image Cutted!     DOKS-563-poster.jpg
[-]Write Failed!
[-] can only concatenate str (not "bool") to str
```
**Logs 日志**
Copy all or key content of the file to this
复制文件的全部或关键内容到此
无

**Running Env 运行环境**
 - OS : Debian 11.6
 - Python Version : 3.9.2

**Comment by tommyxps** [comment]
兄弟，遇到同样问题，能否分享下修改后的exe 文件？谢谢
