### ISSUE TITLE
nfo中刮削的内容为乱码

### ISSUE THREAD

**Issue by maike1860** [yoshiko2/Movie_Data_Capture#980]
配置文件如下
# 详细教程请看
# - https://github.com/yoshiko2/Movie_Data_Capture/wiki#%E9%85%8D%E7%BD%AEconfigini
[common]
main_mode = 1
source_folder = ./
failed_output_folder = 未完成
success_output_folder = 已完成
link_mode = 2
; 0: 不刮削硬链接文件 1: 刮削硬链接文件
scan_hardlink = 1
failed_move = 0
auto_exit = 1
translate_to_sc = 1
multi_threading = 1
;actor_gender value: female(♀) or male(♂) or both(♀ ♂) or all(♂ ♀ ⚧)
actor_gender = female
del_empty_folder = 1
; 跳过最近(默认:30)天新修改过的.NFO，可避免整理模式(main_mode=3)和软连接(soft_link=0)时
; 反复刮削靠前的视频文件，0为处理所有视频文件
nfo_skip_days = 30
ignore_failed_list = 0
download_only_missing_images = 1
mapping_table_validity = 7
; 一些jellyfin中特有的设置 (0:不开启， 1：开启) 比如
; 在jellyfin中tags和genres重复，因此可以只需保存genres到nfo中
; jellyfin中只需要保存thumb，不需要保存fanart
jellyfin = 0
; 开启后tag和genere只显示演员
actor_only_tag = 0
sleep = 3

[advenced_sleep]
; 处理完多少个视频文件后停止，0为处理所有视频文件
stop_counter = 0
; 再运行延迟时间，单位：h时m分s秒 举例: 1h30m45s(1小时30分45秒)  45(45秒)
; stop_counter不为零的条件下才有效，每处理stop_counter部影片后延迟rerun_delay秒再次运行
rerun_delay = 0
; 以上参数配合使用可以以多次少量的方式刮削或整理数千个文件而不触发翻译或元数据站封禁

[proxy]
;proxytype: http or socks5 or socks5h switch: 0 1
switch = 1
type = socks5h
proxy = 127.0.0.1:7890
timeout = 20
retry = 3
cacert_file =

[Name_Rule]
location_rule = actor+'/'+number
naming_rule = number+'-'+title
max_title_len = 50
; 刮削后图片是否命名为番号
image_naming_with_number = 0

[update]
update_check = 1

[priority]
website = javbus,airav,jav321,fanza,xcity,mgstage,fc2,avsox,dlsite,carib,madou,mv91,getchu,javdb,gcolle

[escape]
literals = \()/
folders = 未完成,已完成

[debug_mode]
switch = 0

; 机器翻译
[translate]
switch = 0
;可选项 google-free,azure
engine = google-free
; azure翻译密钥
key =
; 翻译延迟
delay = 1
values = title,outline
service_site = translate.google.cn

; 预告片
[trailer]
switch = 0

; 用来确定是否是无码
[uncensored]
uncensored_prefix = PT-,S2M,BT,LAF,SMD,SMBD,SM3D2DBD,SKY-,SKYHD,CWP,CWDV,CWBD,CW3D2DBD,MKD,MKBD,MXBD,MK3D2DBD,MCB3DBD,MCBD,RHJ,MMDV

[media]
; 影片后缀
media_type = .mp4,.avi,.rmvb,.wmv,.mov,.mkv,.flv,.ts,.webm,.iso,.mpg,.m4v
; 字幕后缀
sub_type = .smi,.srt,.idx,.sub,.sup,.psb,.ssa,.ass,.usf,.xss,.ssf,.rt,.lrc,.sbv,.vtt,.ttml

; 水印
[watermark]
switch = 1
water = 2
; 左上 0, 右上 1, 右下 2， 左下 3

; 剧照
[extrafanart]
switch = 1
parallel_download = 5
extrafanart_folder = extrafanart

; 剧情简介
[storyline]
switch = 1
; website为javbus javdb avsox xcity carib时，site censored_site uncensored_site 为获取剧情简介信息的
; 可选数据源站点列表。列表内站点同时并发查询，取值优先级由冒号前的序号决定，从小到大，数字小的站点没数据才会采用后面站点获得的。
; 其中airavwiki airav avno1 58avgo是中文剧情简介，区别是airav只能查有码，avno1 airavwiki 有码无码都能查，
; 58avgo只能查无码或者流出破解马赛克的影片(此功能没使用)。
; xcity和amazon是日语的，由于amazon商城没有番号信息，选中对应DVD的准确率仅99.6%。如果三个列表全部为空则不查询，
; 设置成不查询可大幅提高刮削速度。
; site=
site = avno1,airavwiki,airav
censored_site = avno1,xcity,amazon,airav
uncensored_site = 58avgo
; 运行模式：0:顺序执行(最慢) 1:线程池(默认值) 2:进程池(启动开销比线程池大，并发站点越多越快)
run_mode = 1
; show_result剧情简介调试信息 0关闭 1简略 2详细(详细部分不记入日志)，剧情简介失效时可打开2查看原因
show_result = 0

; 繁简转换 繁简转换模式mode=0:不转换 1:繁转简 2:简转繁
[cc_convert]
mode = 1
vars = outline,series,studio,tag,title

[javdb]
sites = 38,39,40

; 人脸识别 locations_model=hog:方向梯度直方图(不太准确，速度快) cnn:深度学习模型(准确，需要GPU/CUDA,速度慢)
; uncensored_only=0:对全部封面进行人脸识别 1:只识别无码封面，有码封面直接切右半部分
; aways_imagecut=0:按各网站默认行为 1:总是裁剪封面，开启此项将无视[common]download_only_missing_images=1总是覆盖封面
; 封面裁剪的宽高比可配置，公式为aspect_ratio/3。默认aspect_ratio=2.12: 适配大部分有码影片封面，前一版本默认为2/3即aspect_ratio=2
[face]
locations_model = cnn
uncensored_only = 1
aways_imagecut = 0
aspect_ratio = 2.12

[jellyfin]
multi_part_fanart = 0

[actor_photo]
download_for_kodi = 0

输出结果如下
<?xml version="1.0" encoding="UTF-8" ?>
<movie>
  <title><![CDATA[121521-001-[VR] πé╗πââπé»πé╣πéóπâöπâ╝πâ½πüèσºëπüòπéô πÇ£τ╗¥σªÖΦêîµèÇπüºΦ»▒µâæΣ╕¡σç║πüùSEXπÇ£]]></title>
  <originaltitle><![CDATA[121521-001-[VR] πé╗πââπé»πé╣πéóπâöπâ╝πâ½πüèσºëπüòπéô πÇ£τ╗¥σªÖΦêîµèÇπüºΦ»▒µâæΣ╕¡σç║πüùSEXπÇ£]]></originaltitle>
  <sorttitle><![CDATA[121521-001-[VR] πé╗πââπé»πé╣πéóπâöπâ╝πâ½πüèσºëπüòπéô πÇ£τ╗¥σªÖΦêîµèÇπüºΦ»▒µâæΣ╕¡σç║πüùSEXπÇ£]]></sorttitle>
  <customrating>JP-18+</customrating>
  <mpaa>JP-18+</mpaa>
  <set>πé½πâ¬VR</set>
  <studio>σèáσïÆµ»ö</studio>
  <year>2021</year>
  <outline><![CDATA[121521-001#πé╣πâ¼πâ│πâÇπâ╝τ╛ÄΣ║║πüºπü¿πü½πüïπüÅπé¿πââπâüπü¬Φ»▒µâæπüèσºëπüòπéôπÇüµƒèπé╖πé¿πâ½πÇéπü«πüúπüæπüïπéëπéóπé»πâ¬πâ½µ¥┐πüºπé¿πââπâüπüÖπüÄπéïπâÖπâ¡πâüπâÑπéªπÇéπâÉπâ╝πâüπâúπâ½πüºπé╖πé¿πâ½πüíπéâπéôπü½Σ╣ùπüúπüïπéëπéîΦêîπéÆσ╖ºπü┐πü½Σ╜┐πüäπü¬πüîπéëπüÖπéïπâòπéºπâ⌐πéäΦç¬πéëΦà░πéÆµî»πéïΘ¬æΣ╣ùΣ╜ìπüîπé¿πâ¡πüÖπüÄπüºπüÖ∩╝üµ£ÇσÉÄπü»πééπüíπéìπéôπâ₧πâ│πé│πü½Σ╕¡σç║πüùπüùπÇüπü▒πüúπüÅπéèπü¿Mσ¡ùπüºσ╝ÇΦäÜπüùπü¿πéìπâ╝πéèµ╡üπéîπéïπé╢πâ╝πâíπâ│πéÆΦºüπü¢πüªπüÅπéîπü╛πüùπüƒπÇéµÿ»Θ¥₧VRπé┤πâ╝πé░πâ½πéÆΦúàτ¥Çπüùπüªπé¿πââπâüπüÖπüÄπéïπé╖πé¿πâ½πüíπéâπéôπü«πâòπéºπâ⌐πéäΣ╕¡σç║πüùπé╗πââπé»πé╣πéÆπüèµÑ╜πüùπü┐πüÅπüáπüòπüä∩╝ü]]></outline>
  <plot><![CDATA[121521-001#πé╣πâ¼πâ│πâÇπâ╝τ╛ÄΣ║║πüºπü¿πü½πüïπüÅπé¿πââπâüπü¬Φ»▒µâæπüèσºëπüòπéôπÇüµƒèπé╖πé¿πâ½πÇéπü«πüúπüæπüïπéëπéóπé»πâ¬πâ½µ¥┐πüºπé¿πââπâüπüÖπüÄπéïπâÖπâ¡πâüπâÑπéªπÇéπâÉπâ╝πâüπâúπâ½πüºπé╖πé¿πâ½πüíπéâπéôπü½Σ╣ùπüúπüïπéëπéîΦêîπéÆσ╖ºπü┐πü½Σ╜┐πüäπü¬πüîπéëπüÖπéïπâòπéºπâ⌐πéäΦç¬πéëΦà░πéÆµî»πéïΘ¬æΣ╣ùΣ╜ìπüîπé¿πâ¡πüÖπüÄπüºπüÖ∩╝üµ£ÇσÉÄπü»πééπüíπéìπéôπâ₧πâ│πé│πü½Σ╕¡σç║πüùπüùπÇüπü▒πüúπüÅπéèπü¿Mσ¡ùπüºσ╝ÇΦäÜπüùπü¿πéìπâ╝πéèµ╡üπéîπéïπé╢πâ╝πâíπâ│πéÆΦºüπü¢πüªπüÅπéîπü╛πüùπüƒπÇéµÿ»Θ¥₧VRπé┤πâ╝πé░πâ½πéÆΦúàτ¥Çπüùπüªπé¿πââπâüπüÖπüÄπéïπé╖πé¿πâ½πüíπéâπéôπü«πâòπéºπâ⌐πéäΣ╕¡σç║πüùπé╗πââπé»πé╣πéÆπüèµÑ╜πüùπü┐πüÅπüáπüòπüä∩╝ü]]></plot>
  <runtime>00:45:36</runtime>
  <director></director>
  <poster>poster.jpg</poster>
  <thumb>thumb.jpg</thumb>
  <fanart>fanart.jpg</fanart>
  <actor>
    <name>µƒèπé╖πé¿πâ½</name>
    <thumb>https://www.caribbeancom.com/box/search_act/7901/images/top.jpg</thumb>
  </actor>
  <maker>σèáσïÆµ»ö</maker>
  <label>πé½πâ¬VR</label>
  <tag>µùáτáü</tag>
  <tag>τ╛ÄΣ╣│</tag>
  <tag>Σ╕¡σç║</tag>
  <tag>µùáµ»¢</tag>
  <tag>µîëµæ⌐µúÆ</tag>
  <tag>τ¬êτ¬ò</tag>
  <tag>µ╖½Φ»¡</tag>
  <tag>τ╛ÄΦà┐</tag>
  <tag>τ╛Äσ░╗</tag>
  <genre>µùáτáü</genre>
  <genre>τ╛ÄΣ╣│</genre>
  <genre>Σ╕¡σç║</genre>
  <genre>µùáµ»¢</genre>
  <genre>µîëµæ⌐µúÆ</genre>
  <genre>τ¬êτ¬ò</genre>
  <genre>µ╖½Φ»¡</genre>
  <genre>τ╛ÄΦà┐</genre>
  <genre>τ╛Äσ░╗</genre>
  <num>121521-001</num>
  <premiered>2021-12-15</premiered>
  <releasedate>2021-12-15</releasedate>
  <release>2021-12-15</release>
  <cover>https://www.caribbeancom.com/moviepages/121521-001/images/l_l.jpg</cover>
  <website>https://www.caribbeancom.com/moviepages/121521-001/index.html</website>
</movie>

另外发现一个配置说明文件与实际文件不一致的情况，不知道以哪个为准
说明文件如下
影片标签翻译至简体中文
[common]
transalte_to_sc = 1

配置文件如下
translate_to_sc = 1

**Comment by Karitsuki** [comment]
换一个刮削网站试试
手动更改一下配置文件里的刮削网站优先级
