### ISSUE TITLE
6.5.2 版無法執行

### ISSUE THREAD

**Issue by robinsonxd** [yoshiko2/Movie_Data_Capture#995]
**Describe the bug 错误描述**
Describe clearly and concisely what the error is
清晰简洁地描述错误是什么

**To Reproduce 如何重现BUG**
重现行为的步骤：

**Expected behavior 预期结果 **
对您期望发生的事情进行清晰简洁的描述

**Screenshots BUG发生截图**
 
**Logs 日志**
Copy all or key content of the file to this
复制文件的全部或关键内容到此
Logs location:
Windows : C:/Users/username/.mlogs/
Linux/MacOS/BSD: /home/username/.mlogs/

**Running Env 运行环境**
 - OS :
 - Python Version : 3.x

**Comment by robinsonxd** [comment]
win10 執行6.5.2版的時候都完全不會動，但6.4.1版可以
但是昨天用6.4.1版javdb的 無法刮削

**Comment by flyingsnowing** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
